### ISSUE TITLE
Redis AUTH password is not available in sentinel helm charts. 

### ISSUE THREAD

**Issue by ericklife28** [OT-CONTAINER-KIT/redis-operator#1018]
**What version of redis operator are you using?**

0.16.4

**Does this issue reproduce with the latest release?**

Yes. It does

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

Client Version: v1.28.8
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.9-gke.1289000

</pre></details>

**What did you do?**

According to your release history, there is already a feature to set a RedisReplicationPassword option into the redis sentinel config, as you can see here 

https://github.com/OT-CONTAINER-KIT/redis-operator/pull/734/files

I have created this configuration, based on the test example https://github.com/OT-CONTAINER-KIT/redis-operator/pull/734/files#diff-ef3c52a539d729cf9b217114d1f22b7cfb1f33dc50ab5f02bd61007a56a035b6 

redisSentinelConfig:
  redisReplicationName: ${redis_replication_name}
  redisReplicationPassword:
    secretKeyRef:
      name: ${redis-replication-secret}
      key: ${redis-replication-password}

However, I noticed that redis-sentinel helm chart doesn't provide an option to set  the RedisReplicationPassword option, so when I deploy my configuration it doesn't take effect. 

**What did you expect to see?**
I would like a redissentinel object with the option RedisReplicationPassword set 

**What did you see instead?**
I see a redissentinel object without the option RedisReplicationPassword set

**Comment by drivebyer** [comment]
You can use `--set redisSentinel.redisSecret.secretName=xxx` and `--set redisSentinel.redisSecret.secretKey=xxx` when deploying the Sentinel Helm chart.

**Comment by ericklife28** [comment]
Hi @drivebyer. It doesn't fix the issue. these properties  `redisSentinel.redisSecret.secretName=xxx and redisSentinel.redisSecret.secretKey` are used to set the sentinel nodes password. However, the configuration above is used to set the password that sentinel's nodes will use to communicate with the replication nodes. It is not the same.

**Comment by drivebyer** [comment]
I've got you. It will be fixed by the weekend.
