### ISSUE TITLE
[0.17.0] docker image missing from https://quay.io/repository/opstree/redis-operator

### ISSUE THREAD

**Issue by pasztorl** [OT-CONTAINER-KIT/redis-operator#1020]
Hi,

The helm chart includes this url: https://quay.io/repository/opstree/redis-operator
But there the lastest image is 0.15.1.
Can you please push the new release?
(Also helm chart crds needs to be updated)

**Comment by drivebyer** [comment]
The latest version (v0.18.0) has been pushed.
