### ISSUE TITLE
confusing redis chart repository

### ISSUE THREAD

**Issue by vramperez** [OT-CONTAINER-KIT/redis-operator#1025]
Which of the two repositories https://github.com/OT-CONTAINER-KIT/redis-operator/tree/master/charts or https://github.com/OT-CONTAINER-KIT/helm-charts/tree/main/charts should be used for redis helm charts (i.e. redis-operator, redis-cluster, redis-sentinel and redis-replication)?

It is very confusing, because in the helm-charts repository documentation it is indicated that it is the Redis charts repository, but the code is not updated, but the releases are published in this other repository.

It should be indicated somewhere in the README where to upload the PR and Issues from the Redis charts.

I myself uploaded some issues and the corresponding PRs, and I think they have been ignored, because the chart code is from this repo?

- https://github.com/OT-CONTAINER-KIT/helm-charts/issues/204
- https://github.com/OT-CONTAINER-KIT/helm-charts/issues/180
- https://github.com/OT-CONTAINER-KIT/helm-charts/issues/178

If someone clarifies me in which repo I have to upload the issues and PR, I will be happy to re-create them in the corresponding repo if necessary.

**Comment by drivebyer** [comment]
redis-operator, redis-cluster, redis-sentinel and redis-replication chart is managed by this repo.

**Comment by vramperez** [comment]
okay, thanks for clarifying. I will re-create the PR in this repo then. 

Shouldn't it be indicated in the other repo then that it is not the one for Redis charts?, in my opinion it is a bit confusing that it is duplicated (even if the other one is no longer updated).
