### ISSUE TITLE
Image tag redis-operator-0.18.1 not available

### ISSUE THREAD

**Issue by RameshPSIT** [OT-CONTAINER-KIT/redis-operator#1078]
**What version of redis operator are you using?**
redis-operator version: redis-operator : 0.18.0

**Does this issue reproduce with the latest release?**
Yes

**What did you do?**
Tried updating helm chart from v0.18.0 to v0.18.1 [redis-operator-0.18.1](https://github.com/OT-CONTAINER-KIT/helm-charts/releases/tag/redis-operator-0.18.1)

**What did you expect to see?**
New version of redis operator to be used and pod restart

**What did you see instead?**
Can't see the new v0.18.1 to be used by pods, pods do not restart.

**Comment by drivebyer** [comment]
We have upgraded the version from v0.18.0 to v0.18.1, but the appVersion remains at v0.18.0. Therefore, the latest operator image tag is still v0.18.0.
