### ISSUE TITLE
SecurityContext to manipulate kernel parameters

### ISSUE THREAD

**Issue by wangyp0701** [OT-CONTAINER-KIT/redis-operator#11]
![image](https://user-images.githubusercontent.com/33682005/85360155-e99fe900-b54a-11ea-8936-602270920445.png)

**Comment by iamabhishek-dubey** [comment]
https://github.com/OT-CONTAINER-KIT/redis-operator/blob/c42faee44f8dba4f5b7e904b6a1afad3d62f2c28/pkg/apis/redis/v1alpha1/redis_types.go#L23

It is already present. You can use define in it while deploying.
https://github.com/OT-CONTAINER-KIT/redis-operator/blob/master/example/redis-standalone-example.yaml
