### ISSUE TITLE
Can we have multiple pods for standalone setup?

### ISSUE THREAD

**Issue by banish1979** [OT-CONTAINER-KIT/redis-operator#112]
Is it possible to have multiple pods for redis standalone setup? I could see the service been configured as LoadBalancer. But could not find any configuration to increment the replica.

**Comment by iamabhishek-dubey** [comment]
Hey @banish1979 ,
That will be a bad practice to implement which can lead to application failure, standalone means a single replica. If you will have multiple replicas the data will be divided between 2 redis which are not in sync. Application will not get the proper data.
