### ISSUE TITLE
Docker image don't exist

### ISSUE THREAD

**Issue by krangerich** [OT-CONTAINER-KIT/redis-operator#1133]
When I want to install the operator using Helm, as mentioned in the documentation, the operator cannot run, because most of the docker images don't exist.

The docker image name seems to be "quay.io/opstree/redis-operator".  But there are only a few tags, as you can see here:
https://quay.io/repository/opstree/redis-operator?tab=tags

So I'm wondering, how anyone is supposed to use the operator, if there are no docker images? If I am not missing anything, there should be a build pipeline with automatic image push to the repository.

**Comment by drivebyer** [comment]
You should use operator https://github.com/OT-CONTAINER-KIT/redis-operator/pkgs/container/redis-operator%2Fredis-operator
