### ISSUE TITLE
redis-cluster chart 0.11.13 is not working (redis version v6.2.5) since new image published 

### ISSUE THREAD

**Issue by AharonIsraelCohen** [OT-CONTAINER-KIT/redis-operator#1170]
**What version of redis operator are you using?**
Redis Operator Chart: 0.13.1
Operator imageTag: v0.13.0

**Does this issue reproduce with the latest release?**
Not happen on the latest version

**What did you do?**
Installed the operator successfuly
Then I tried to install the redis-cluster 
redis-cluster chart version:  0.11.3
redis image: v6.2.5

And then I got in the logs:
`*** FATAL CONFIG FILE ERROR (Redis 6.2.5) ***
Reading the configuration file, at line 16
>>> 'cluster-announce-hostname redis-cluster-leader-0'
Bad directive or wrong number of arguments`

Then I noticed here -> https://quay.io/repository/opstree/redis?tab=tags
that new version published few month ago, I try to install with the old 6.2.5 sha256:aa634cd690da99d801073fcb4531026f1cc71d3a34c5d5f4f2021c938533107b
And it worked.

**Comment by jiangjian0920** [comment]
Yes, I also encountered this issue. Switching to the old image solved it. Thanks for the reminder.

**Comment by AharonIsraelCohen** [comment]
I must inform that you can use the new 6.2.5 version image but with latest redis-cluster chart version.
https://github.com/OT-CONTAINER-KIT/redis-operator/issues/1172
