### ISSUE TITLE
Do you support  set up Redis Cluster using a deployment?

### ISSUE THREAD

**Issue by LaryCaka** [OT-CONTAINER-KIT/redis-operator#118]
Do you support  set up Redis Cluster using a deployment? I can't find the relevant instructions in guide

**Comment by iamabhishek-dubey** [comment]
No, it supports using the statefulset only. But what issue statefulset is causing you?

**Comment by LaryCaka** [comment]
I only see deployment based on using helm command to setup redis cluster，Since my server has no network status, I want to use “kubectl apply -f ”command to&nbsp;setup redis cluster.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OT-CONTAINER-KIT/redis-operator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月27日(星期二) 中午12:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OT-CONTAINER-KIT/redis-operator] Do you support  set up Redis Cluster using a deployment? (#118)





 
No, it supports using the statefulset only. But what issue statefulset is causing you?

**Comment by iamabhishek-dubey** [comment]
Check this folder
https://github.com/OT-CONTAINER-KIT/redis-operator/tree/master/example

**Comment by iamabhishek-dubey** [comment]
Closing this issues
