### ISSUE TITLE
Unable to connect to cluster using redis-cli

### ISSUE THREAD

**Issue by blackfly19** [OT-CONTAINER-KIT/redis-operator#138]
I followed this documentation for exposing redis: https://ot-container-kit.github.io/redis-operator/guide/exposing-redis.html#exposing-service
I set up a redis standalone on kind cluster but I am unable to connect to it using redis-cli. It shows connection timed out after a few minutes.
Is there any way I can access redis on the cluster using redis-cli?

**Comment by iamabhishek-dubey** [comment]
Have you tried using `NodePort`?

**Comment by blackfly19** [comment]
That worked. Thank you so much. Is there anyway I can get the url to the cluster? I tried connecting redis-cli to this url but it didn't work.
redis://redis-0.ot-operators.svc.cluster.local:6379/0

**Comment by iamabhishek-dubey** [comment]
you are missing service name after redis-0, ideally, it should be 

```
redis://redis-0.redis-standalone-headless.ot-operators.svc.cluster.local:6379/0
```

Better approach would be directly using the name of the headless service only
