### ISSUE TITLE
ipv6 is not supporting 

### ISSUE THREAD

**Issue by pradyumna268** [OT-CONTAINER-KIT/redis-operator#139]
We are having ipv6 deployed cluster in which we have deployed redis-operator and getting the below like error from redis-operator logs  :

ERROR	controller_redis	Could not execute command	{"Request.RedisManager.Namespace": "rcp-harbor", "Request.RedisManager.Name": "redis-cluster", "Command": ["redis-cli", "--cluster", "create", "140b:a0a0:204:546d:b414:2:0:44fd:6379", "We are having ipv6 deployed cluster in which we have deployed redis-operator and getting the below like error from redis-operator logs:6379", "140b:a0a0:204:546d:b414:2:0:4a05:6379", "--cluster-yes", "-a", "redis123"], "Output": "", "Error": "Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.\nCould not connect to Redis at 140b:a0a0:204:546d:b414:2:0:44fd:6379: Connection refused\n", "error": "command terminated with exit code 1"}

```
2021-08-23T09:45:10.655Z	ERROR	controller_redis	Redis command failed with this error	{"Request.RedisManager.Namespace": "rcp-harbor", "Request.RedisManager.Name": "redis-cluster", "error": "dial tcp: address `140b:a0a0:204:546d:b414:2:0:44fd:6379:` too many colons in address"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132
redis-operator/k8sutils.checkRedisCluster
	/workspace/k8sutils/redis.go:122
redis-operator/k8sutils.CheckRedisNodeCount
	/workspace/k8sutils/redis.go:173
redis-operator/controllers.(*RedisClusterReconciler).Reconcile
	/workspace/controllers/rediscluster_controller.go:107
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:263
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:235
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:198
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185
k8s.io/apimachinery/pkg/util/wait.UntilWithContext
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:99
```

Could you please help here ? 

Based on our experience with ipv6 , redis ipv6 address supposed to be in square brackets [140b:a0a0:204:546d:b414:2:0:4a05]:6379 .

**Comment by iamabhishek-dubey** [comment]
Hey @pradyumna268 ,

Ipv6 support is not there but I am adding it to the backlog, we will try to add this feature in the future.

**Comment by davidcollom** [comment]
Hey @pradyumna268 I've raised a PR - #152 for IPv6 support, would love to hear your thoughts/feedback on this, as I don't have access to an IPv6 cluster right now.
