### ISSUE TITLE
Leader/Follower separate anti-affinity/affinity rules

### ISSUE THREAD

**Issue by zposloncec** [OT-CONTAINER-KIT/redis-operator#142]
Hi,

currently, we can define unique anti-affinity rules for leaders and followers pods which results In the same type of pods running on the same hosts. If we have 3 hosts, we want to run 3 leaders with anti-affinity and 3 followers with affinity rules based on leaders. So 1 leader and 1 follower will run on the same host.

`NAME                       READY   STATUS    RESTARTS   AGE     IP            NODE                             NOMINATED NODE   READINESS GATES`
`redis-cluster-follower-0   2/2     Running   0          2m      10.50.6.205   aks-common-50765233-vmss000002   <none>           <none>`
`redis-cluster-follower-1   2/2     Running   0          63s     10.50.5.114   aks-common-50765233-vmss000001   <none>           <none>`
`redis-cluster-follower-2   1/2     Running   0          19s     10.50.6.135   aks-common-50765233-vmss000002   <none>           <none>`
`redis-cluster-leader-0     2/2     Running   0          2m42s   10.50.6.104   aks-common-50765233-vmss000002   <none>           <none>`
`redis-cluster-leader-1     2/2     Running   0          81s     10.50.3.254   aks-common-50765233-vmss000000   <none>           <none>`
`redis-cluster-leader-2     2/2     Running   0          45s     10.50.6.60    aks-common-50765233-vmss000002   <none>           <none>`

with preferred rules, we're getting followers on the same nodes, and with required rules, pods can't get scheduled because all pods have the same rules.

Thanks!

**Comment by iamabhishek-dubey** [comment]
This was already in to-do list but thanks for creating an issue for same :) 

https://github.com/OT-CONTAINER-KIT/redis-operator/pull/143
