### ISSUE TITLE
Fix cluster role and role access for redis operator serviceaccount

### ISSUE THREAD

**Issue by iamabhishek-dubey** [OT-CONTAINER-KIT/redis-operator#149]

**Comment by davidcollom** [comment]
Could you fill more information out on this issue? so that others can maybe contribute/understand the issue at hand?

**Comment by iamabhishek-dubey** [comment]
Sure, right now we are using the cluster-admin cluster role attached to the serviceaccount. But as a better practice, we should create a new cluster role with the required privileges.
