### ISSUE TITLE
download ot-helm/redis-operator and install in offline environment

### ISSUE THREAD

**Issue by Auggie321** [OT-CONTAINER-KIT/redis-operator#153]
sir, 

wanna download helm repo ot-helm/redis-operator in servers, and rewrite some configuration,

then helm install redis-operator ./local directory in offline.

but could not found how to helm pull this repo.

is there have some solution pull charts ot-helm/redis-operator in local, thanks.

helm pull xxxx

**Comment by iamabhishek-dubey** [comment]
```
helm pull ot-helm/redis-operator
helm pull ot-helm/redis
helm pull ot-helm/redis-cluster
```
