### ISSUE TITLE
How to connect to cluster using a redis client?

### ISSUE THREAD

**Issue by shahinghasemi** [OT-CONTAINER-KIT/redis-operator#156]
Hello, I just followed your guides and created a new redis-cluster of 7 pods (3 leaders, 3 followers, 1 redis operator) and 4 services (2 headless and 2 clusterIP) for leaders and followers under `redis-operator` namespace.
I use `ioredis` as our redis-client. what I want to do is to connect our backend container to our redis-cluster which are both in the same cluster. however I'm confused about:
1. what URL should I use to connect? headless or clusterIP? follower or leader? or maybe something else?
2. as I understood from ioredis [docs](https://github.com/luin/ioredis#cluster) about cluster connection, we should provide multiple nodes which are in our redis-cluster however with above setup, should I use node's address or the service URL to connect to our cluster? 
3. I don't know if this is suitable, but should I use `cluster` API or default API (`ioredis()`) to connect to our cluster? 

thanks in advance.

**Comment by iamabhishek-dubey** [comment]
Hey @shahinghasemi ,

In cluster mode, you may have to define the leader and follower both inside your application code. Also, if your application is running inside the k8s, I would suggest using a headless service to make a connection.

For further discussion, you can open a discussion forum here https://github.com/OT-CONTAINER-KIT/redis-operator/discussions
