### ISSUE TITLE
Separate Leader/Follower serviceType

### ISSUE THREAD

**Issue by stoupance** [OT-CONTAINER-KIT/redis-operator#157]
Hi,

First of all, thanks for the great job!

**Is your feature request related to a problem? Please describe.**
Currently `serviceType` is the same for Leaders and Followers. This is declared into `kubernetesCconfig` (so for both of them) as `serviceType: {LoadBalancer, ClusterIP, NodePort}` with deploying a `ClusterIP` by default.
It could be handy to separate this behavior for both type of Redis nodes. Also, I noticed in a scenario we only declare leaders with:

```
redisLeader:
  replicas: 3
redisFollower:
  replicas: 0
```

Then, 4 services will still be created:
- 2 for followers: `redis-cluster-follower` and `redis-cluster-follower-headless`
- 2 for leaders `redis-cluster-leader` and `redis-cluster-leader-headless`

**Describe the solution you'd like**
Separate `serviceType` for each type of nodes (leader and follower) and not creating any `service` in case `redisFollower` = 0

**What version of redis-operator are you using?**

redis-operator version: 0.8.0

Thanks a lot!

**Comment by iamabhishek-dubey** [comment]
I think this can be fixed inside the helm chart
https://ot-container-kit.github.io/redis-operator/guide/exposing-redis.html#exposing-service

**Comment by stoupance** [comment]
@iamabhishek-dubey I read the documentation and my point is not **how** to expose the service externally to the Kubernetes cluster. The YAML file provided is exactly my point, the `externalService` will create services for both `redisLeader` and `redisFollower`. My suggestion is to separate this behavior for both of them.

Also, on the default configuration (for example with this file https://github.com/OT-CONTAINER-KIT/redis-operator/blob/master/example/advance_config/cluster.yaml) the operator will create by default 4 services:
* 2 for followers: `redis-cluster-follower` and `redis-cluster-follower-headless`
* 2 for leaders `redis-cluster-leader` and `redis-cluster-leader-headless`

Their kind (private `clusterIP` or public `LoadBalancer`) must be defined in the above YAML file into `RedisCluster.spec.kubernetesConfig`.


In other words, when your create a cluster, it automatically creates Kubernetes services of type `ClusterIP` for both the leaders AND the followers, even when the configuration is to **not deploy follower**. My cluster is composed of only `redisLeader`. The settings is cluster-wide and not "type-wide" (leader or follower)

My point is, it could be useful to separate the type of Kubernetes `services` created for both `redisLeader` and `redisFollower`. I see for example some scenarios of :
- Exposing the `redisLeader` **internally** (by default) only
- Exposing the `redisFollower`  **externally** to the Kubernetes cluster with a `type: LoadBalancer`

Another scenario (which is mine)
- Exposing the `redisLeader` internally (by default) only
- Not exposing the `redisFollower` at all because there is no `redisFollower` deployed.

Hope this makes more sense?
