### ISSUE TITLE
Unknown field "serviceType" in in.opstreelabs.redis.redis.v1beta1.RedisCluster.spec.kubernetesConfig

### ISSUE THREAD

**Issue by nagendra-sharman** [OT-CONTAINER-KIT/redis-operator#160]
Seeing below error while trying to run helm upgrade redis-cluster ot-helm/redis-cluster --set redisCluster.clusterSize=3 --install --namespace redis-operator

Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(RedisCluster.spec.kubernetesConfig): unknown field "serviceType" in in.opstreelabs.redis.redis.v1beta1.RedisCluster.spec.kubernetesConfig, ValidationError(RedisCluster.spec.redisFollower): unknown field "serviceType" in in.opstreelabs.redis.redis.v1beta1.RedisCluster.spec.redisFollower, ValidationError(RedisCluster.spec.redisLeader): unknown field "serviceType" in in.opstreelabs.redis.redis.v1beta1.RedisCluster.spec.redisLeader]

Also on the documentation page [https://ot-container-kit.github.io/redis-operator/guide/setup.html#redis-cluster] in many places the commands refer to ot-operator namespace instead of redis-operator which is confusing

**Comment by nagendra-sharman** [comment]
I am using redis-operator. Installed using below command.
helm upgrade redis-operator ot-helm/redis-operator --install --namespace redis-operator

helm version: 3.0.0
kubernetes version: 1.21.2

Coming to helm chart, i'm just trying to run the command from below link
https://ot-container-kit.github.io/redis-operator/guide/setup.html#redis-cluster

**Comment by iamabhishek-dubey** [comment]
@nagendra-sharman I am aware that you are using the redis cluster helm chart but what's the version of the chart?

You can check it by:-
```shell
helm ls --namespace redis-operator
```

**Comment by ahkui** [comment]
> Had same issue with standalone redis. Fixed just by commenting #serviceType: ClusterIP

how to comment this `serviceType`

**Comment by iamabhishek-dubey** [comment]
Fixed in helm chart version -> v0.9.0

**Comment by arezk84** [comment]
It's still there with standalone installation 

```
NAME          	NAMESPACE     	REVISION	UPDATED                             	STATUS  	CHART               	APP VERSION
redis-operator	redis-operator	1       	2021-12-21 18:24:36.947692 +0300 +03	deployed	redis-operator-0.9.0	0.9.0
```

**Comment by LvLs9** [comment]
Yes, it's still here

**Comment by arezk84** [comment]
@LvLs9 I disabled the validation to skip this issue while installing `--disable-openapi-validation` 🤷‍♂️

**Comment by yangtian9999** [comment]
--disable-openapi-validatio   this worked for current redis standalone version.
