### ISSUE TITLE
AOF and RDB deactivatable

### ISSUE THREAD

**Issue by monderino** [OT-CONTAINER-KIT/redis-operator#164]
Hi, 

I use the Redis Standalone version
`redisStandalone:
  image: quay.io/opstree/redis
  tag: v6.2.5`

And my question is:
Is there a way to disable AOF and RDB via the values.yaml? I tried some ways but unfortunately didn't found a solution.

**What version of redis operator are you using?**
redis-operator version: 0.8.0

**Does this issue reproduce with the latest release?**

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code></summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:31:32Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"4966fd0dded6419fd23233a38c8905c67a3ea78e", GitTreeState:"clean", BuildDate:"2021-08-17T02:06:07Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.20) exceeds the supported minor version skew of +/-1
</pre></details>

Thanks for your help.

**Comment by monderino** [comment]
Sorry that I created it as bug... it's more a question.

**Comment by zposloncec** [comment]
Hi,

I've tried to disable AOP and RDB using external config, but it's not disabled.

From within the pod:

```
bash-4.4# cat /etc/redis/external.conf.d/redis-external.conf 
appendonly no
save ""
```

```
bash-4.4# cat /etc/redis/redis.conf 
bind 0.0.0.0
protected-mode yes
tcp-backlog 511
timeout 0
tcp-keepalive 300
daemonize no
supervised no
pidfile /var/run/redis.pid
include /etc/redis/external.conf.d/redis-external.conf
masterauth ....
requirepass .....
cluster-enabled yes
cluster-node-timeout 5000
cluster-require-full-coverage no
cluster-migration-barrier 1
cluster-config-file /data/nodes.conf
save 900 1
save 300 10
save 60 10000
appendonly yes
appendfilename "appendonly.aof"
dir /data
```

```
127.0.0.1:6379> config get save
1) "save"
2) "900 1 300 10 60 10000"
127.0.0.1:6379> config get appendonly
1) "appendonly"
2) "yes"

```
