### ISSUE TITLE
Examples have been updated too soon

### ISSUE THREAD

**Issue by alex-telpis** [OT-CONTAINER-KIT/redis-operator#171]
ServiceType fields have been removed in v0.9.0 from both manifests and examples c4bb135fce25a44ac1961ba97375cb6dc8fdf312.
`spec.kubernetesConfig.serviceType`
`spec.redisLeader.serviceType`
`spec.redisFollower.serviceType`

Examples on the master branch are now lacking these fields, but they are still required in the latest version (0.8.0)

**Comment by iamabhishek-dubey** [comment]
https://github.com/OT-CONTAINER-KIT/redis-operator/tree/gh-pages --> updated
