### ISSUE TITLE
AOF and RDB deactivate not working through external_config

### ISSUE THREAD

**Issue by zposloncec** [OT-CONTAINER-KIT/redis-operator#172]
Hi,

I've tried to disable AOF and RDB using external config, but it's not disabled. Redis Operator version 0.8.0.

```
bash-4.4# cat /etc/redis/external.conf.d/redis-external.conf 
appendonly no
save ""
```

```
bash-4.4# cat /etc/redis/redis.conf 
bind 0.0.0.0
protected-mode yes
tcp-backlog 511
timeout 0
tcp-keepalive 300
daemonize no
supervised no
pidfile /var/run/redis.pid
include /etc/redis/external.conf.d/redis-external.conf
masterauth ....
requirepass .....
cluster-enabled yes
cluster-node-timeout 5000
cluster-require-full-coverage no
cluster-migration-barrier 1
cluster-config-file /data/nodes.conf
save 900 1
save 300 10
save 60 10000
appendonly yes
appendfilename "appendonly.aof"
dir /data
```

```
127.0.0.1:6379> config get save
1) "save"
2) "900 1 300 10 60 10000"
127.0.0.1:6379> config get appendonly
1) "appendonly"
2) "yes"
```

related to issue [164](https://github.com/OT-CONTAINER-KIT/redis-operator/issues/164)

**Comment by iamabhishek-dubey** [comment]
It's because AOF is by default enabled in the parent configuration file here:-

https://github.com/OT-CONTAINER-KIT/redis/blob/master/entrypoint.sh

Maybe you can remove this from the entrypoint and build a separate image for yourself. In that case, it will help

**Comment by iamabhishek-dubey** [comment]
Let me know if you need my help in doing that

**Comment by zposloncec** [comment]
Thanks!

**Comment by plachta11b** [comment]
Changing kubernetesConfig.image from v6.2.5 to [6.2.5](https://quay.io/repository/opstree/redis?tab=tags) and turning off persistence in [configmap](https://github.com/OT-CONTAINER-KIT/redis-operator/blob/c4bb135fce25a44ac1961ba97375cb6dc8fdf312/example/external_config/configmap.yaml) now works.

**Comment by alita1991** [comment]
Hi @plachta11b, tested a reconfiguration to disable AOF persistence for data restore, but for some reason, redis still see appendonly yes, using operator version 0.15.1 with standalone.
