### ISSUE TITLE
RBAC issues

### ISSUE THREAD

**Issue by disconn3ct** [OT-CONTAINER-KIT/redis-operator#176]
**What version of redis operator are you using?**
stable (v0.9.0)

```
operators/redis-operator-857656484-tbstj[manager]: E1129 15:31:09.357462       1 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156: Failed to watch *v1beta1.Redis: failed to list *v1beta1.Redis: redis.redis.redis.opstreelabs.in is forbidden: User "system:serviceaccount:operators:redis-operator" cannot list resource "redis" in API group "redis.redis.opstreelabs.in" at the cluster scope
```
redis-operator version: quay.io/opstree/redis-operator:v0.9.0

**Does this issue reproduce with the latest release?**
Yes

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:04:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What did you do?**
```shell
$ k apply -f https://operatorhub.io/install/redis-operator.yaml -n operators
$ k apply -f https://github.com/OT-CONTAINER-KIT/redis-operator/raw/master/example/redis-cluster.yaml -n other-namespace
```

**What did you expect to see?**
Redis cluster started in the `other-namespace` NS.

**What did you see instead?**
Nothing (no events) and the error log above

**Workaround/Fix**
Removing the redis* plurals from the cluster role (`redis` not `rediss`, `rediscluster` not `redisclusters`) fixed it

**Comment by iamabhishek-dubey** [comment]
Fixed PR and helm chart
