### ISSUE TITLE
Add kustomization.yaml to rbac folder

### ISSUE THREAD

**Issue by kesavkolla** [OT-CONTAINER-KIT/redis-operator#182]
Add kustomization.yaml to rbac so that we can use kustomize build for rbac also. This will make the correct order of resources for setting up RBAC

**Comment by davidcollom** [comment]
@iamabhishek-dubey We should close this issue as this is now resolved with the above/linked PR.

**Comment by iamabhishek-dubey** [comment]
@davidcollom yes :)
