### ISSUE TITLE
Add option to watch resources in a namespace and not cluster-wide

### ISSUE THREAD

**Issue by MathieuCesbron** [OT-CONTAINER-KIT/redis-operator#187]
Hello, I have tried redis-operator in a Minikube setup and it works perfectly. However, I have to use it in a Kubernetes cluster where I cannot add rights cluster-wide, it has to be namespaced. There is no option to watch only a specific namespace at the moment.

This option is not available yet, I was thinking about adding an environment variable for the namespace that would start the operator in the namespace if present, if not present, would start cluster-wide.

I would be happy to make a PR if you accept the idea.

Have a good day,

**Comment by iamabhishek-dubey** [comment]
Hey @MathieuCesbron ,

I think this is a great idea, please make a PR for same.
