### ISSUE TITLE
External-Service bug in latest helm-chart

### ISSUE THREAD

**Issue by LvLs9** [OT-CONTAINER-KIT/redis-operator#190]
We should have external service only if we strictly enabled it [as mentioned in documentation](https://ot-container-kit.github.io/redis-operator/guide/exposing-redis.html)

However by default it [automatically creates service if we have any replicas](https://github.com/OT-CONTAINER-KIT/helm-charts/blob/efc60c3a0eb069759ee1b323adeae846cc341430/charts/redis-cluster/templates/leader-service.yaml#L1)

Helm-chart version: 0.9.0

**Comment by LvLs9** [comment]
I can create pull request to fix that if you want

**Comment by iamabhishek-dubey** [comment]
@LvLs9 yes that would be great if you can create it.

**Comment by iamabhishek-dubey** [comment]
Fixed
