### ISSUE TITLE
Delete resources on redisCluster Deletion

### ISSUE THREAD

**Issue by MathieuCesbron** [OT-CONTAINER-KIT/redis-operator#192]
Hello,

When we delete a redisCluster resource, the services, pvc, etc created are not deleted via a finalizer like it is for the official mysql operator for example.

I do think it would be more elegant to delete these resources on redisCluster deletion. Right now, it is prone to resource pollution.

I would be glad to make a PR if you accept the feature.

Have a good day,

**Comment by iamabhishek-dubey** [comment]
Yes, we can do it.

**Comment by MathieuCesbron** [comment]
I created the PR #195. Also can I now when will be the next release ?
