### ISSUE TITLE
The 'Getting Started' helm command returns an error

### ISSUE THREAD

**Issue by mukundv18** [OT-CONTAINER-KIT/redis-operator#206]
**What version of redis operator are you using?**

Latest. Unable to download the latest because of the error

**Does this issue reproduce with the latest release?**

Yes.

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
v1.23.1

</pre></details>

**What did you do?**

Ran the following command

$ helm upgrade redis-operator ot-helm/redis-operator --install --namespace redis-operator

**What did you expect to see?**

Expected the command to install the redis-operator successfully. 
Note: It was tried on different systems as well

**What did you see instead?**

Release "redis-operator" does not exist. Installing it now.
Error: failed to download "ot-helm/redis-operator"

**Comment by azui007** [comment]
I have the same problem

**Comment by iamabhishek-dubey** [comment]
Have you added the repository correctly?

```
helm repo add ot-helm https://ot-container-kit.github.io/helm-charts/
```

![image](https://user-images.githubusercontent.com/26764731/153644298-cc39803d-1a62-4cb0-a2ee-fec1bea96e65.png)

**Comment by iamabhishek-dubey** [comment]
Closing this, open if the issue still persists.
