### ISSUE TITLE
0.9.0 release is missing in helm chart repo

### ISSUE THREAD

**Issue by declum** [OT-CONTAINER-KIT/redis-operator#209]
0.9.0 release is missing in provided helm chart repo.

https://github.com/OT-CONTAINER-KIT/helm-charts/issues/17

**Comment by jalonsoa** [comment]
Hi @declum !
  I opened a discussion about this 8 days ago, but I haven't had an answer yet

https://github.com/OT-CONTAINER-KIT/redis-operator/discussions/203

j

**Comment by iamabhishek-dubey** [comment]
This is fixed now.
