### ISSUE TITLE
No status in redis and redisCluster API

### ISSUE THREAD

**Issue by MathieuCesbron** [OT-CONTAINER-KIT/redis-operator#212]
Hello,

From my understanding, the status of both redis and redisCluster resource are never updated by the reconcile, so basically there is no status.

For redisStatus:
```
// RedisStatus defines the observed state of Redis
type RedisStatus struct {
	Redis RedisSpec `json:"redis,omitempty"`
}
```
For redisClusterStatus:
```
// RedisClusterStatus defines the observed state of RedisCluster
type RedisClusterStatus struct {
	RedisCluster RedisCluster `json:"redisCluster,omitempty"`
}
```
I also find it strange that it is not `Status RedisClusterStatus` in RedisCluster struct. Am I missing something ?
```
// RedisCluster is the Schema for the redisclusters API
type RedisCluster struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   RedisClusterSpec `json:"spec"`
	Status RedisClusterSpec `json:"status,omitempty"`
}
```
There should be no fields in RedisStatus and RedisClusterStatus at the moment.

Have a good day,

**Comment by iamabhishek-dubey** [comment]
Agreed, this is bug which needs to be fixed.
