### ISSUE TITLE
Support secret object making logic

### ISSUE THREAD

**Issue by zmrdltl** [OT-CONTAINER-KIT/redis-operator#221]
**Describe the solution you'd like**

When creating a custom resource called redis-standalone, I want to create and expose a service object in clusterIP type. To communicate with the corresponding redis-standalone pod provisioned in WAS or web application. 

**Describe alternatives you've considered**
If the operator can create a secret object by tying (clusterIP, redis host, and password) by checking the exposed service as well, the service binding operator will be able to inject the binding data into WAS. Is this a possible design?

**What version of redis-operator are you using?**
redis-operator version: v0.9.0

**Comment by iamabhishek-dubey** [comment]
I would suggest this is more of a custom requirement for this particular use-case, it would make sense if you use redis, redis-cluster helm chart as a dependency inside your chart and create a secret from the same helm chart instead of the operator.
