### ISSUE TITLE
Insufficient RBAC permissions for ClusterRole

### ISSUE THREAD

**Issue by youvegotmoxie** [OT-CONTAINER-KIT/redis-operator#227]
**What version of redis operator are you using?**

redis-operator version: `v0.9.0`

**Does this issue reproduce with the latest release?**

Yes, this is the latest tagged version of the operator. Didn't try with the master branch.

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.12", GitCommit:"e2a822d9f3c2fdb5c9bfbe64313cf9f657f0a725", GitTreeState:"clean", BuildDate:"2020-05-06T05:17:59Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.15", GitCommit:"2adc8d7091e89b6e3ca8d048140618ec89b39369", GitTreeState:"clean", BuildDate:"2020-09-02T11:31:21Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

</pre></details>

**What did you do?**

1. Deploy the v0.9.0 release of the operator
2. Try deploying a RedisCluster CR
3. Observe that there are errors in the operator's log output indicating insufficient permissions for `event` and `pod` resource types

**What did you expect to see?**
- I expected the operator to deploy the cluster without errors

**What did you see instead?**
- See step 3 from above

Patching the `ClusterRole` as follows resolves the issue:
```
@@ -14,7 +14,7 @@ rules:
 - apiGroups:
   - redis.redis.opstreelabs.in
   resources:
-  - rediss
+  - redis
   - redisclusters
   verbs:
   - create
@@ -47,6 +47,8 @@ rules:
   - pods/exec
   - services
   - configmaps
+  - pods
+  - events
   verbs:
   - create
   - delete
```

I also encountered issue #184 which is why there is the `rediss` section of the patch

**Comment by MathieuCesbron** [comment]
If you do not own permission to create ClusterRole in your Kubernetes, you can set it to a specific namespace. 

You can set the environment var `NAMESPACE`, it is only available in the version `v0.10.0` unfortunately.

**Comment by youvegotmoxie** [comment]
Thanks for the reply, however there doesn't seem to be a v0.10.0 chart available right now
```
helm search repo redis-operator -l
NAME                    CHART VERSION   APP VERSION     DESCRIPTION
ot-helm/redis-operator  0.9.0           0.9.0           Provides easy redis setup definitions for Kuber...
ot-helm/redis-operator  0.8.0           0.8.0           Provides easy redis setup definitions for Kuber...
ot-helm/redis-operator  0.7.0           0.7.0           Provides easy redis setup definitions for Kuber...
ot-helm/redis-operator  0.6.0           0.6.0           Provides easy redis setup definitions for Kuber...
ot-helm/redis-operator  0.5.0           0.5.0           Provides easy redis setup definitions for Kuber...
```

**Comment by iamabhishek-dubey** [comment]
Fixed in this https://github.com/OT-CONTAINER-KIT/helm-charts/commit/be516fec7ec71fd04efac8ff76d0b0e15ec67982
