### ISSUE TITLE
Bad merge in https://github.com/OT-CONTAINER-KIT/redis-operator/blob/master/config/crd/bases/redis.redis.opstreelabs.in_redisclusters.yaml

### ISSUE THREAD

**Issue by RogerParkinson** [OT-CONTAINER-KIT/redis-operator#228]
**What version of redis operator are you using?**
This applies to the master branch

the file 
https://github.com/OT-CONTAINER-KIT/redis-operator/blob/master/config/crd/bases/redis.redis.opstreelabs.in_redisclusters.yaml

has a bad merge ie there is "<<<<< HEAD" etc
so it doesn't work.

**Comment by kvendingoldo** [comment]
Created fix: https://github.com/OT-CONTAINER-KIT/redis-operator/pull/232
