### ISSUE TITLE
Adopt existing redis deployments previously managed by helm chart

### ISSUE THREAD

**Issue by lsoica** [OT-CONTAINER-KIT/redis-operator#229]
Hi,

If I have an existing Redis standalone deployment, managed currently through the Helm Chart (https://github.com/bitnami/charts/tree/master/bitnami/redis) is there a way to migrate to this operator and adopt the existing Redis deployment?

**Comment by iamabhishek-dubey** [comment]
Not right now, you can migrate the required configuration and data inside the new Redis setup by the operator.
