### ISSUE TITLE
Error log when we delete redis/redisCluster resource

### ISSUE THREAD

**Issue by MathieuCesbron** [OT-CONTAINER-KIT/redis-operator#230]
Hello,

When we delete a resource, we have an error that I did not notice previously:

![Screenshot 2022-01-28 at 21 24 06](https://user-images.githubusercontent.com/45229023/151616446-9c94a241-b9eb-4134-ac91-394f658b9c1e.png)

The finalizer works, it is an error in the logs.

I will look into correcting it a soon as I can. I am curious if anyone already know the reason of the bug.

Have a good day,

**Comment by MathieuCesbron** [comment]
I see that we have to GET the resource to be deleted and then delete it with the name AND the UID.

Example for the percona-xtradb-operator: https://github.com/percona/percona-xtradb-cluster-operator/blob/69229bd8981ae97f2e7255a3b17d4aab88078dd9/pkg/controller/pxc/controller.go#L987

I will make a PR a soon as I can.

**Comment by iamabhishek-dubey** [comment]
Fixed with the finalizer https://github.com/OT-CONTAINER-KIT/redis-operator/blob/master/k8sutils/finalizer.go
