### ISSUE TITLE
Cannot connect to cluster using python redis client with password

### ISSUE THREAD

**Issue by JC1DA** [OT-CONTAINER-KIT/redis-operator#236]
Hi, I can login into the cluster using redis-cli with password.
But when using python client to login, I got this error

`redis.exceptions.ResponseError: AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?`

I found this [article](https://medium.com/@umutuluer/resolving-the-err-client-sent-auth-but-no-password-is-set-error-b81438d10843) telling that "requirepass" is not set in the redis.conf file.
To temporarily fix this, I have to login using redis-cli and run `CONFIG SET requirepass "yourpassword"`

Are there any configurations that I can enable requirepass in redis.conf by default?

Thank you

**Comment by kvendingoldo** [comment]
you can add `requirepass "yourpassword"` to config map and provide attach it to your cluster
here is the example: https://github.com/OT-CONTAINER-KIT/redis-operator/tree/master/example/external_config

**Comment by JC1DA** [comment]
Thanks, @kvendingoldo , it works for kubectl. Can we map it using helm?

**Comment by iamabhishek-dubey** [comment]
I think you can create an issue in the helm-chart repository for the same https://github.com/OT-CONTAINER-KIT/helm-charts/tree/main/charts

**Comment by JC1DA** [comment]
Thanks, I've created an issue there. Closing this now :)
