### ISSUE TITLE
Add support of custom labels/annotation for cluster pods

### ISSUE THREAD

**Issue by kvendingoldo** [OT-CONTAINER-KIT/redis-operator#237]
In some cases, it's really useful to add user-specific labels/annotations to pods that statefulset creates.

**Comment by kvendingoldo** [comment]
@MathieuCesbron @davidcollom @Olivier-St-Pierre @iamabhishek-dubey WDYT about it?
I can implement it for RedisCluster.

**Comment by iamabhishek-dubey** [comment]
https://github.com/OT-CONTAINER-KIT/redis-operator/blob/5f45d581a9451f2c4f866f387c7d013ea8c66340/k8sutils/labels.go#L83

It's already part of the operator, you just have to define labels and annotation on the Redis and RedisCluster manifests and it will be applied.

**Comment by kvendingoldo** [comment]
@iamabhishek-dubey thank you, I've missed that.

**Comment by blbradley** [comment]
I was unable to determine where the annotations go. Can someone comment which key it is in the `Redis` resource?
