### ISSUE TITLE
Redis image `quay.io/opstree/redis` - not found

### ISSUE THREAD

**Issue by aslubsky** [OT-CONTAINER-KIT/redis-operator#24]
Hi, thanks for your awesome project. I've tried to deploy it and image `quay.io/opstree/redis` is not found or it's private.
`  Normal   BackOff  5m50s (x4190 over 16h)  kubelet, dev-node-3  Back-off pulling image "quay.io/opstree/redis:v2.0"`
 Is it possible to use the official [redis](https://hub.docker.com/_/redis) image?

**Comment by zhongxuan123** [comment]
have Dockerfile ?

**Comment by aslubsky** [comment]
pls close this issue, I've found https://github.com/bitnami/bitnami-docker-redis-cluster and it's absolutely worked for me
