### ISSUE TITLE
redis-operator helm chart v0.10.0 contains invalid yaml in crds

### ISSUE THREAD

**Issue by alfsch** [OT-CONTAINER-KIT/redis-operator#241]
**What version of redis operator are you using?**

redis-operator version: v0.10.0

**Does this issue reproduce with the latest release?**
it's the latest version

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.7", GitCommit:"1f86634ff08f37e54e8bfcd86bc90b61c98f84d4", GitTreeState:"clean", BuildDate:"2021-11-17T14:41:19Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"132a687512d7fb058d0f5890f07d4121b3f0a2e2", GitTreeState:"clean", BuildDate:"2021-05-27T23:27:49Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What did you do?**
Template the chart the first time including the crd's to see what would be installed
<pre>
 helm repo add ot-helm https://ot-container-kit.github.io/helm-charts/
 helm template redis-operator ot-helm/redis-operator --include-crds --namespace redis-operator --validate
Error: unable to build kubernetes objects from release manifest: error parsing : error converting YAML to JSON: yaml: line 3427: could not find expected ':
</pre>

rendering the templates locally shows, that some descriptions of crds are mangled.

<pre>
 helm template redis-operator ot-helm/redis-operator --include-crds --namespace redis-operator
</pre>

e.g.

<pre>
                        volumeClaimTemplate:
                          description: PersistentVolumeClaim is a user's request for
                            and claim to a persistent volume
                          properties:
                            apiVersion:
                              description: 'APIVersion defines the versioned schema
                              of this representation of an object. Servers should
                              convert recognized schemas to the latest internal value,
                              and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
                              type: string
                            kind:
</pre>

**What did you expect to see?**
<pre>
                        volumeClaimTemplate:
                          description: PersistentVolumeClaim is a user's request for
                            and claim to a persistent volume
                          properties:
                            apiVersion:
                              description: 'APIVersion defines the versioned schema
                                of this representation of an object. Servers should
                                convert recognized schemas to the latest internal value,
                                and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
                              type: string
                            kind:
</pre>

**What did you see instead?**
<pre>
                        volumeClaimTemplate:
                          description: PersistentVolumeClaim is a user's request for
                            and claim to a persistent volume
                          properties:
                            apiVersion:
                              description: 'APIVersion defines the versioned schema
                              of this representation of an object. Servers should
                              convert recognized schemas to the latest internal value,
                              and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
                              type: string
                            kind:
</pre>

Hopefully you can see the idention issues in the crd .yamls. When you extract them from redis-operator-0.10.0.tgz and load them into
a yaml editor, you can see the idention problems in some descriptions all over the files.

Currently a fresh install isn't possible.

**Comment by dm3ch** [comment]
Seems a duplicate https://github.com/OT-CONTAINER-KIT/helm-charts/issues/18
