### ISSUE TITLE
Problems encountered during installation

### ISSUE THREAD

**Issue by xiaozhimengmengda** [OT-CONTAINER-KIT/redis-operator#242]
redis-operator version:
**Does this issue reproduce with the latest release?**

# Add the helm chart
```
 helm repo add ot-helm https://ot-container-kit.github.io/helm-charts/
````
# Deploy the redis-operator]
```
$ helm upgrade redis-operator ot-helm/redis-operator --install --namespace redis-operator
```

Error: failed to install CRD crds/redis-cluster.yaml: error parsing : error converting YAML to JSON: yaml: line 3428: could not find expected ':'

```
helm pull ot-helm/redis-operator  --untar
```

</pre></details>

**What did you do?**

Open the corresponding issue and found the following error

![image](https://user-images.githubusercontent.com/26473715/154192203-086c16cf-0571-4c66-a8bf-2c289167da0e.png)

**Comment by iamabhishek-dubey** [comment]
This should be fixed now
