### ISSUE TITLE
Add support for new labels format or custom labels

### ISSUE THREAD

**Issue by ngnix** [OT-CONTAINER-KIT/redis-operator#244]
Hello team!

Thank you for your work for this operator.

We have encountered an issue that the recommended security rules are rejecting the provisioning of statefulsets created by the operator due to the use of the old label format
Can you add support for the format of the new label, like:

1. replace `app` with `app.kubernetes.io/name`
2. replace `role` with `app.kubernetes.io/role`
3. add `app.kubernetes.io/component`
4. add `app.kubernetes.io/part-of`

You can see the full recommended label list [here](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/)

We use admission controller kyverno and [best practice rules](https://kyverno.io/policies/best-practices/require_labels/require_labels/)

Or add support for custom labels.

Thanks!

**Comment by iamabhishek-dubey** [comment]
We do have the support of custom labels, you just have to pass those labels in the metadata section of redis or redis cluster spec and those will be applied to the k8s resources.
