### ISSUE TITLE
It's not possible to pull repo via go get

### ISSUE THREAD

**Issue by kvendingoldo** [OT-CONTAINER-KIT/redis-operator#247]
```
go get: github.com/OT-CONTAINER-KIT/redis-operator@none updating to
        github.com/OT-CONTAINER-KIT/redis-operator@v0.10.0: parsing go.mod:
        module declares its path as: redis-operator
                but was required as: github.com/OT-CONTAINER-KIT/redis-operator
```

**Comment by iamabhishek-dubey** [comment]
Any special use-case for which we are using `go get`?

**Comment by iamabhishek-dubey** [comment]
Closing this issue, please reopen if needed.

**Comment by fpuc** [comment]
Hi @iamabhishek-dubey I would have an use-case: If i want to  execute CRUD operations via type safe go `k8s.io/client-go` an import of the CRD https://github.com/OT-CONTAINER-KIT/redis-operator/tree/master/api/v1beta1 is needed. This can't be easily achieved if the module isn't named according to the guideline.
