### ISSUE TITLE
I created a cluster redis DB on Openshift, but I don't need the auth and I can get the keys. And I found the slave pod didn't have any function.

### ISSUE THREAD

**Issue by hanleirx** [OT-CONTAINER-KIT/redis-operator#25]
I created a cluster redis DB on Openshift, but I don't need the auth and I can get the keys.

The second question is  I found the slave pod didn't have any function. My cluster size is 3, I set a key in master 1, then I checked the other pod and their key is empty. So the data don't be sync.

**Comment by iamabhishek-dubey** [comment]
This shouldn't be the case. I will check this issue and get back to you. Thanks for reporting this issue

**Comment by iamabhishek-dubey** [comment]
Can you execute this inside redis-cli and share the output with me
```
cluster nodes
```

**Comment by iamabhishek-dubey** [comment]
Fixed in https://github.com/OT-CONTAINER-KIT/redis-operator/pull/26
