### ISSUE TITLE
SigSegv when trying to run from master

### ISSUE THREAD

**Issue by hufon** [OT-CONTAINER-KIT/redis-operator#252]
**What version of redis operator are you using?**
master

```shell
kubectl logs <_redis-operator_pod_name> -n <namespace>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1394f7b]

goroutine 411 [running]:
redis-operator/api/v1beta1.(*RedisClusterSpec).GetReplicaCounts(0xc000523318, {0x1723ec1, 0x6})
	/workspace/api/v1beta1/rediscluster_types.go:53 +0x17b
redis-operator/controllers.(*RedisClusterReconciler).Reconcile(0xc00073af60, {0xc0005357d0, 0x155b080}, {{{0xc00040dd9c, 0x1665bc0}, {0xc00040dda0, 0x30}}})
	/workspace/controllers/rediscluster_controller.go:48 +0x1ea
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc0004d4dc0, {0x193f178, 0xc0005357d0}, {{{0xc00040dd9c, 0x1665bc0}, {0xc00040dda0, 0x413a94}}})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:114 +0x26f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0004d4dc0, {0x193f0d0, 0xc0006433c0}, {0x15b06c0, 0xc00006f3a0})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:311 +0x33e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0004d4dc0, {0x193f0d0, 0xc0006433c0})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:223 +0x357
```

redis-operator version:
master
**Does this issue reproduce with the latest release?**

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"archive", BuildDate:"2021-07-22T00:00:00Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.1-1839+b93fd35dd03051-dirty", GitCommit:"b93fd35dd030519c24dd02f8bc2a7f873d2928cd", GitTreeState:"dirty", BuildDate:"2022-02-11T06:14:59Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
</summary><br><pre>
$ kubectl version

</pre></details>

**What did you do?**
Just start the operator with an existing RedisCluster

**What did you expect to see?**

**What did you see instead?**

**Comment by hufon** [comment]
I think this code is bad :

```
	instance := &redisv1beta1.RedisCluster{}

	leaderReplicas := instance.Spec.GetReplicaCounts("leader")
	followerReplicas := instance.Spec.GetReplicaCounts("follower")
```
Because it creates a new instance object, and didn't get the actual instance

**Comment by hufon** [comment]
Created a PR for this https://github.com/OT-CONTAINER-KIT/redis-operator/pull/253

**Comment by iamabhishek-dubey** [comment]
PR is merged
