### ISSUE TITLE
Annotations and labels for pods not working as intended

### ISSUE THREAD

**Issue by youvegotmoxie** [OT-CONTAINER-KIT/redis-operator#264]
**What version of redis operator are you using?**

redis-operator version: `v0.10.0`

**What did you do?**

Annotations and labels added to a Redis or RedisCluster object aren't inherited by their child objects and the CRD for both resources only allows for labels or annotations in `metadata.{labels,annotations}`

There are a similar reports for this issue here but those issues are closed:
https://github.com/OT-CONTAINER-KIT/redis-operator/pull/193#issuecomment-1061178322
https://github.com/OT-CONTAINER-KIT/redis-operator/issues/95#issuecomment-1083420692

**What did you expect to see?**

I would expect for annotations and labels added to Redis and RedisCluster objects to be inherited by the StatefulSet and Pod objects.

**What did you see instead?**

Annotations and labels are only present in the top level objects.
```
$ k get redis redis -o json | jq '.metadata.annotations'
{
  "meta.helm.sh/release-name": "redis",
  "meta.helm.sh/release-namespace": "default",
  "test.custom.annotation": "test-annotation"
}
```
```
$ k get sts redis -o json | jq '.metadata.annotations'
{
  "banzaicloud.com/last-applied": "...",
  "prometheus.io/port": "9121",
  "prometheus.io/scrape": "true",
  "redis.opstreelabs.in": "true"
}
```
```
$ k get pod redis-0 -o json | jq '.metadata.annotations'
null
```

**Comment by liortamari** [comment]
@youvegotmoxie I tetesd this feature with the master version and it works - the sts get both annotations and labels.
You need to build a docker image for the master branch.
I asked the maintainers to issue a release so we have a docker image here -> https://github.com/OT-CONTAINER-KIT/redis-operator/pull/262

**Comment by youvegotmoxie** [comment]
Thanks for the reply. I tried the `quay.io/opstree/redis-operator:0.10.0` (not `v0.10.0`) which was built a day ago off the master branch and can confirm labels and tags are being passed down to child objects now.

**Comment by ryan-pfizer** [comment]
Crumbs for future people: this was also broken in the Redis version but is now working in the latest version of the operator
