### ISSUE TITLE
How can  scale my redis-cluster at a runtime。

### ISSUE THREAD

**Issue by aaahy** [OT-CONTAINER-KIT/redis-operator#270]
**Is your feature request related to a problem? Please describe.**

I want to scale my redis-cluster at a runtime。Ex. from 3master+3slave to 5master+5slave，or from 5master+5slave 
 to 3master+3slave.
**Describe the solution you'd like**

 #modify charts from 3 to 5
[root@k8s4 ot]# vim redis-cluster/values.yaml 
redisCluster:
  clusterSize: 5
  leader:
    replicas: 5  
  follower:
    replicas: 5
#upgrade to scale
[root@k8s4 ot]# helm upgrade redis-cluster -f redis-cluster/values.yaml redis-cluster-0.10.0.tgz --namespace ot 

#finnaly,operator will help adding 2 redis-leader and 2 redis-follower to redis-cluster and operator will help migrating and rebalancing slots besides all 5leader+5follower redis node。

**What version of redis-operator are you using?**

redis-operator version:0.10.2
redis-cluster version:0.10.0
Kubernetes v1.20.14

**Additional context**

**Comment by shubham-cmyk** [comment]
https://github.com/OT-CONTAINER-KIT/redis-operator/pull/455
