### ISSUE TITLE
New leader is unable to join an existing cluster

### ISSUE THREAD

**Issue by youvegotmoxie** [OT-CONTAINER-KIT/redis-operator#271]
**What version of redis operator are you using?**

redis-operator version: `0.10.0`

**Does this issue reproduce with the latest release?**

Yes

**What did you do?**

- Deployed a RedisCluster with 3 replicas
- Ran `redis-benchmark` to add some data to the database
- Killed one of the leader pods and I'm seeing the following errors in the operator's log:
```
...
[redis-operator-7f84d6fdd7-24rfg] 1.6508901462921185e+09        ERROR   controller_redis        Could not execute command       {"Request.RedisManager.Namespace": "auto", "Request.RedisManager.Name": "redis-prr", "Command": ["redis-cli", "--cluster", "create", "100.105.60.82:6379", "100.105.24.19:6379", "100.105.97.21:6379", "--cluster-yes"], "Output": "[ERR] Node 100.105.97.21:6379 is not empty. Either the node already knows other nodes (check with CLUSTER NODES) or contains some key in database 0.\n", "Error": "", "error": "command terminated with exit code 1"}
[redis-operator-7f84d6fdd7-24rfg] redis-operator/k8sutils.ExecuteRedisClusterCommand
[redis-operator-7f84d6fdd7-24rfg]       /workspace/k8sutils/redis.go:71
[redis-operator-7f84d6fdd7-24rfg] redis-operator/controllers.(*RedisClusterReconciler).Reconcile
[redis-operator-7f84d6fdd7-24rfg]       /workspace/controllers/rediscluster_controller.go:123
[redis-operator-7f84d6fdd7-24rfg] sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
[redis-operator-7f84d6fdd7-24rfg]       /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:114
[redis-operator-7f84d6fdd7-24rfg] sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
[redis-operator-7f84d6fdd7-24rfg]       /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:311
[redis-operator-7f84d6fdd7-24rfg] sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
[redis-operator-7f84d6fdd7-24rfg]       /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266
[redis-operator-7f84d6fdd7-24rfg] sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
[redis-operator-7f84d6fdd7-24rfg]       /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227
[redis-operator-7f84d6fdd7-24rfg] 1.6508901462921746e+09        INFO    controller_redis        Successfully executed the command       {"Request.RedisManager.Namespace": "auto", "Request.RedisManager.Name": "redis-prr", "Command": ["redis-cli", "--cluster", "create", "100.105.60.82:6379", "100.105.24.19:6379", "100.105.97.21:6379", "--cluster-yes"], "Output": "[ERR] Node 100.105.97.21:6379 is not empty. Either the node already knows other nodes (check with CLUSTER NODES) or contains some key in database 0.\n"}
[redis-operator-7f84d6fdd7-24rfg] 1.6508901462921813e+09        INFO    controllers.RedisCluster        Will reconcile redis cluster operator in again 10 seconds       {"Request.Namespace": "auto", "Request.Name": "redis-prr"}
```

**What did you expect to see?**

- I expect the new leader to join the existing cluster without issue

**What did you see instead?**

- The above error repeated endlessly

**Comment by dblife1024** [comment]
I also encountered such then problem，new pod can't join to redis cluster
======================================================
Killed one of the leader pods and I'm seeing the following errors in the operator's log:

2022-05-11T09:08:33.212Z	ERROR	controller_redis	Could not execute command	{"Request.RedisManager.Namespace": "redis-operator", "Request.RedisManager.Name": "redis-cluster", "Command": ["redis-cli", "--cluster", "create", "10.100.2.34:6379", "10.100.2.36:6379", "10.100.8.5:6379", "--cluster-yes"], "Output": "[ERR] Node 10.100.2.34:6379 is not empty. Either the node already knows other nodes (check with CLUSTER NODES) or contains some key in database 0.\n", "Error": "", "error": "command terminated with exit code 1"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132
redis-operator/k8sutils.executeCommand
	/workspace/k8sutils/redis.go:276
redis-operator/k8sutils.ExecuteRedisClusterCommand
	/workspace/k8sutils/redis.go:61
redis-operator/controllers.(*RedisClusterReconciler).Reconcile
	/workspace/controllers/rediscluster_controller.go:114
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:263
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:235
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:198
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185
k8s.io/apimachinery/pkg/util/wait.UntilWithContext
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:99

**Comment by chobostar** [comment]
I see a lot errors are being ignored in code.
e.g.:
```
	if err != nil {
		logger.Error(err, "Could not execute command", "Command", cmd, "Output", execOut.String(), "Error", execErr.String())
	}
	logger.Info("Successfully executed the command", "Command", cmd, "Output", execOut.String())
```
https://github.com/OT-CONTAINER-KIT/redis-operator/blob/v0.10.0/k8sutils/redis.go#L304-L307
in other words:
```
if ok != true {
  print("oops it's error")
}
print("everything is ok")
```
if ok == false, then output would be:
```
oops it's erro
everything is ok
```
what did the developer mean?

---

Also there are text-parse logic over unexpected output, which are not ready to them:
```
	csvOutputRecords, err := csvOutput.ReadAll()
	if err != nil {
		logger.Error(err, "Error parsing Node Counts", "output", output)
	}
	return csvOutputRecords
	
```
	clusterNodes := checkRedisCluster(cr)
	count := len(clusterNodes)
```	
https://github.com/OT-CONTAINER-KIT/redis-operator/blob/aeecf234b56e4ccd7ca5a41d42c31b5366cc80c8/k8sutils/redis.go#L200-L201

wtf? We got a error, why code continues to process?
---

Thus, code is not ready to errors, operator can't provide consistent state.

**Comment by iamabhishek-dubey** [comment]
@youvegotmoxie persistence volume is attached to redis pods or not?

**Comment by youvegotmoxie** [comment]
> @youvegotmoxie persistence volume is attached to redis pods or not?

Yes, persistence was enabled
