### ISSUE TITLE
Option to make redis-operator "namespaced" is not present in the helm chart

### ISSUE THREAD

**Issue by Zeka13** [OT-CONTAINER-KIT/redis-operator#274]
Hi!

I believe this one https://github.com/OT-CONTAINER-KIT/redis-operator/pull/189 doesn't reflect in any of yours helm charts and that's just not right :)

**Comment by iamabhishek-dubey** [comment]
Closed in https://github.com/OT-CONTAINER-KIT/helm-charts/commit/91a88049019e812e9d2cebcdb30712f075090508
