### ISSUE TITLE
Data loss after simultaneous leader & follower config edit

### ISSUE THREAD

**Issue by plachta11b** [OT-CONTAINER-KIT/redis-operator#275]
I encounter this behavior in one of our tests. I consider this to be bug. I was able to workaround this by editing leader xor follower config before full configuration deployment. Configurable rollout strategy type would be helpful here.

**What version of redis operator are you using?**

redis-operator version: **v0.8.0** on openshift

**Does this issue reproduce with the latest release?**

Not sure. I can test it later if needed.

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
Client Version: 4.8.0-xxxx
Kubernetes Version: v1.22.5+xxxxxxx
</pre></details>

**What did you do?**
- Edit both `spec.redisFollower` and `spec.redisLeader` at the same time
- See your Redis cluster to burn.

**What did you expect to see?**
My data :D

**What did you see instead?**
Broken cluster. Cluster restarted both leaders and followers (two statefulsets) simultaneously causing data loss.

Maybe this is already fixed, but it would be great warn about this issue somewhere.

**Comment by iamabhishek-dubey** [comment]
It is fixed in the latest version of operator
