### ISSUE TITLE
Backup and Restore

### ISSUE THREAD

**Issue by arezvani** [OT-CONTAINER-KIT/redis-operator#281]
**Hi, I want to backup from my cluster data in kubernetes. what should i do?**

**Is there anyway to backup then restore or fork my redis database?**

**Comment by devkmsg** [comment]
Are there any thoughts on how to do this @iamabhishek-dubey?  We are starting to look at this and I think we are going to run a sidecar to copy the rdb files elsewhere.

**Comment by arezvani** [comment]
@iamabhishek-dubey thank you. Can you please help me now what should i do to have this feature? for backup i think we should use save or bgsave then copy the rdb files to elsewhere but i have many questions:
1. We should just take backup from masters? for example if we have 6 nodes with 3 master with 1 slave for each master, we should take backup from just 3 masters? how we should take backup from only masters?
2. what about nodes.conf? I think we should also take backup from cluster config in nodes.conf but my problem is k8s pod ip change and it's not stable. we should write a script to set ip?

**Comment by chobostar** [comment]
Here is overview how Redis Enterprise takes consistent backup: https://redis.com/redis-enterprise/technology/backup-disaster-recovery/

**Comment by jerry-jibu** [comment]
another possible solution is to use [velero](https://velero.io/) to backup all redis resources with data.
mentioned by @arezvani , we can exclude data from slave pods and could use hook to trigger save/bgsave before backup.

**Comment by voarsh2** [comment]
Slightly off topic, but I'm running an application that requires Redis v6 - so I am using 0.8 of the Helm Chart, I was wondering, how might I import the dump from a standalone into a freshly made cluster? Put the dumb.rdb file in /data on first boot?

**Comment by shubham-cmyk** [comment]
Should we implement using velero
