### ISSUE TITLE
Service not being created for cluster when using only `clusterSize`

### ISSUE THREAD

**Issue by ADustyOldMuffin** [OT-CONTAINER-KIT/redis-operator#285]
**What version of redis operator are you using?**

redis-operator version: 0.10.0

**Does this issue reproduce with the latest release?**

Yes

**What did you do?**

Deployed a Redis cluster using only clusterSize (not specifying replicas on leader or followers

**What did you expect to see?**

A service created for the leader and followers.

**What did you see instead?**

No service was created for either followers or leaders.

**Comment by ADustyOldMuffin** [comment]
When I add replicas to the leader and follower fields in the spec then I get a service created. When looking through the logs of the operator, it mentioned nothing around a service until the replicas are added and then when reconciled it mentions creating and getting the services.

**Comment by ADustyOldMuffin** [comment]
I'm not quite sure what causes the issue since these are made based on this condition.

https://github.com/OT-CONTAINER-KIT/redis-operator/blob/f1c547e26ece015c0c5cd8a8549ff277e8e7c2ab/controllers/rediscluster_controller.go#L72-L77

But if you go to where the condition is set, it's set to `clusterSize` by default.

https://github.com/OT-CONTAINER-KIT/redis-operator/blob/f1c547e26ece015c0c5cd8a8549ff277e8e7c2ab/api/v1beta1/rediscluster_types.go#L42-L50

**Comment by ADustyOldMuffin** [comment]
I see it was committed just a few days before tag, maybe it didn't make it?

**Comment by iamabhishek-dubey** [comment]
Yes @ADustyOldMuffin, it has been fixed in the 0.11.0 version.
