### ISSUE TITLE
The field `cr.spec.resources` is ineffective

### ISSUE THREAD

**Issue by hoyhbx** [OT-CONTAINER-KIT/redis-operator#290]
We found that the field `cr.spec.resources` is not used by the operator and thus changing it means nothing to the system state.

**What version of redis operator are you using?**

redis-operator version: We are using redis-operator built from the `HEAD` and built from the latest release

- https://github.com/OT-CONTAINER-KIT/redis-operator/commit/f1c547e26ece015c0c5cd8a8549ff277e8e7c2ab

**Does this issue reproduce with the latest release?**
Yes, the problem reproduces with `quay.io/opstree/redis-operator:v0.10.0`

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What did you do?**

I submitted a CR file in which I specified resource requests and limits in field `cr.spec.resource` .

**What did you expect to see?**
The specified resource requests and limits take effect in the redis-cluster that's created.

**What did you see instead?**
The specified resource requests and limits are ignored. They result in no change in system state.

**To reproduce, apply the below CR file**

<details><summary><code>cr_cluster.yaml</code></summary><br><pre>
apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: RedisCluster
metadata:
  name: test-cluster
spec:
  clusterSize: 3
  kubernetesConfig:
    image: quay.io/opstree/redis:v6.2.5
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 101m
        memory: 128Mi
      requests:
        cpu: 101m
        memory: 128Mi
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 1024Mi
</pre></details>

Observe that `cr.spec.resources` does not take effect as the system state reflects `cr.spec.kubernetesConfig.resources`.

**Possible Root Cause and Fix**
We suspect that the field `cr.spec.resources` is deprecated and moved to `cr.spec.kubernetesConfig.resources`. Scanning through the source code, we find that `cr.spec.resources` is not accessed and `cr.spec.kubernetesConfig.resources` is used instead [redis-cluster.go#L57](https://github.com/OT-CONTAINER-KIT/redis-operator/blob/master/k8sutils/redis-cluster.go#L57), as is also confirmed by this pull request https://github.com/OT-CONTAINER-KIT/redis-operator/pull/93.

**Comment by iamabhishek-dubey** [comment]
Fixed in https://github.com/OT-CONTAINER-KIT/redis-operator/pull/294
