### ISSUE TITLE
followers in number above the leaders number are created but not associated with the cluster

### ISSUE THREAD

**Issue by doronl** [OT-CONTAINER-KIT/redis-operator#299]
**What version of redis operator are you using?**

redis-operator version: 0.10.1

**Does this issue reproduce with the latest release?**

It is the latest version.

**What operating system and processor architecture are you using (`kubectl version`)?**

clientVersion:
  buildDate: "2022-06-17T22:28:26Z"
  compiler: gc
  gitCommit: f66044f4361b9f1f96f0053dd46cb7dce5e990a8
  gitTreeState: clean
  gitVersion: v1.24.2
  goVersion: go1.18.3
  major: "1"
  minor: "24"
  platform: linux/amd64
kustomizeVersion: v4.5.4
serverVersion:
  buildDate: "2022-06-09T18:22:07Z"
  compiler: gc
  gitCommit: e1318dce57b3e319a2e3fecf343677d1c4d4aa75
  gitTreeState: clean
  gitVersion: v1.21.13-eks-84b4fe6
  goVersion: go1.16.15
  major: "1"
  minor: 21+
  platform: linux/amd64

**What did you do?**

I put 3 leaders and 6 followers  

**What did you expect to see?**

3 leaders with 2 followers each or at least a log error that my configuration is not supported if it is not supported

**What did you see instead?**

cluster created with 3 leaders and 6 followers but only 3 of the followers were connected to the cluster the others were ignored by the operator

**Comment by iamabhishek-dubey** [comment]
Right now it's a 1:1 ratio between leader and follower. This can be an enhancement feature.
