### ISSUE TITLE
Support for Sentinel Based CRDs

### ISSUE THREAD

**Issue by samof76** [OT-CONTAINER-KIT/redis-operator#306]
Implement Sentinel installation and not just cluster installation

**Is your feature request related to a problem? Please describe.**
We most often have request for both types, Cluster and Sentinel, of installations in our environments. So it would better to manage it using a single Operator.

**Describe the solution you'd like**
One Operator to manage two types of popular Redis' HA solutiions. Have two CRs
- `RedisSentinel`
- `RedisClutser`

**Describe alternatives you've considered**

Running two operators, like one from [here](https://github.com/spotahome/redis-operator) and for clusters have ot-container-kit's operator.

**What version of redis-operator are you using?**

redis-operator version: latest(always)

**Comment by iamabhishek-dubey** [comment]
Duplicate of https://github.com/OT-CONTAINER-KIT/redis-operator/issues/146

This is already in to-do list

**Comment by shubham-cmyk** [comment]
#417  Sentinel Mode added
