### ISSUE TITLE
Could not connect to Redis at [IPv6]:6379: Name does not resolve

### ISSUE THREAD

**Issue by arif17ginanjar** [OT-CONTAINER-KIT/redis-operator#309]
**What version of redis operator are you using?**

redis-operator version: quay.io/opstree/redis-operator:v0.11.0

**Does this issue reproduce with the latest release?**

It is the latest version.

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6", GitCommit:"f59f5c2fda36e4036b49ec027e556a15456108f0", GitTreeState:"clean", BuildDate:"2022-01-19T17:33:06Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.9-eks-a64ea69", GitCommit:"540410f9a2e24b7a2a870ebfacb3212744b5f878", GitTreeState:"clean", BuildDate:"2022-05-12T19:15:31Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What did you do?**

I deploying RedisCLuster on my EKS cluster which using IPv6, the manifest I deploy is as follows
<details><summary>RedisCLuster Manifest</summary><br><pre>
apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: RedisCluster
metadata:
  name: redis
  namespace: redis-devops-production
spec:
  clusterSize: 3
  kubernetesConfig:
    image: 'quay.io/opstree/redis:v6.2.5'
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
  redisExporter:
    enabled: true
    image: 'quay.io/opstree/redis-exporter:1.0'
    imagePullPolicy: IfNotPresent
    resources: {}
  redisFollower:
    replicas: 0
  redisLeader:
    replicas: 3
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
</pre></details>

but when run it produces this error in the redis-operator
```
1.6582454610258813e+09	INFO	controller_redis	Pod Counted successfully	{"Request.RedisManager.Namespace": "redis-devops-production", "Request.RedisManager.Name": "redis", "Count": 0, "Container Name": "redis-leader"}
1.6582454611030037e+09	ERROR	controller_redis	Could not execute command	{"Request.RedisManager.Namespace": "redis-devops-production", "Request.RedisManager.Name": "redis", "Command": ["redis-cli", "--cluster", "create", "[2406:da19:716:4803:a2c5::7]:6379", "[2406:da19:716:4803:a2c5::6]:6379", "[2406:da19:716:4804:520b::8]:6379", "--cluster-yes"], "Output": "", "Error": "Could not connect to Redis at [2406:da19:716:4803:a2c5::7]:6379: Name does not resolve\n", "error": "command terminated with exit code 1"}
redis-operator/k8sutils.ExecuteRedisClusterCommand
	/workspace/k8sutils/redis.go:71
redis-operator/controllers.(*RedisClusterReconciler).Reconcile
	/workspace/controllers/rediscluster_controller.go:123
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:114
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227
1.6582454611030781e+09	INFO	controllers.RedisCluster	Will reconcile redis cluster operator in again 10 seconds	{"Request.Namespace": "redis-devops-production", "Request.Name": "redis"}
```

I did some of the following reproduces,
did an exec to one of the RedisCluster pods and tried to access another Redis pod with the following command, yielded the appropriate result
```
bash-4.4# redis-cli -h 2406:da19:716:4803:a2c5::7 -p 6379 ping
PONG
bash-4.4# redis-cli -h 2406:da19:716:4803:a2c5::7 -p 6379
[2406:da19:716:4803:a2c5::7]:6379>
```

but when doing the following reproduce
produces the same error as the redis-operator
```
bash-4.4# redis-cli --cluster create [2406:da19:716:4803:a2c5::7]:6379 [2406:da19:716:4803:a2c5::6]:6379 [2406:da19:716:4804:520b::8]:6379 --cluster-yes
Could not connect to Redis at [2406:da19:716:4803:a2c5::7]:6379: Name does not resolve
```

**What did you expect to see?**

redis-operator can be successfully perform cluster creation with redis-cli

**What did you see instead?**
for now, the cluster was not created successfully

---
I really thank you for your help in advance! 🙇

**Comment by arif17ginanjar** [comment]
I don't know if this reference is related my issue or not, but hopefully it can be helps.
https://github.com/redis/redis/issues/3076

**Comment by iamabhishek-dubey** [comment]
I guess this appending [] brackets are causing this issue

**Comment by hfinucane** [comment]
```
bash-4.4# redis-cli --cluster create [2406:da19:716:4803:a2c5::7]:6379 [2406:da19:716:4803:a2c5::6]:6379 2406:da19:716:4804:520b::8]:6379 --cluster-yes
```
the last IP address has a closing square bracket, but not an opening one.

**Comment by arif17ginanjar** [comment]
Hi @iamabhishek-dubey, 
Thank you for responding to my issue report

> I guess this appending [] brackets are causing this issue

Yeah, I think so.
But if we don't use brackets, this problem occur https://github.com/OT-CONTAINER-KIT/redis-operator/issues/139. 
And for now I'm still confused 😂, what is the right command to create a redis ipv6 cluster with redis-cli

**Comment by iamabhishek-dubey** [comment]
<img width="1461" alt="image" src="https://user-images.githubusercontent.com/26764731/198880692-94deaf18-4d09-40c6-b269-79951743d38d.png">

**Comment by arif17ginanjar** [comment]
Thanks very much, sir. @iamabhishek-dubey 🙇 🎉
