### ISSUE TITLE
when will redisConfig be ready?

### ISSUE THREAD

**Issue by zhangchl007** [OT-CONTAINER-KIT/redis-operator#31]

**Comment by iamabhishek-dubey** [comment]
In the next release

**Comment by iamabhishek-dubey** [comment]
This feature will be released in `0.6.0`

**Comment by zhangchl007** [comment]
Hi Abhishek
Got it, Thanks you!

**Comment by zhangchl007** [comment]
Hi Abhishek

I had implemented the function of redisConfig,  I am not sure if  I can submit my codes

**Comment by iamabhishek-dubey** [comment]
It's more than welcome if you want to contribute, please raise a PR. This will make my life easier :D

**Comment by dzmitry-lahoda** [comment]
oh, so i cannot disable persist with this setup?
