### ISSUE TITLE
CRD schema contains unused resources object

### ISSUE THREAD

**Issue by dosmanak** [OT-CONTAINER-KIT/redis-operator#314]
in master
https://github.com/OT-CONTAINER-KIT/redis-operator/blob/master/config/crd/bases/redis.redis.opstreelabs.in_redisclusters.yaml#L2280

This `resources` object is not used in operator deployment
e.g. here https://github.com/OT-CONTAINER-KIT/redis-operator/blob/master/k8sutils/redis-cluster.go

**Comment by iamabhishek-dubey** [comment]
The cleanup has been performed.
