### ISSUE TITLE
update redis cluster will cause one shard data to offline status?

### ISSUE THREAD

**Issue by bugme1024** [OT-CONTAINER-KIT/redis-operator#315]
**What version of redis operator are you using?**
redis 6.0
```shell
kubectl logs <_redis-operator_pod_name> -n <namespace>
```

redis-operator version:
    Image:         quay.io/opstree/redis-operator:v0.11.0
    Image ID:      quay.io/opstree/redis-operator@sha256:20b564e8aa41aeddaf3389ddd5676fc3bee5fae89dd0c1da58f980646ec4e9df

**Does this issue reproduce with the latest release?**
1. update clusrer.yaml cpu limit  param
2. kubectl apply -f cluster.yaml: make cluster to restart

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

</pre></details>

**What did you do?**

make cluster to restart

**What did you expect to see?**

<img width="1084" alt="企业微信截图_487f809c-1b9e-444e-80f1-3101c948e796" src="https://user-images.githubusercontent.com/54942365/182990694-dd27c6ec-4b05-44ee-bd5d-7988ca031c5a.png">

**What did you see instead?**

1. leader-2 and follower-2 are in terminateing status.
2. this will cause this shard data offline?

** Solution:?
check leader ready replicas before createorUpdate follower statefulset

**Comment by bugme1024** [comment]
because followers and leaders use 2 statefulset to controler pod status. and it will restart pod seperately

**Comment by godwhoa** [comment]
Noticed this problem as well. Ideally, each shard should have a statefulset then the pod disruption budget would make sense.

**Comment by iamabhishek-dubey** [comment]
I think this problem can be solved by integrating the pdb, please refer to this example:-

https://github.com/OT-CONTAINER-KIT/redis-operator/blob/master/example/disruption_budget/clusterd.yaml
