### ISSUE TITLE
latest version won't run on OCP due to runAsUser: 65532

### ISSUE THREAD

**Issue by davidkarlsen** [OT-CONTAINER-KIT/redis-operator#318]
**What version of redis operator are you using?** 

redis-operator version: v0.11.0

**Does this issue reproduce with the latest release?** 
yes

**What operating system and processor architecture are you using (`kubectl version`)?**
openshift 4.10.x

**What did you do?**

install from default from OLM from operatorhub.io

**What did you expect to see?**
it running

**What did you see instead?**
fails because of the:

```yaml
securityContext:
  runAsUser: 65532
```

**Comment by iamabhishek-dubey** [comment]
https://github.com/k8s-operatorhub/community-operators/pull/1885/files
