### ISSUE TITLE
RBAC error 

### ISSUE THREAD

**Issue by xdimedrolx** [OT-CONTAINER-KIT/redis-operator#32]
I am tryinig to install latest version from operatorhub.io, but i got error 
```Failed to watch *v1beta1.Redis: failed to list *v1beta1.Redis: redis.redis.redis.opstreelabs.in is forbidden: User "system:serviceaccount:redis-operator:redis-operator" cannot list resource "redis" in API group "redis.redis.opstreelabs.in" at the cluster scope```

How can i fix it?

**Comment by iamabhishek-dubey** [comment]
Looks like some permission got messed up at operatorhub, I will fix it by the weekend

**Comment by iamabhishek-dubey** [comment]
This will be fixed after the merge of these PRs:-
https://github.com/operator-framework/community-operators/pull/3113
https://github.com/operator-framework/community-operators/pull/3112

**Comment by iamabhishek-dubey** [comment]
PRs are merged, closing this issue

**Comment by mms-gianni** [comment]
I got version the operator version 0.11.0 and got the same messages. I installed the operator with OLM. 

@iamabhishek-dubey What am I missing here? 

```
kubectl create -f https://operatorhub.io/install/stable/redis-operator.yaml 
```

`
W1014 08:52:24.512175       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.0/tools/cache/reflector.go:167: failed to list *v1beta1.Redis: redis.redis.redis.opstreelabs.in is forbidden: User "system:serviceaccount:operators:redis-operator" cannot list resource "redis" in API group "redis.redis.opstreelabs.in" at the cluster scope
E1014 08:52:24.512226       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.0/tools/cache/reflector.go:167: Failed to watch *v1beta1.Redis: failed to list *v1beta1.Redis: redis.redis.redis.opstreelabs.in is forbidden: User "system:serviceaccount:operators:redis-operator" cannot list resource "redis" in API group "redis.redis.opstreelabs.in" at the cluster scope
`

**Comment by nick4fake** [comment]
Just happened on 0.14 after reinstall

**Comment by ReggieCarey** [comment]
I experienced this problem deploying the operator today 2 FEB 2024.  Apparently its still broken in 0.15.1

This is an RBAC issue from what I can tell.  It seems that the ClusterRole is missing some entries.

I addressed this by editing the ClusterRole redis-operator...

I added the following new rule because the Redis operator was complaining that it could not list or watch the resources which are not listed in any of the install ClusterRoles.

```- apiGroups:
  - redis.redis.opstreelabs.in
  resources:
  - redisreplications
  - redissentinels
  verbs:
  - list
  - watch
```

This eliminated the errors in the Operator log and seems to have stopped the constant restarting of the operator.

```
$ kubectl get -n operators csv
NAME                               DISPLAY                        VERSION   REPLACES                           PHASE
redis-operator.v0.15.1             Redis Operator                 0.15.1    redis-operator.v0.15.0             Succeeded
```

**Comment by puppetmaster** [comment]
I have the same issue here (28/02/2024), still broken with version 0.15.1

**Comment by captainpro-eng** [comment]
i have the same issue in latest version.

**Comment by khusseini** [comment]
same issue with version 0.15.1

**Comment by aminerachyd** [comment]
Same issue on 0.15.1 installed through operatorhub, and the fix is to manually add the resources as @ReggieCarey mentioned

**Comment by zeidlos** [comment]
Still broken here as well. Thanks to @ReggieCarey I was able to fix it manually.

**Comment by christensenjairus** [comment]
I'm having issues with this as well. I don't see a newer version in the operatorhub catalog that seems to solves this problem

**Comment by ocervell** [comment]
I'm seeing this in my operator logs:

error retrieving resource lock <NAMESPACE>/6cab913b.redis.opstreelabs.in: leases.coordination.k8s.io "6cab913b.redis.opstreelabs.in" is forbidden: User "system:serviceaccount:<NAMESPACE>:redis-operator" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "<NAMESPACE>"

This keeps printing and Redis is barely available anymore...

Any change of of you can tell me how to fix it ?
