### ISSUE TITLE
Custom probe patch cause issue with statefulset

### ISSUE THREAD

**Issue by ahiaht** [OT-CONTAINER-KIT/redis-operator#320]
**What version of redis operator are you using?**
quay.io-opstree-redis:v6.2.5
```shell
kubectl logs <_redis-operator_pod_name> -n <namespace>
```
1.6611527696951663e+09	INFO	controller_redis	Redis statefulset get action was successful	{"Request.StatefulSet.Namespace": "nprod-blue-test-app", "Request.StatefulSet.Name": "redis-standalone"}
1.6611527697097921e+09	INFO	controller_redis	Reconciliation Complete, no Changes required.	{"Request.StatefulSet.Namespace": "nprod-blue-test-app", "Request.StatefulSet.Name": "redis-standalone"}
1.6611527697146933e+09	INFO	controller_redis	Redis service get action is successful	{"Request.Service.Namespace": "nprod-blue-test-app", "Request.Service.Name": "redis-standalone-headless"}
1.661152769721344e+09	INFO	controller_redis	Redis service is already in-sync	{"Request.Service.Namespace": "nprod-blue-test-app", "Request.Service.Name": "redis-standalone-headless"}
1.661152769777506e+09	INFO	controller_redis	Redis service get action is successful	{"Request.Service.Namespace": "nprod-blue-test-app", "Request.Service.Name": "redis-standalone"}
1.661152769789846e+09	INFO	controller_redis	Redis service is already in-sync	{"Request.Service.Namespace": "nprod-blue-test-app", "Request.Service.Name": "redis-standalone"}
1.6611527697899318e+09	INFO	controllers.Redis	Will reconcile redis operator in again 10 seconds	{"Request.Namespace": "nprod-blue-test-app", "Request.Name": "redis-standalone"}
1.6611527797910993e+09	INFO	controllers.Redis	Reconciling opstree redis controller	{"Request.Namespace": "nprod-blue-test-app", "Request.Name": "redis-standalone"}
1.6611527797971225e+09	INFO	controller_redis	Redis statefulset get action was successful	{"Request.StatefulSet.Namespace": "nprod-blue-test-app", "Request.StatefulSet.Name": "redis-standalone"}
1.6611527798058143e+09	INFO	controller_redis	Reconciliation Complete, no Changes required.	{"Request.StatefulSet.Namespace": "nprod-blue-test-app", "Request.StatefulSet.Name": "redis-standalone"}
1.6611527798112783e+09	INFO	controller_redis	Redis service get action is successful	{"Request.Service.Namespace": "nprod-blue-test-app", "Request.Service.Name": "redis-standalone-headless"}
1.6611527798135328e+09	INFO	controller_redis	Redis service is already in-sync	{"Request.Service.Namespace": "nprod-blue-test-app", "Request.Service.Name": "redis-standalone-headless"}
1.6611527798208494e+09	INFO	controller_redis	Redis service get action is successful	{"Request.Service.Namespace": "nprod-blue-test-app", "Request.Service.Name": "redis-standalone"}
1.6611527798243272e+09	INFO	controller_redis	Redis service is already in-sync	{"Request.Service.Namespace": "nprod-blue-test-app", "Request.Service.Name": "redis-standalone"}
1.661152779824385e+09	INFO	controllers.Redis	Will reconcile redis operator in again 10 seconds	{"Request.Namespace": "nprod-blue-test-app", "Request.Name": "redis-standalone"}

redis-operator version:
0.11.0
**Does this issue reproduce with the latest release?**
Yes

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:30:46Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.6", GitCommit:"fbf646b339dc52336b55d8ec85c181981b86331a", GitTreeState:"clean", BuildDate:"2020-12-18T12:01:36Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

</pre></details>

**What did you do?**

Create a standalone redis reployment, the statefulset can not be created with this error:

**What did you expect to see?**

The sts should be created successfully.

**What did you see instead?**
create Pod redis-standalone-0 in StatefulSet redis-standalone failed error: Pod "redis-standalone-0" is invalid: [spec.containers[0].livenessProbe: Required value: must specify a handler type, spec.containers[0].readinessProbe: Required value: must specify a handler type]
-- After reading related issue in github, i found out that might related to the pull request https://github.com/OT-CONTAINER-KIT/redis-operator/pull/302 which remove some entries in CRD which stop the operator to add the default handler to the sts.

**Comment by ahiaht** [comment]
create Pod redis-standalone-0 in StatefulSet redis-standalone failed error: Pod "redis-standalone-0" is invalid: [spec.containers[0].livenessProbe: Required value: must specify a handler type, spec.containers[0].readinessProbe: Required value: must specify a handler type] => this is the error message, sorry for the typo in the bug report

**Comment by drewburr** [comment]
Also experiencing this, running Kubernetes v1.21.5. Standalone Redis does not contain `.livenessProbe.exec` and `readinessProbe.exec`, and these are required by the pod definition. The RedisCluster resource does seem to define these values, however.

I tried to define these manually on the Redis CR:

```yaml
apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: Redis
...
spec:
  readinessProbe:
    exec:
      command:
      - bash
      - /usr/bin/healthcheck.sh
    failureThreshold: 5
    initialDelaySeconds: 15
    periodSeconds: 15
    successThreshold: 1
    timeoutSeconds: 5
  livenessProbe:
    exec:
      command:
      - bash
      - /usr/bin/healthcheck.sh
    failureThreshold: 5
    initialDelaySeconds: 15
    periodSeconds: 15
    successThreshold: 1
    timeoutSeconds: 5
```

But I'm running into this error:

`error: error validating "template.yaml": error validating data: [ValidationError(Redis.spec.livenessProbe): unknown field "exec" in in.opstreelabs.redis.redis.v1beta1.Redis.spec.livenessProbe, ValidationError(Redis.spec.readinessProbe): unknown field "exec" in in.opstreelabs.redis.redis.v1beta1.Redis.spec.readinessProbe]; if you choose to ignore these errors, turn validation off with --validate=false`

It seems the Redis CRD does not permit exec being defined, and the operator is not setting the exec value itself, resulting in the inability to deploy a Redis resource.

**Comment by trathborne** [comment]
I encountered this problem too.

It took a bit of work to roll back the operator version, CRDs, and remove the injected probes from the Redis resource.
