### ISSUE TITLE
Adding mounts to redis containers

### ISSUE THREAD

**Issue by gairadzi** [OT-CONTAINER-KIT/redis-operator#321]
Hey,

I would like to add modules to the cluster, I can add the `loadmodule` directive as an `additionalRedisConfig` but it needs to point to the so file on the container and I could not find a way to add any additional ConfigMap mounts to the containers.

Any direction or suggestion will be much appreciated.
Thanks!

**Comment by lvyanru8200** [comment]
the question is whether the problem of module load failing when the container is restarted needs to be solved or must be solved?

**Comment by gairadzi** [comment]
> the question is whether the problem of module load failing when the container is restarted needs to be solved or must be solved?

Sorry, but I don't understand how this question relates to what I was asking.
I provided a specific use-case I have that requires having an additional file on the container (a custom redis module), currently the operator does not support defining additional volumes for the pods it create so my only option is to build my own redis container image (which I would prefer not to do).

Instead I believe (and @lvyanru8200, you might not feel the same way) that the operator should allow for basic k8s modifications to the pod such as additional mounts, init containers, etc'.

**Comment by lvyanru8200** [comment]
I understand what you mean, what I mean is that after your redis module is loaded in, if your redis container is down, does your former module mount command still work

**Comment by lvyanru8200** [comment]
There are two ways of dealing with this.
The first: cr gives you the fields that you can mount your redis module in and let him mount it in to end, just like configmap
The second: mount it like configmap, but leave it to reconcile to load the module automatically, the advantage of this is that you don't need to reload the module after a redis restart
@gairadzi

**Comment by gairadzi** [comment]
I might be missing something @lvyanru8200 but I could not find a way in the custom resource to add additional mounts or config maps.
Can you please provide an example or a link to the crd property in the code you think I can use?
