### ISSUE TITLE
Can open source ` quay. IO/opstree/redis: v6.2.5 ` corresponding ` Dockerfile `, as well as the associated `. Sh ` file?

### ISSUE THREAD

**Issue by leijianzhong001** [OT-CONTAINER-KIT/redis-operator#322]
**Is your feature request related to a problem? Please describe.**
I want to make some changes to the 'quay. IO/opstree/redis: v6.2.5' image, for example I want to change its default persistence configuration. But I don't have a Dockerfile for that image

**Describe the solution you'd like**
I want the 'Dockerfile' file of 'Quay. IO/opstree/redis: v6.2.5' image so that I can make some modifications and then rebuild the image

**What version of redis-operator are you using?**
redis-operator version: 0.11.0

**Comment by iamabhishek-dubey** [comment]
It is already https://github.com/OT-CONTAINER-KIT/redis

**Comment by leijianzhong001** [comment]
> It is already https://github.com/OT-CONTAINER-KIT/redis

ok, i got it , think you.
