### ISSUE TITLE
Misleading IPv6 Info log "Redis is IPv6"

### ISSUE THREAD

**Issue by applike-ss** [OT-CONTAINER-KIT/redis-operator#329]
I found this while checking why one of our redis clusters did not recover properly.
The IP of the Pod may be empty (which was the case on our end, but might not have been what's caused our cluster not to recover).
The IP can be empty if the pod status is being read while the container is still in Pending phase.
Suggested solution would be to wait for the pod to enter Phase "Running" and then read the ip or make a check whether the PodIP field is not empty.

https://github.com/OT-CONTAINER-KIT/redis-operator/blob/ead242fb70cc9b5fc5e09a2c4f26e93c158aacea/k8sutils/redis.go#L37

**Comment by iamabhishek-dubey** [comment]
Agreed, I guess this needs to be fixed.

**Comment by applike-ss** [comment]
now i wish we had logging for it too when it fails to read the ip via net.ParseIP or if it's empty. @iamabhishek-dubey should i open a new issue for this?
