### ISSUE TITLE
Grafana dashboard is showing random data

### ISSUE THREAD

**Issue by armujahid** [OT-CONTAINER-KIT/redis-operator#332]
**What version of redis operator are you using?**

redis-operator version: v0.11.0
**Does this issue reproduce with the latest release?**
Yes

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code></summary><br><pre>
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:44:59Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.11-eks-18ef993", GitCommit:"b9628d6d3867ffd84c704af0befd31c7451cdc37", GitTreeState:"clean", BuildDate:"2022-07-06T18:06:23Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.25) and server (1.22) exceeds the supported minor version skew of +/-1
</pre></details>

**What did you do?**

1. Installed operator using 
```
helm repo add ot-helm https://ot-container-kit.github.io/helm-charts/
helm upgrade -i redis-operator ot-helm/redis-operator -n redis-operator --create-namespace
```
2. Installed redis cluster (with redis exporters) using
```
helm upgrade -i redis-cluster ot-helm/redis-cluster --set redisCluster.clusterSize=3 -n redis-operator

```
Helm default values has redisExporter enabled
```
redisExporter:
  enabled: true
  image: quay.io/opstree/redis-exporter
  tag: "1.0"
  imagePullPolicy: IfNotPresent
  resources: {}

```

3. Installed grafana dashboard using from https://raw.githubusercontent.com/OT-CONTAINER-KIT/redis-operator/master/dashboards/redis-operator-cluster.json

Note that I am not using prometheus operator

**What did you expect to see?**

dashboard should display redis-cluster stats

**What did you see instead?**
Garbage data that changes on refresh but I am sure that it isn't coming from redis cluster since It has 6 pods (3 leader, 3 followers)
But dashboard shows random number of nodes (60+)
![image](https://user-images.githubusercontent.com/3725386/190414679-6d15180b-a98b-458c-81ca-0f25eb134e0b.png)

Any idea what is wrong?

Dashboard keep on displaying garbage data even if I uninstall redis cluster and operator.

**Comment by armujahid** [comment]
Following two annotations were missing from `redis-cluster-leader` and `redis-cluster-follower` services that were exposing redis-exporter.
```
    prometheus.io/scrape: "true"
    prometheus.io/port: "9121"
``` 

1) As per docs these should already exist in both of these services. How to ensure that these annotations are automatically added?
2) I can see both services in service dropdown in grafana dashboard after manually adding these two annotations in both services But again dashboard doesn't seem to show valid data. (Redis nodes count randomly varies between ~30 to ~90)

![image](https://user-images.githubusercontent.com/3725386/190567320-fa98c684-eee4-4fc0-b795-14a72909dcca.png)
![image](https://user-images.githubusercontent.com/3725386/190567712-a882ab2f-e44b-4802-b201-e22755f6ae30.png)

**Comment by armujahid** [comment]
@trathborne How should this dashboard be imported in grafana?
I have tried 2 approaches
1) Using grafana-values

```
   redis-operator-cluster:
      url: https://raw.githubusercontent.com/OT-CONTAINER-KIT/redis-operator/master/dashboards/redis-operator-cluster.json

```
I am getting this error on refreshing dashboard imported using this approach
```
Failed to upgrade legacy queries Datasource ${DS_PROMETHEUS} was not found
```

2) By pasting json in "Import via panel json"  on `/dashboard/import` page

Random data behavior is same for both approaches

**Comment by trathborne** [comment]
@armujahid download that redis-operator-cluster.json, then in Grafana click +→Import and upload that JSON file. Grafana will ask you to pick a Prometheus data source and will configure the dashboard correctly.

If you have multiple Prometheus data sources, then you'll have to make a new datasource variable (e.g. mydatasource) in the dashboard, and replace all datasource values with '${mydatassource}'. I did this by search-and-replace in the JSON view.

**Comment by armujahid** [comment]
I had only one prometheus datasource but it wasn't set to default. I set it to default using `isDefault: true` in `grafana-values.yaml`

```
    datasources:
    - name: Prometheus
      type: prometheus
      version: 1
      url: http://prometheus-server:80
      access: proxy
      isDefault: true
```

After that both of below approaches started to work

1. Using grafana-values.yaml while upgrading helm chart

```
    redis-operator-cluster:
      url: https://raw.githubusercontent.com/OT-CONTAINER-KIT/redis-operator/master/dashboards/redis-operator-cluster.json
      datasource: Prometheus
```

2. Using import dashboard feature by selecting after selecting Prometheus datasource (Note that this wasn't working before although it should work even if Prometheus datasource is not set to default)

![image](https://user-images.githubusercontent.com/3725386/191253204-8a1a2cb1-6ee1-4ce6-be4a-b49ab3001679.png)
![image](https://user-images.githubusercontent.com/3725386/191253317-ac6cb3fb-1736-4d2d-a1c9-3eaa73172a7d.png)
