### ISSUE TITLE
Single Leader and Follower in redis-cluster

### ISSUE THREAD

**Issue by tanujd11** [OT-CONTAINER-KIT/redis-operator#339]
**Is your feature request related to a problem? Please describe.**

For lower environments I want a feature to create single leader and single follower redis cluster as it would be better visibilty and also cost optimisation. This can't be done currently as there is validation for it to be a minimum of 3.

**Describe the solution you'd like**

I would like a way to create single leader and follower cluster.

**Describe alternatives you've considered**

To achieve this we can't directly use the `redis-cli --cluster create` command because of it's limitation of need for 3 leader and followers at the very least. I achieved this in a fork of mine by using `redis-cli CLUSTER ADDSLOTS` command. I would be happy to contribute if this proposal is accepted.

**What version of redis-operator are you using?**

redis-operator version:

**Additional context**

**Comment by tanujd11** [comment]
@iamabhishek-dubey would you care to take a look? This feature is required for us. If it doesn't get merge then we would have to maintain another fork which will be drifted to the latest changes in the operator. Thanks

**Comment by iamabhishek-dubey** [comment]
FIxed
