### ISSUE TITLE
failed to find unique target for patch 

### ISSUE THREAD

**Issue by mathslimin** [OT-CONTAINER-KIT/redis-operator#34]
make deploy
/mnt/data/apps/ot-container-kit-redis-operator/bin/controller-gen "crd:trivialVersions=true,preserveUnknownFields=false" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
cd config/manager && /mnt/data/apps/ot-container-kit-redis-operator/bin/kustomize edit set image controller=localhost:5000/redis-operator:v0.3.0
/mnt/data/apps/ot-container-kit-redis-operator/bin/kustomize build config/default >deploy.yaml
Error: no matches for OriginalId apps_v1_Deployment|system|controller-manager; no matches for CurrentId apps_v1_Deployment|system|controller-manager; failed to find unique target for patch apps_v1_Deployment|controller-manager

**Comment by iamabhishek-dubey** [comment]
I would suggest you go through the documentation for deployment, the command which you are executing it's more like to develop and test CRD.

**Comment by iamabhishek-dubey** [comment]
If you want to dive into the Development of this CRD, please go through this document
https://docs.opstreelabs.in/redis-operator/development
