### ISSUE TITLE
How to pause operator watch?

### ISSUE THREAD

**Issue by rhrytskiv** [OT-CONTAINER-KIT/redis-operator#350]
**Is your feature request related to a problem? Please describe.**
I can't find in documentation how to pause operator from watching specific or all redis resources.

**Describe the solution you'd like**
Pause operator from watching specific or all redis resources

**Describe alternatives you've considered**

**What version of redis-operator are you using?**

redis-operator version: redis-operator-0.11.2

**Additional context**

**Comment by devkmsg** [comment]
What is your usecase for this feature?  #325 may be related depending on your usecase.

**Comment by rhrytskiv** [comment]
@devkmsg I'm using Mayastor as my storage backend, and to update Mayastor it's essential to scale down every statefulset that is using PVs.
If you just scale down statefulset operator will scale it back down. For example rabbitmq operator [has this feature ](https://www.rabbitmq.com/kubernetes/operator/using-operator.html#pause).
I've though worked-around this lack of feature by just scaling down redis operator to 0 before scaling down statefulsets.

**Comment by iamabhishek-dubey** [comment]
It can be used now like this:

```yaml
annotations:
    redis.opstreelabs.in/skip-reconcile: "true"
    rediscluster.opstreelabs.in/skip-reconcile: "true"
```
