### ISSUE TITLE
Wrong resource in clusterrole RBAC

### ISSUE THREAD

**Issue by mms-gianni** [OT-CONTAINER-KIT/redis-operator#351]
**What version of redis operator are you using?**

```shell
# kubectl get csv
NAME                      DISPLAY                           VERSION   REPLACES                  PHASE
kubero-operator.v0.0.67   Kubero                            0.0.67                              Succeeded
redis-operator.v0.11.0    Redis Operator                    0.11.0    redis-operator.v0.9.0     Succeeded
```

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
# kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-19T15:39:43Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.24) exceeds the supported minor version skew of +/-1
</pre></details>

**What did you do?**
Installed via Operator Hub 
```bash
# kubectl create -f https://operatorhub.io/install/stable/redis-operator.yaml
```

**What did you see instead?**
`
W1014 08:52:24.512175       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.0/tools/cache/reflector.go:167: failed to list *v1beta1.Redis: redis.redis.redis.opstreelabs.in is forbidden: User "system:serviceaccount:operators:redis-operator" cannot list resource "redis" in API group "redis.redis.opstreelabs.in" at the cluster scope
E1014 08:52:24.512226       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.0/tools/cache/reflector.go:167: Failed to watch *v1beta1.Redis: failed to list *v1beta1.Redis: redis.redis.redis.opstreelabs.in is forbidden: User "system:serviceaccount:operators:redis-operator" cannot list resource "redis" in API group "redis.redis.opstreelabs.in" at the cluster scope
`

**What seems to be wrong?**
This might be the issue: The clusterrole redis-operator has a double 'ss' in his resource (rediss) 

It was allready mentionend and fixe in this early bug : 
https://github.com/OT-CONTAINER-KIT/redis-operator/issues/32 

It also seems to be fixed here: https://github.com/OT-CONTAINER-KIT/redis-operator/pull/177 
But it cant figure out, why it appears in my installation.

```bash
# kubectl get clusterroles.rbac.authorization.k8s.io redis-operator.v0.11.0-7bc859f74 -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: "2022-10-14T08:40:19Z"
  labels:
    olm.owner: redis-operator.v0.11.0
    olm.owner.kind: ClusterServiceVersion
    olm.owner.namespace: operators
    operators.coreos.com/redis-operator.operators: ""
  name: redis-operator.v0.11.0-7bc859f74
  resourceVersion: "2322679"
  uid: 5f0ac850-f7b3-4f78-9bda-992dd92336cd
rules:
- apiGroups:
  - redis.redis.opstreelabs.in
  resources:
  - rediss <<<<<<<<-------------------------- HERE 
  - redisclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redis.redis.opstreelabs.in
  resources:
  - redis/finalizers
  - rediscluster/finalizers
  verbs:
  - update
- apiGroups:
  - redis.redis.opstreelabs.in
  resources:
  - redis/status
  - rediscluster/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  - pods/exec
  - services
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
```

**Comment by iamabhishek-dubey** [comment]
We need to release a new version of this on operatorhub

**Comment by iamabhishek-dubey** [comment]
This will be fixed in https://github.com/k8s-operatorhub/community-operators/pull/1832

**Comment by nick4fake** [comment]
Happens on 0.14:

rediss.redis.redis.opstreelabs.in
![image](https://github.com/OT-CONTAINER-KIT/redis-operator/assets/1065993/ec5a699e-f9fc-4bb9-b71f-5c456968a03e)

**Comment by nick4fake** [comment]
E0618 14:55:34.842782       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.0/tools/cache/re
flector.go:167: Failed to watch *v1beta1.RedisReplication: failed to list *v1beta1.RedisReplica
tion: redisreplications.redis.redis.opstreelabs.in is forbidden: User "system:serviceaccount:nt
r-infra:redis-operator" cannot list resource "redisreplications" in API group "redis.redis.opst
reelabs.in" at the cluster scope

**Comment by shubham-cmyk** [comment]
Make sure you have upgraded your crd while you have upgraded from v0.13.0 to v0.14.0, helm doesn't upgrade crd on it's own so  you have to upgrade it independently.
