### ISSUE TITLE
Wrong resource in clusterrole RBAC in v0.12.0 

### ISSUE THREAD

**Issue by mms-gianni** [OT-CONTAINER-KIT/redis-operator#352]
Sorry to bother you again. I tried your fix from https://github.com/OT-CONTAINER-KIT/redis-operator/issues/351 in version 0.12.0
The resource `redis` works fine now, but the resource `rediscluster` is now in singular and should be plural `redisclusters`

**What version of redis operator are you using?**

```shell
# kubectl get csv
NAME                      DISPLAY                           VERSION   REPLACES                  PHASE
kubero-operator.v0.0.67   Kubero                            0.0.67                              Succeeded
redis-operator.v0.12.0    Redis Operator                    0.12.0    redis-operator.v0.11.0     Succeeded
```

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
# kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-19T15:39:43Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.24) exceeds the supported minor version skew of +/-1
</pre></details>

**What did you do?**
Installed via Operator Hub 
```bash
# kubectl create -f https://operatorhub.io/install/stable/redis-operator.yaml
```

**What did you see instead?**
`
W1017 09:53:28.116982       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.0/tools/cache/reflector.go:167: failed to list *v1beta1.RedisCluster: redisclusters.redis.redis.opstreelabs.in is forbidden: User "system:serviceaccount:operators:redis-operator" cannot list resource "redisclusters" in API group "redis.redis.opstreelabs.in" at the cluster scope
E1017 09:53:28.117048       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.0/tools/cache/reflector.go:167: Failed to watch *v1beta1.RedisCluster: failed to list *v1beta1.RedisCluster: redisclusters.redis.redis.opstreelabs.in is forbidden: User "system:serviceaccount:operators:redis-operator" cannot list resource "redisclusters" in API group "redis.redis.opstreelabs.in" at the cluster scope
W1017 09:53:30.222973       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.0/tools/cache/reflector.go:167: failed to list *v1beta1.RedisCluster: redisclusters.redis.redis.opstreelabs.in is forbidden: User "system:serviceaccount:operators:redis-operator" cannot list resource "redisclusters" in API group "redis.redis.opstreelabs.in" at the cluster scope
E1017 09:53:30.223068       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.0/tools/cache/reflector.go:167: Failed to watch *v1beta1.RedisCluster: failed to list *v1beta1.RedisCluster: redisclusters.redis.redis.opstreelabs.in is forbidden: User "system:serviceaccount:operators:redis-operator" cannot list resource "redisclusters" in API group "redis.redis.opstreelabs.in" at the cluster scope
`

**What seems to be wrong?**
The resources needs to be plural. Since "redis" ends with an "s" it remains unchanged and for and rediscluster requires a "s" 

- redis
- redisclusters 

```bash
# kubectl get clusterroles.rbac.authorization.k8s.io redis-operator.v0.12.0-5b9545c585 -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: "2022-10-17T09:53:07Z"
  labels:
    olm.owner: redis-operator.v0.12.0
    olm.owner.kind: ClusterServiceVersion
    olm.owner.namespace: operators
    operators.coreos.com/redis-operator.operators: ""
  name: redis-operator.v0.12.0-5b9545c585
  resourceVersion: "2720269"
  uid: 40f6bc0a-8c0b-4c9c-b495-5438fca7d5a1
rules:
- apiGroups:
  - redis.redis.opstreelabs.in
  resources:
  - redis
  - rediscluster <<<<<<<<-------------------------- Missing an 's' for plurals
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redis.redis.opstreelabs.in
  resources:
  - redis/finalizers
  - rediscluster/finalizers
  verbs:
  - update
- apiGroups:
  - redis.redis.opstreelabs.in
  resources:
  - redis/status
  - rediscluster/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  - pods/exec
  - services
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
```

**Comment by iamabhishek-dubey** [comment]
Well, will raise another PR for operator hub with this change.

**Comment by iamabhishek-dubey** [comment]
Will be fixed in https://github.com/k8s-operatorhub/community-operators/pull/1833

**Comment by mms-gianni** [comment]
@iamabhishek-dubey works perfectly now. Thank you!
