### ISSUE TITLE
Redis-cluster helm upgrade/install error

### ISSUE THREAD

**Issue by juvivas-mop** [OT-CONTAINER-KIT/redis-operator#359]
redis-operator version: v0.12.0

```shell
 kubectl logs redis-operator-5bfdc967c8-s5fgk -n redis-operator
I1021 16:14:44.617093       1 request.go:665] Waited for 1.042253131s due to client-side throttling, not priority and fairness, request: GET:https://10.96.0.1:443/apis/node.k8s.io/v1?timeout=32s
{"level":"info","ts":1666368884.720352,"logger":"controller-runtime.metrics","msg":"Metrics server is starting to listen","addr":":8080"}
{"level":"info","ts":1666368884.7206926,"logger":"setup","msg":"starting manager"}
{"level":"info","ts":1666368884.720946,"msg":"Starting server","kind":"health probe","addr":"[::]:8081"}
{"level":"info","ts":1666368884.720945,"msg":"Starting server","path":"/metrics","kind":"metrics","addr":"[::]:8080"}
I1021 16:14:44.721017       1 leaderelection.go:248] attempting to acquire leader lease redis-operator/6cab913b.redis.opstreelabs.in...
I1021 16:15:01.126524       1 leaderelection.go:258] successfully acquired lease redis-operator/6cab913b.redis.opstreelabs.in
{"level":"info","ts":1666368901.126733,"logger":"controller.redis","msg":"Starting EventSource","reconciler group":"redis.redis.opstreelabs.in","reconciler kind":"Redis","source":"kind source: *v1beta1.Redis"}
{"level":"info","ts":1666368901.1267645,"logger":"controller.redis","msg":"Starting Controller","reconciler group":"redis.redis.opstreelabs.in","reconciler kind":"Redis"}
{"level":"info","ts":1666368901.1271617,"logger":"controller.rediscluster","msg":"Starting EventSource","reconciler group":"redis.redis.opstreelabs.in","reconciler kind":"RedisCluster","source":"kind source: *v1beta1.RedisCluster"}
{"level":"info","ts":1666368901.1271832,"logger":"controller.rediscluster","msg":"Starting Controller","reconciler group":"redis.redis.opstreelabs.in","reconciler kind":"RedisCluster"}
{"level":"info","ts":1666368901.227567,"logger":"controller.redis","msg":"Starting workers","reconciler group":"redis.redis.opstreelabs.in","reconciler kind":"Redis","worker count":1}
{"level":"info","ts":1666368901.2276301,"logger":"controller.rediscluster","msg":"Starting workers","reconciler group":"redis.redis.opstreelabs.in","reconciler kind":"RedisCluster","worker count":1}
```

**What operating system and processor architecture are you using (`kubectl version`)?**
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.7", GitCommit:"e6f35974b08862a23e7f4aad8e5d7f7f2de26c15", GitTreeState:"clean", BuildDate:"2022-10-12T10:57:14Z", GoVersion:"go1.18.7", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.7", GitCommit:"e6f35974b08862a23e7f4aad8e5d7f7f2de26c15", GitTreeState:"clean", BuildDate:"2022-10-12T10:50:21Z", GoVersion:"go1.18.7", Compiler:"gc", Platform:"linux/amd64"}

**What did you do?**
- Install chart: `helm repo add ot-helm https://ot-container-kit.github.io/helm-charts/ && helm repo update`
- Deploy operator: `helm upgrade --install redis-operator ot-helm/redis-operator -n redis-operator`
- Deploy redis cluster : `helm upgrade --install redis-cluster ot-helm/redis-cluster --namespace gitlab`

**What did you expect to see?**
Redis Cluster Deployed. The operator work correctly when i deploy a redis standalone 

**What did you see instead?**

```
helm upgrade --install redis-cluster ot-helm/redis-cluster --namespace gitlab-system
Release "redis-cluster" does not exist. Installing it now.
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(RedisCluster.spec): unknown field "clusterVersion" in in.opstreelabs.redis.redis.v1beta1.RedisCluster.spec, ValidationError(RedisCluster.spec): unknown field "persistenceEnabled" in in.opstreelabs.redis.redis.v1beta1.RedisCluster.spec]

```

**Comment by iamabhishek-dubey** [comment]
<img width="1322" alt="image" src="https://user-images.githubusercontent.com/26764731/198371268-b7e449dd-c747-4039-a45d-1b42edda7fc6.png">
Looks like this is because helm because upgrade helm charts don't upgrade the crds. I would suggest removing the chart of the redis operator and installing it again in the system. There is not issue with the operator and operator helm chart, please refer to the above-mentioned screenshot.

**Comment by armujahid** [comment]
I had to manually delete these two CRDs even after removing redis operator and redis cluster charts.
```
k delete crd redis.redis.redis.opstreelabs.in
k delete crd redisclusters.redis.redis.opstreelabs.in 
```
I think this is a bug that CRDs aren't automatically removed after operator removal.
