### ISSUE TITLE
quay.io/opstree/redis:v6.2.5 Can Not Use

### ISSUE THREAD

**Issue by liyongxian** [OT-CONTAINER-KIT/redis-operator#360]

**Comment by iamabhishek-dubey** [comment]
Can you please provide a description of this issue?

**Comment by iamabhishek-dubey** [comment]
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/26764731/198375084-d8a3c26a-9584-42d1-81a3-fb2d9998192a.png">
I tested v6.2.5 and I can still see it's working completely fine.

```shell
helm upgrade --install redis-cluster ot-helm/redis-cluster --namespace gitlab --set redisCluster.clusterVersion=v6 --set redisCluster.tag=v6.2.5
```

**Comment by iamabhishek-dubey** [comment]
You need to update clusterVersion and image only in the spec.

https://github.com/OT-CONTAINER-KIT/redis-operator/blob/master/example/redis_monitoring/clusterd.yaml#L10-L16

Closing this issue because it's not a real bug
