### ISSUE TITLE
upgrade operator error

### ISSUE THREAD

**Issue by szy345** [OT-CONTAINER-KIT/redis-operator#383]
**What version of redis operator are you using?**
Old operator version: v0.11.0
New version: v0.12.0

**What operating system and processor architecture are you using (`kubectl version`)?**
Ubuntu 18.04.3 LTS
Kubernetes:v1.23.6

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:49:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:43:11Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}

</pre></details>

**What did you do?**

I tried several ways to upgrade the operator, but the same error occurred.
Old operator version: v0.11.0
New version: v0.12.0

1、upgrade
<details><summary><code>helm upgrade</code> Output</summary><br><pre>
cd ../redis-operator-0.12.0/charts/redis-operator/
helm upgrade redis-operator . -n dbaredis

 kubectl logs redis-operator-54d5dbf7dd-dhcmm -n dbaredis

{"level":"info","ts":1669287858.5609622,"logger":"controller-runtime.metrics","msg":"Metrics server is starting to listen","addr":":8080"}
{"level":"info","ts":1669287858.5613623,"logger":"setup","msg":"starting manager"}
{"level":"info","ts":1669287858.5616646,"msg":"Starting server","path":"/metrics","kind":"metrics","addr":"[::]:8080"}
{"level":"info","ts":1669287858.5616803,"msg":"Starting server","kind":"health probe","addr":"[::]:8081"}
I1124 11:04:18.561724       1 leaderelection.go:248] attempting to acquire leader lease dbaredis/6cab913b.redis.opstreelabs.in...
I1124 11:04:35.431823       1 leaderelection.go:258] successfully acquired lease dbaredis/6cab913b.redis.opstreelabs.in
{"level":"info","ts":1669287875.4320662,"logger":"controller.redis","msg":"Starting EventSource","reconciler group":"redis.redis.opstreelabs.in","reconciler kind":"Redis","source":"kind source: *v1beta1.Redis"}
{"level":"info","ts":1669287875.4321146,"logger":"controller.redis","msg":"Starting Controller","reconciler group":"redis.redis.opstreelabs.in","reconciler kind":"Redis"}
{"level":"info","ts":1669287875.4320934,"logger":"controller.rediscluster","msg":"Starting EventSource","reconciler group":"redis.redis.opstreelabs.in","reconciler kind":"RedisCluster","source":"kind source: *v1beta1.RedisCluster"}
{"level":"info","ts":1669287875.4321516,"logger":"controller.rediscluster","msg":"Starting Controller","reconciler group":"redis.redis.opstreelabs.in","reconciler kind":"RedisCluster"}
{"level":"info","ts":1669287875.53308,"logger":"controller.rediscluster","msg":"Starting workers","reconciler group":"redis.redis.opstreelabs.in","reconciler kind":"RedisCluster","worker count":1}
{"level":"info","ts":1669287875.5331802,"logger":"controller.redis","msg":"Starting workers","reconciler group":"redis.redis.opstreelabs.in","reconciler kind":"Redis","worker count":1}
{"level":"info","ts":1669287875.5332248,"logger":"controllers.RedisCluster","msg":"Reconciling opstree redis Cluster controller","Request.Namespace":"dbaredis","Request.Name":"guanggaotest"}
{"level":"info","ts":1669287875.533297,"logger":"controllers.Redis","msg":"Reconciling opstree redis controller","Request.Namespace":"dbaredis","Request.Name":"test2"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x140a57e]

</pre></details>

2、apply the crds files, then upgrade
<details><summary><code>apply the crds files,helm upgrade</code> Output</summary><br><pre>
cd ../redis-operator-0.12.0/charts/redis-operator/

kubectl apply -f ./crds/redis-cluster.yaml -n dbaredis
kubectl apply -f ./crds/redis.yaml -n dbaredis

helm upgrade redis-operator . -n dbaredis

the error of the operator is the same as above：
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x140a57e]

</pre></details>

3、uninstall the old operator ,then install new operator
<details><summary><code>uninstall the old operator ,then install new operator</code> Output</summary><br><pre>
helm -n dbaredis delete redis-operator

cd ../redis-operator-0.12.0/charts/redis-operator/
helm install redis-operator . -n dbaredis

the error of the operator is the same as above：
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x140a57e]

</pre></details>

Now, what can I do ?

**Comment by shubham-cmyk** [comment]
Can you elaborate more.

**Comment by szy345** [comment]
The following command is executed successfully.
`helm upgrade <release-name> <chart-name>`

But the operator Always reporting error and restarting.

the error content is as I described above.

**Comment by shubham-cmyk** [comment]
This could happen if the Redis Cluster resource has some issue.

**Comment by iamabhishek-dubey** [comment]
There are some breaking changes in version `>=0.12.0`. Please share your cluster deployment manifest.

**Comment by revathyr13** [comment]
Hello @iamabhishek-dubey 

I am also facing the same issue

I am trying the operator upgrade from version 0.10.0 to 0.12.0 . [chart from 0.10.1 to 0.12.0]

After upgrade I am getting following error in redis operator pods


NAME                             READY   STATUS             RESTARTS   AGE
redis-operator-bc478dbbc-jw7xq   0/1     CrashLoopBackOff   4          4m57s

{"level":"info","ts":1670312209.2248487,"logger":"controllers.RedisCluster","msg":"Reconciling opstree redis Cluster controller","Request.Namespace":"redis-cluster-itd","Request.Name":"redis-cluster-itd"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x140a57e]

goroutine 540 [running]:
redis-operator/k8sutils.generateRedisClusterContainerParams(0xc0008d8240, 0xc00049cf00, 0xc00049cf18)
        /workspace/k8sutils/redis-cluster.go:86 +0x1de
redis-operator/k8sutils.RedisClusterSTS.CreateRedisClusterSetup({{0x17272db, 0x6}, 0xc000895510, 0x0, 0xc00049cf00, 0xc00049cf18}, 0xc0008d8240)
        /workspace/k8sutils/redis-cluster.go:158 +0x3fa
redis-operator/k8sutils.CreateRedisLeader(0xc0008d8240)
        /workspace/k8sutils/redis-cluster.go:109 +0xa9
redis-operator/controllers.(*RedisClusterReconciler).Reconcile(0xc0005bd080, {0xc0008c9920, 0x155e1a0}, {{{0xc000623398, 0x1668f60}, {0xc000623380, 0x30}}})
        /workspace/controllers/rediscluster_controller.go:68 +0x2c5
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc0000c2420, {0x1942e58, 0xc0008c9920}, {{{0xc000623398, 0x1668f60}, {0xc000623380, 0x413a94}}})

I have also tried deploying the new crd as well.  But still same error.

The redis cluster deployment I had in older version [operator version 0.10.0] is  as follows 

apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: RedisCluster
metadata:
  name: redis-cluster-itd
spec:
  clusterSize: 3
  kubernetesConfig:
    image: 'quay.io/opstree/redis:v6.2.5'
    imagePullPolicy: IfNotPresent
    redisSecret:
      key: password
      name: redis-auth
    resources:
      requests:
        cpu: 100m
        memory: 1Gi
      limits:
        cpu: 200m
        memory: 1Gi
#Redisexporter
  redisExporter:
    enabled: true
    image: 'quay.io/opstree/redis-exporter:1.0'
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 128Mi
  redisLeader:
    redisConfig:
      additionalRedisConfig: redis-external-config
  redisFollower:
    redisConfig:
      additionalRedisConfig: redis-external-config

  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi


May I know what changes are required to make it work on 0.12.0 operator version. Also we are using the cluster  in production so does any changes cause data loss ?

**Comment by revathyr13** [comment]
Hello Team,

Any updates on this ?

**Comment by revathyr13** [comment]
Hello @iamabhishek-dubey 

I am using helm chart for operator installation.  May I know when the changes will be added in helm chart ?
