### ISSUE TITLE
When I created a redis-cluster, an error was displayed during verification, please help to check if there is a problem with the configuration

### ISSUE THREAD

**Issue by chenghongxi** [OT-CONTAINER-KIT/redis-operator#387]
yaml：
`---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: redis-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
spec:
  capacity:
    storage: 6Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: redis-storage
  local:
    path: /mnt
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - pixiu01 # 这里根据官网例子，要设置亲和性，改成节点名
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-follower
spec:
  capacity:
    storage: 6Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: redis-storage
  local:
    path: /mnt
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - pixiu01 # 这里根据官网例子，要设置亲和性，改成节点名
---
apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: RedisCluster
metadata:
  name: redis-cluster
spec:
  clusterSize: 1
  clusterVersion: v7
  securityContext:
    runAsUser: 1000
    fsGroup: 1000
  persistenceEnabled: true
  kubernetesConfig:
    image: 'quay.io/opstree/redis:v7.0.5'
    imagePullPolicy: IfNotPresent
  redisExporter:
    enabled: true
    image: 'quay.io/opstree/redis-exporter:v1.44.0'
    imagePullPolicy: IfNotPresent
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: redis-storage
        resources:
          requests:
            storage: 1Gi`

使用上边的yaml 创建了一个数量为1的redis-cluster，
kubectl get pods显示：
[root@VM-4-3-centos ~]# kubectl get po
NAME                       READY   STATUS    RESTARTS   AGE
redis-cluster-follower-0   2/2     Running   0          24m
redis-cluster-leader-0     2/2     Running   0          24m

但是我测试集群时出现问题，
[root@VM-4-3-centos ~]# kubectl exec -it redis-cluster-leader-0  -- redis-cli -c set tony stark
Defaulted container "redis-cluster-leader" out of: redis-cluster-leader, redis-exporter
(error) CLUSTERDOWN Hash slot not served

[root@VM-4-3-centos ~]# kubectl exec -it redis-cluster-leader-0  -- redis-cli cluster nodes
Defaulted container "redis-cluster-leader" out of: redis-cluster-leader, redis-exporter
06ccfd372b6b28929ebbbdd9abd300a910515ce3 :6379@16379 myself,master - 0 0 0 connected

不能set值，和查看追随者。

**Comment by shubham-cmyk** [comment]
Everything seems to be okay! 
Can you share more details.  
@chenghongxi 

![Screenshot from 2022-11-30 03-01-20](https://user-images.githubusercontent.com/69793468/204652226-8712c751-b39a-4942-b9c7-e91ca5fffa08.png)

**Comment by chenghongxi** [comment]
Did you create the cluster with my yaml above?

**Comment by chenghongxi** [comment]
![1](https://user-images.githubusercontent.com/48846160/204678900-c2dceafe-23c7-40df-9118-52d66ce6f0cb.png)

**Comment by chenghongxi** [comment]
yaml file
>
 ---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: redis-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
spec:
  capacity:
    storage: 6Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: redis-storage
  local:
    path: /mnt
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - pixiu01 # 这里根据官网例子，要设置亲和性，改成节点名
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv1
spec:
  capacity:
    storage: 6Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: redis-storage
  local:
    path: /mnt
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - pixiu01 # 这里根据官网例子，要设置亲和性，改成节点名
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv2
spec:
  capacity:
    storage: 6Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: redis-storage
  local:
    path: /mnt
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - pixiu01 # 这里根据官网例子，要设置亲和性，改成节点名


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-follower
spec:
  capacity:
    storage: 6Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: redis-storage
  local:
    path: /mnt
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - pixiu01 # 这里根据官网例子，要设置亲和性，改成节点名
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-follower1
spec:
  capacity:
    storage: 6Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: redis-storage
  local:
    path: /mnt
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - pixiu01 # 这里根据官网例子，要设置亲和性，改成节点名
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-follower2
spec:
  capacity:
    storage: 6Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: redis-storage
  local:
    path: /mnt
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - pixiu01 # 这里根据官网例子，要设置亲和性，改成节点名


---
apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: RedisCluster
metadata:
  name: redis-cluster
spec:
  clusterSize: 3
  clusterVersion: v7
  securityContext:
    runAsUser: 1000
    fsGroup: 1000
  persistenceEnabled: true
  kubernetesConfig:
    image: 'quay.io/opstree/redis:v7.0.5'
    imagePullPolicy: IfNotPresent
    redisSecret:
      name: redis-secret
      key: password
  redisExporter:
    enabled: true
    image: 'quay.io/opstree/redis-exporter:v1.44.0'
    imagePullPolicy: IfNotPresent
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: redis-storage
        resources:
          requests:
            storage: 1Gi

**Comment by iamabhishek-dubey** [comment]
Please share the operator logs.

**Comment by chenghongxi** [comment]
![redis-operators-log](https://user-images.githubusercontent.com/48846160/204734805-a83b002d-f95a-49a2-a50c-277bd00139df.png)

**Comment by chenghongxi** [comment]
The above figure shows the log of redis-operator-547d8c9d55-fb6wl

![3](https://user-images.githubusercontent.com/48846160/204735554-9499425c-cb69-498e-b9d7-40f2f27dcf0a.png)

**Comment by chenghongxi** [comment]
请帮忙看一下  谢谢

**Comment by shubham-cmyk** [comment]
Please clean your PV and start the Cluster again.

**Comment by chenghongxi** [comment]
![4](https://user-images.githubusercontent.com/48846160/204737207-371afdad-cff9-404d-ac31-79c0284c745b.png)

**Comment by chenghongxi** [comment]
delete pv？

**Comment by chenghongxi** [comment]
The pv has been removed and the following yaml files have been re-applied with the pod status pending

![6](https://user-images.githubusercontent.com/48846160/204738498-d49399af-c291-463f-8b23-11faaecf7062.png)

![7](https://user-images.githubusercontent.com/48846160/204738871-9cd1d736-2d50-4fc3-ab73-66228fb884d9.png)

![5](https://user-images.githubusercontent.com/48846160/204738179-ce60257e-753a-4982-b4ee-e1e53baaf2cd.png)

**Comment by chenghongxi** [comment]
@shubham-cmyk

**Comment by shubham-cmyk** [comment]
@chenghongxi Is it solved ?

**Comment by chenghongxi** [comment]
Worked it out
