### ISSUE TITLE
Adding tests for the operator 

### ISSUE THREAD

**Issue by m-yosefpor** [OT-CONTAINER-KIT/redis-operator#399]
**Is your feature request related to a problem? Please describe.**

There are new kind of bugs which are introduced into new version releases, which can be prevented and figured out before code release. For example https://github.com/OT-CONTAINER-KIT/redis-operator/issues/394 panic issue which happens when there is not a `storage` section in `redis` manifest (for redis with persistent disabled). Although https://github.com/OT-CONTAINER-KIT/redis-operator/pull/395 fixed the issue, these kind of bugs might be reintroduced again in future releases.
**Describe the solution you'd like**

Adding tests for the operator and having a pipeline which is run in github actions and making sure the pipeline is passed for each release. Tests can be completed overtime, and encompass most of the operator logic, and can prevent many kind of issues (panics, logical issues, etc)

**Describe alternatives you've considered**

**What version of redis-operator are you using?**

redis-operator version:  0.13.0

**Additional context**

I'll send a few PRs to add some tests and add github action pipelines for testing the operator

**Comment by iamabhishek-dubey** [comment]
@m-yosefpor have you started working on writing e2e test cases?

**Comment by m-yosefpor** [comment]
> @m-yosefpor have you started working on writing e2e test cases?

Not yet. I have a cramped work schedule these days. I have plans to start it a few weeks. Feel free to take over this if you can contribute sooner.
