### ISSUE TITLE
Basic HA scenarios. 

### ISSUE THREAD

**Issue by vineelyalamarthy** [OT-CONTAINER-KIT/redis-operator#405]
I used an example provided and tried to set up Redis Cluster on a three node Kubernetes cluster. 

https://github.com/OT-CONTAINER-KIT/redis-operator/blob/master/example/affinity/clusterd.yaml

First of all, I expected masters and replicas are created on different nodes to provide HA. That didn't seem to work. 

And secondly, I tried deleting a node in Kubernetes, hoping that slots will be rebalanced. That didn't happen either. 

Is the example CR I used incorrect or this operator lacks basic HA functionalities.   Please help.

**Comment by iamabhishek-dubey** [comment]
@shubham-cmyk can you please test the example manifest and fix this issue if needed

**Comment by shubham-cmyk** [comment]
Currently, Lable on leaders are: 
```
Labels:           app=redis-cluster-leader
                  controller-revision-hash=redis-cluster-leader-7b6768d778
                  redis_setup_type=cluster
                  role=leader
```
and on followers are : 
```
Labels:           app=redis-cluster-follower
                  controller-revision-hash=redis-cluster-follower-bdfc6bdd7
                  redis_setup_type=cluster
                  role=follower

```
I think scheduling the leader and follower pods we need to add a different label on the pods.

**Comment by shubham-cmyk** [comment]
#407 This could solve 
Pods are scheduled on different nodes. 
![Screenshot from 2023-01-08 06-02-12](https://user-images.githubusercontent.com/69793468/211175306-5e25a2e2-567d-4375-9d63-1ae775d7e42e.png)

**Comment by shubham-cmyk** [comment]
The second issue about rebalancing is not done because downscaling the cluster at runtime doesn't include the Redis slots balancing I would add it to the code. Thanks, @vineelyalamarthy 

![Screenshot from 2023-01-09 15-53-06](https://user-images.githubusercontent.com/69793468/211286759-8ca9b0f9-4946-40f0-8ead-f4e995b15bb3.png)
