### ISSUE TITLE
Separate cluster configuration files and persistence files in different directories

### ISSUE THREAD

**Issue by obitolyz** [OT-CONTAINER-KIT/redis-operator#409]
redis-operator version: 0.13.0
I deploy redis cluster in k3s, if i don't turn on persistence(PersistenceEnable env is false, it cannot create `/data` dir).
When the pod is deleted by k3s for some reason, it will be restarted with different node id(it cannot join the cluster)

I think it's reasonable to separate cluster configuration files and persistence files  in different directories

**Comment by shubham-cmyk** [comment]
_When the pod is deleted by k3s for some reason, it will be restarted with a different node id(it cannot join the cluster)_

While Running in the persistence mode if master node is down it becomes slave and the slave becomes the master and they do have the same node id.

The node fd63f0988c72ca1efe05ff5587941e921f8bfcbf failed and started as slave with the same node id.

![Screenshot from 2023-01-19 02-46-47](https://user-images.githubusercontent.com/69793468/213296583-58d530d5-3a7c-4c79-8717-7e7baabc627a.png)

**Comment by shubham-cmyk** [comment]
However, the other condition seems to be true creating the redis-cluster while turning off the persistence pods are failing. Need to inspect this one

redis cluster logs : 
![Screenshot from 2023-01-19 02-49-55](https://user-images.githubusercontent.com/69793468/213298048-82088e7a-3906-4c99-9b50-4c3cb141ae86.png)

pods failed : 
![Screenshot from 2023-01-19 02-54-50](https://user-images.githubusercontent.com/69793468/213298217-2ee7fad8-137e-43af-af5d-eacc4ee60506.png)

**Comment by obitolyz** [comment]
> _When the pod is deleted by k3s for some reason, it will be restarted with a different node id(it cannot join the cluster)_
> 
> While Running in the persistence mode if master node is down it becomes slave and the slave becomes the master and they do have the same node id.
> 
> The node fd63f0988c72ca1efe05ff5587941e921f8bfcbf failed and started as slave with the same node id.
> 
> ![Screenshot from 2023-01-19 02-46-47](https://user-images.githubusercontent.com/69793468/213296583-58d530d5-3a7c-4c79-8717-7e7baabc627a.png)

Yep, while running in the persistence mode, it works. But not in the persistence mode, it failed pod restarts with different node id.
