### ISSUE TITLE
Using NFS to persist my redis standalone instance

### ISSUE THREAD

**Issue by johnlongo** [OT-CONTAINER-KIT/redis-operator#41]
Hi,
Running in an OKD 4.7 cluster and I'm using NFS to persist my redis standalone instance, but when the instance comes up it's not able to access the PVC directory.
Right now I have the NFS directory permissions set to nobody:nobody 777.
Please advise

mkdir: can't create directory '/opt/redis': Permission denied
/usr/bin/entrypoint.sh: line 21: /etc/redis/redis.conf: Permission denied
/usr/bin/entrypoint.sh: line 32: /etc/redis/redis.conf: Permission denied
sed: /data/nodes.conf: No such file or directory
/usr/bin/entrypoint.sh: line 52: /etc/redis/redis.conf: Permission denied
Starting redis service in cluster mode.....
11:C 28 Feb 2021 19:39:04.171 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
11:C 28 Feb 2021 19:39:04.171 # Redis version=6.0.9, bits=64, commit=00000000, modified=0, pid=11, just started
11:C 28 Feb 2021 19:39:04.171 # Configuration loaded
11:M 28 Feb 2021 19:39:04.175 * Running mode=standalone, port=6379.
11:M 28 Feb 2021 19:39:04.175 # Server initialized
11:M 28 Feb 2021 19:39:04.177 * Ready to accept connections

**Comment by iamabhishek-dubey** [comment]
You can have an `initContainer` that can change the permission for the directories.

**Comment by iamabhishek-dubey** [comment]
Closing this issue, please reopen if problem persists
