### ISSUE TITLE
Cannot use headless - address wrong? .svc and  .svc.cluster.local 

### ISSUE THREAD

**Issue by voarsh2** [OT-CONTAINER-KIT/redis-operator#415]
**What version of redis operator are you using?**

```shell
```

redis-operator version: v0.13.0

**Does this issue reproduce with the latest release?**
Yes

**What operating system and processor architecture are you using (`kubectl version`)?**
Linux Ubuntu 20 LTS
RKE1

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.8", GitCommit:"4a3b558c52eb6995b3c5c1db5e54111bd0645a64", GitTreeState:"clean", BuildDate:"2021-12-15T14:52:11Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.14", GitCommit:"3321ffc07d2f046afdf613796f9032f4460de093", GitTreeState:"clean", BuildDate:"2022-11-09T13:32:47Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}

</pre></details>

```

```

**What did you do?**
Create a Cluster after installing the operator.

**What did you expect to see?**
Expect to see the command complete. I believe my RKE 1 cluster uses this type of URL: posthog-posthog-kafka-0.posthog-posthog-kafka-headless.posthog-system.svc.cluster.local:9092
Redis Operator is using .svc (.svc.cluster.local should resolve)......

**What did you see instead?**

```

{"level":"error","ts":1674651338.2002966,"logger":"controller_redis","msg":"Could not execute command","Request.RedisManager.Namespace":"posthog-demo","Request.RedisManager.Name":"redis-cluster","Command":["redis-cli","--cluster","create","redis-cluster-leader-0.redis-cluster-leader-headless.posthog-demo.svc:6379","redis-cluster-leader-1.redis-cluster-leader-headless.posthog-demo.svc:6379","redis-cluster-leader-2.redis-cluster-leader-headless.posthog-demo.svc:6379","--cluster-yes"],"Output":">>> Performing hash slots allocation on 3 nodes...\nMaster[0] -> Slots 0 - 5460\nMaster[1] -> Slots 5461 - 10922\nMaster[2] -> Slots 10923 - 16383\nM: b1349e38735deb6c7d45668d31aa4e082d2260b1 redis-cluster-leader-0.redis-cluster-leader-headless.posthog-demo.svc:6379\n slots:[0-5460] (5461 slots) master\nM: 9b1feb6eb07115e8fb46b1e5188fd60d05926342 redis-cluster-leader-1.redis-cluster-leader-headless.posthog-demo.svc:6379\n slots:[5461-10922] (5462 slots) master\nM: f98a8b086bc1dfd48a61ecaba6322876a61d6857 redis-cluster-leader-2.redis-cluster-leader-headless.posthog-demo.svc:6379\n slots:[10923-16383] (5461 slots) master\n>>> Nodes configuration updated\n>>> Assign a different config epoch to each node\n>>> Sending CLUSTER MEET messages to join the cluster\nNode redis-cluster-leader-1.redis-cluster-leader-headless.posthog-demo.svc:6379 replied with error:\nERR Invalid node address specified: redis-cluster-leader-0.redis-cluster-leader-headless.posthog-demo.svc:6379\n","Error":"","error":"command terminated with exit code 1","stacktrace":"redis-operator/k8sutils.ExecuteRedisClusterCommand\n\t/workspace/k8sutils/redis.go:116\nredis-operator/controllers.(*RedisClusterReconciler).Reconcile\n\t/workspace/controllers/rediscluster_controller.go:130\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcil
--
  | eHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227"}
```
```

Didn't have this problem in v0.8.0

**Comment by voarsh2** [comment]
I only got it working by installing:

redis-operator:0.9.0

redis-cluster:0.11.0

**Comment by iamabhishek-dubey** [comment]
What's the version of redis you are using 6 or 7?

**Comment by voarsh2** [comment]
> What's the version of redis you are using 6 or 7?

I was required to use Redis 6

**Comment by iamabhishek-dubey** [comment]
Change this to v6 and it will work.

https://github.com/OT-CONTAINER-KIT/redis-operator/blob/master/example/node-selector/clusterd.yaml#L8

**Comment by iamabhishek-dubey** [comment]
There is a major change for redis 7 and 6 formation, that’s why we had to keep this as variable.
