### ISSUE TITLE
Recovering a redis cluster

### ISSUE THREAD

**Issue by lehy786** [OT-CONTAINER-KIT/redis-operator#42]
When a redis cluster loses contact with more than half of its nodes either because of failed nodes or network split, the cluster stops responding to client connections. When this happens, you must recover the cluster to restore the connections.

And what would this happen in kubernetes, which nodes are managed with redis-operator? I mean, you may need a restart of all redis nodes.

thanks!

**Comment by iamabhishek-dubey** [comment]
Yes, in this case, you may have to restart the nodes but since we are keeping `nodes.conf` in the persistent volume, also, the redis-operator can manage the failover in case of redis connection failure.
