### ISSUE TITLE
ERR Invalid node address specified

### ISSUE THREAD

**Issue by jiuker** [OT-CONTAINER-KIT/redis-operator#428]
{"level":"error","ts":1676432901.5208611,"logger":"controller_redis","msg":"Could not execute command","Request.RedisManager.Namespace":"mcamel-system","Request.RedisManager.Name":"test-redis-cluster","Command":["redis-cli","--cluster","create","test-redis-cluster-leader-0.test-redis-cluster-leader-headless.mcamel-system.svc:6379","test-redis-cluster-leader-1.test-redis-cluster-leader-headless.mcamel-system.svc:6379","test-redis-cluster-leader-2.test-redis-cluster-leader-headless.mcamel-system.svc:6379","--cluster-yes","-a","Aa123456"],"Output":">>> Performing hash slots allocation on 3 nodes...\nMaster[0] -> Slots 0 - 5460\nMaster[1] -> Slots 5461 - 10922\nMaster[2] -> Slots 10923 - 16383\nM: 7f6129c9d35c210ad6bbc09f5f8e2dcbf9401528 test-redis-cluster-leader-0.test-redis-cluster-leader-headless.mcamel-system.svc:6379\n   slots:[0-5460] (5461 slots) master\nM: b2502375e5155634e23b82fcde79e5758b47344f test-redis-cluster-leader-1.test-redis-cluster-leader-headless.mcamel-system.svc:6379\n   slots:[5461-10922] (5462 slots) master\nM: fb390f8735a9cea32a48f44e2c43c5702238097e test-redis-cluster-leader-2.test-redis-cluster-leader-headless.mcamel-system.svc:6379\n   slots:[10923-16383] (5461 slots) master\n>>> Nodes configuration updated\n>>> Assign a different config epoch to each node\n>>> Sending CLUSTER MEET messages to join the cluster\nNode test-redis-cluster-leader-1.test-redis-cluster-leader-headless.mcamel-system.svc:6379 replied with error:\nERR Invalid node address specified: test-redis-cluster-leader-0.test-redis-cluster-leader-headless.mcamel-system.svc:6379\n","Error":"Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.\n","error":"command terminated with exit code 1","stacktrace":"redis-operator/k8sutils.ExecuteRedisClusterCommand\n\t/build/redis-operator-master/k8sutils/redis.go:116\nredis-operator/controllers.(*RedisClusterReconciler).Reconcile\n\t/build/redis-operator-master/controllers/rediscluster_controller.go:130\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/build/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/build/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/build/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/build/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227"}

**What version of redis operator are you using?**

```shell
kubectl logs <_redis-operator_pod_name> -n <namespace>
```

redis-operator version:

v0.14.0

**Does this issue reproduce with the latest release?**

yes

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

</pre></details>

**What did you do?**

**What did you expect to see?**

create a redis-cluster

**What did you see instead?**
Cluster is not ready.`set a b` output:
```shell
127.0.0.1:6379> set a b
(error) CLUSTERDOWN Hash slot not served
```

**Comment by deepak-gc** [comment]
Hi @jiuker I also get the same below error and both the leaders and followers role is master, were you able to resolve it?

```
Invalid node address specified: redis-cluster-leader-0.redis-cluster-leader-headless.redis-cluster.svc:6379
```

**Comment by deepak-gc** [comment]
Hi @jiuker were you able to find any solution for the issue?

**Comment by jiuker** [comment]
> Hi @jiuker were you able to find any solution for the issue?

May be config is empty.Or password is no good for Redis.

**Comment by deepak-gc** [comment]
I was using different clusterVersion `v7` and imageversion `quay.io/opstree/redis:v6.2.5`, changing clusterVersion to `v6` fixed the issue. Thanks for the reply. 

https://github.com/OT-CONTAINER-KIT/redis-operator/issues/476
