### ISSUE TITLE
plz update the helm chart to the newest version

### ISSUE THREAD

**Issue by CrossainQi** [OT-CONTAINER-KIT/redis-operator#431]
The version of redis-operator in helm is 13.0.1 now and I got "Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(RedisCluster.spec): unknown field "pdb" in in.opstreelabs.redis.redis.v1beta1.RedisCluster.spec" while trying to deploy a redis cluster via helm, has it fixed in version 14.0.0? if so, please update the helm charts, thank u.

**Comment by shubham-cmyk** [comment]
@CrossainQi Sorry for that It would be done soon

**Comment by CrossainQi** [comment]
> @CrossainQi Sorry for that It would be done soon

gj, thanks!
