### ISSUE TITLE
Sentinel's Service Ports association is incorrect

### ISSUE THREAD

**Issue by muicoder** [OT-CONTAINER-KIT/redis-operator#435]
**What version of redis operator are you using?**

```shell
# kubectl get svc sentinel-sentinel -o template='{{.spec.ports}}'
[map[name:redis-client port:6379 protocol:TCP targetPort:6379] map[name:redis-exporter port:9121 protocol:TCP targetPort:9121]]
```

redis-operator version: v0.14.0

**Does this issue reproduce with the latest release?**

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

</pre></details>

**What did you do?**

**What did you expect to see?**

**What did you see instead?**

**Comment by shubham-cmyk** [comment]
https://github.com/OT-CONTAINER-KIT/redis-operator/pull/440

**Comment by muicoder** [comment]
> #440

should be #442

**Comment by shubham-cmyk** [comment]
right
