### ISSUE TITLE
Add chart for AIO(standalone cluster replication sentinel) with Redis images for hub.docker.com

### ISSUE THREAD

**Issue by muicoder** [OT-CONTAINER-KIT/redis-operator#437]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**What version of redis-operator are you using?**

redis-operator version:

**Additional context**

https://github.com/muicoder/redis-operator/tree/action/chart

**Comment by shubham-cmyk** [comment]
You can find the helm charts here : https://github.com/OT-CONTAINER-KIT/helm-charts/tree/main/charts
