### ISSUE TITLE
Feature: Add RedisExporter for sentinel

### ISSUE THREAD

**Issue by muicoder** [OT-CONTAINER-KIT/redis-operator#441]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**What version of redis-operator are you using?**

redis-operator version: v0.14.0

**Additional context**

#440

**Comment by shubham-cmyk** [comment]
https://github.com/OT-CONTAINER-KIT/redis-operator/pull/440 
Merged

**Comment by genofire** [comment]
RedisSentinel Exporter does not work:
```
Couldn't connect to redis instance (redi
s://localhost:6379)
```


PS: Health.sh use port 26379

**Comment by muicoder** [comment]
> RedisSentinel Exporter does not work:
> 
> ```
> Couldn't connect to redis instance (redis://localhost:6379)
> ```
> 
> PS: `/usr/bin/healthcheck.sh` use `redis-cli -h $(hostname) -p 26379 ping` another port

#444
