### ISSUE TITLE
Split image to registry,repository,tag

### ISSUE THREAD

**Issue by genofire** [OT-CONTAINER-KIT/redis-operator#446]
**Is your feature request related to a problem? Please describe.**
We like to use your internal cacheing of images without editing the tag/version based on the operator.

**Describe the solution you'd like**
https://github.com/OT-CONTAINER-KIT/redis-operator/blob/7cf390e1c8a0dad05a076e5fb41eb61fced84593/api/v1beta1/common_types.go#L25-L26

Split this Image to:
  - registry
  - repository
  - tag

so an overwrite of `registry` has no effect on the `tag`.

**What version of redis-operator are you using?**

redis-operator version: v0.14.0

**Comment by shubham-cmyk** [comment]
@genofire  This feature is already incorporated while installing redis by helm; 
link here:-  https://github.com/OT-CONTAINER-KIT/helm-charts

**Comment by genofire** [comment]
https://github.com/OT-CONTAINER-KIT/helm-charts/pull/75
