### ISSUE TITLE
When using TLS, the operator cannot reconcile because TLS does not sign the pod name

### ISSUE THREAD

**Issue by muicoder** [OT-CONTAINER-KIT/redis-operator#447]
**What version of redis operator are you using?**

```shell
kubectl logs <_redis-operator_pod_name> -n <namespace>
```
redis(replication) logs:
---
`redis error:0A000126:SSL routines::unexpected eof while reading`

operator logs:
---
`{"level":"error","ts":1677121497.5900624,"logger":"controller_redis","msg":"Failed to Get the role Info of the","Request.RedisManager.Namespace":"redis","Request.RedisManager.Name":"replication","redis pod":"replication-1","error":"x509: certificate is valid for replication, replication.redis, not replication-1","stacktrace":"redis-operator/k8sutils.GetRedisNodesByRole\n\t/workspace/k8sutils/redis.go:464\nredis-operator/controllers.(*RedisReplicationReconciler).Reconcile\n\t/workspace/controllers/redisreplication_controller.go:81\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227"}`

redis-operator version: v0.14.0

**Does this issue reproduce with the latest release?**

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

</pre></details>

**What did you do?**

**What did you expect to see?**

**What did you see instead?**

**Comment by egorksv** [comment]
This is blocking issue, any resolutions?

**Comment by drivebyer** [comment]
does it reproducable on the latest code?

**Comment by egorksv** [comment]
@drivebyer yes, on master as well, sent the PR to fix it
