### ISSUE TITLE
Seeing errors in okd (4.7.0-0.okd-2021-03-28-152009) Comunity Redis Operator 0.4.0

### ISSUE THREAD

**Issue by johnlongo** [OT-CONTAINER-KIT/redis-operator#45]
It continually throws errors and restarts see attached pics and text
quay.io/opstree/redis-operator:v0.4.0

[redis-operator-log-error.txt](https://github.com/OT-CONTAINER-KIT/redis-operator/files/6296062/redis-operator-log-error.txt)

<img width="886" alt="2021-04-12_7-02-03" src="https://user-images.githubusercontent.com/23619505/114385155-a35d5a00-9b5d-11eb-8223-93d4639f5bc0.png">

<img width="902" alt="2021-04-12_7-04-02" src="https://user-images.githubusercontent.com/23619505/114385162-a5271d80-9b5d-11eb-91af-75bafca9ab02.png">

<img width="888" alt="2021-04-12_7-15-58" src="https://user-images.githubusercontent.com/23619505/114386336-16b39b80-9b5f-11eb-894f-0130960473b7.png">

**Comment by iamabhishek-dubey** [comment]
What's the replica count you have kept?

**Comment by johnlongo** [comment]
1

**Comment by iamabhishek-dubey** [comment]
Redis cluster cannot get created in less than 3 nodes, either keep the mode to standalone or keep the replicas 3 with cluster mode. I will add a validation as well :)

**Comment by johnlongo** [comment]
Made the change, but still seeing errors in the logs see attached

apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: Redis
metadata:
  name: redis
  namespace: redis
spec:
  size: 3
  master:
    redisConfig: {}
    service:
      type: ClusterIP
  mode: cluster
  global:
    image: 'quay.io/opstree/redis:v6.2'
    imagePullPolicy: IfNotPresent
    password: Opstree@1234
    resources:
      limits:
        cpu: 10000m
        memory: 12800Mi
      requests:
        cpu: 1000m
        memory: 1280Mi
  service:
    type: ClusterIP
  slave:
    redisConfig: {}
    service:
      type: ClusterIP
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: lv-file-system-sc
  redisExporter:
    enabled: true
    image: 'quay.io/opstree/redis-exporter:1.0'
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 10000m
        memory: 12800Mi
      requests:
        cpu: 1000m
        memory: 1280Mi
  redisConfig: {}


<img width="882" alt="2021-04-12_11-46-01" src="https://user-images.githubusercontent.com/23619505/114423231-fac2f080-9b84-11eb-84a1-2b7a040e9dd6.png">


[log.txt](https://github.com/OT-CONTAINER-KIT/redis-operator/files/6298034/log.txt)

**Comment by iamabhishek-dubey** [comment]
Can you try deleting and recreating the cluster again?

**Comment by iamabhishek-dubey** [comment]
Closing this issue, please re-open if you again see the same issue
