### ISSUE TITLE
Redis-operator. Containers crash with persistenceEnabled=false

### ISSUE THREAD

**Issue by vkanindriver** [OT-CONTAINER-KIT/redis-operator#450]
**What version of redis operator are you using?**
quay.io/opstree/redis-operator:v0.14.0

redis-operator logs:
[redis-operator.log](https://github.com/OT-CONTAINER-KIT/redis-operator/files/10824708/redis-operator.log)

**Does this issue reproduce with the latest release?**
yes

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What did you do?**
helm repo add ot-helm https://ot-container-kit.github.io/helm-charts/
helm install redis-operator ot-helm/redis-operator --namespace ot-operators
helm install redis-cluster ot-helm/redis-cluster --set redisCluster.clusterSize=3 --set redisCluster.persistenceEnabled=false --namespace env138

**What did you expect to see?**
NAME                                 READY   STATUS    RESTARTS   AGE
redis-cluster-follower-0             1/1     Running   0          149m
redis-cluster-follower-1             1/1     Running   0          150m
redis-cluster-follower-2             1/1     Running   0          151m
redis-cluster-leader-0               1/1     Running   0          149m
redis-cluster-leader-1               1/1     Running   0          150m
redis-cluster-leader-2               1/1     Running   0          151m

**What did you see instead?**
NAME                                      READY   STATUS             RESTARTS   AGE
pod/redis-cluster-leader-0                1/2     CrashLoopBackOff   7          14m

NAME                                      TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                                 AGE
service/redis-cluster-leader              ClusterIP   10.104.118.112   <none>        6379/TCP,9121/TCP                                       14m
service/redis-cluster-leader-additional   ClusterIP   10.110.23.117    <none>        6379/TCP                                                14m
service/redis-cluster-leader-headless     ClusterIP   None             <none>        6379/TCP                                                14m

NAME                                    READY   AGE
statefulset.apps/redis-cluster-leader   0/3     14m

kubectl logs pod/redis-cluster-leader-0 -n env138 -c redis-cluster-leader:
```
sed: /data/nodes.conf: No such file or directory
Running without persistence mode
Running without TLS mode
Starting redis service in cluster mode.....
10:C 24 Feb 2023 13:39:39.743 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
10:C 24 Feb 2023 13:39:39.743 # Redis version=7.0.5, bits=64, commit=00000000, modified=0, pid=10, just started
10:C 24 Feb 2023 13:39:39.743 # Configuration loaded
10:M 24 Feb 2023 13:39:39.744 * monotonic clock: POSIX clock_gettime
10:M 24 Feb 2023 13:39:39.745 # Can't open /data/nodes.conf in order to acquire a lock: Permission denied
```

**Comment by vkanindriver** [comment]
[redis-operator.log](https://github.com/OT-CONTAINER-KIT/redis-operator/files/10824740/redis-operator.log)

**Comment by samof76** [comment]
@vkanindriver add this `storage` section in your `spec`
```
  storage:
    volumeMount:
      volume:
        - name: data
          emptyDir:
            sizeLimit: 1Gi
      mountPath:
        - mountPath: /data
          name: data
```
