### ISSUE TITLE
ARM64 images are for incorrect platform

### ISSUE THREAD

**Issue by milas** [OT-CONTAINER-KIT/redis-operator#452]
**What version of redis operator are you using?**
redis-operator version: v0.14.0

**Does this issue reproduce with the latest release?**
Yes

**What operating system and processor architecture are you using (`kubectl version`)?**
ARM64

**Related issues**
* #390
* #404
* #451

**What is the issue?**
The Dockerfile is set up for multiplatform building (even better with #451 imo 😉) and I've built and used it great without any modifications. I've successfully done AMD64->ARM64 cross compiles as well as native ARM64->ARM64 compiles.

However, the CI pipeline from [opstree/azure-devops-template:/operator-ci.yaml](https://github.com/opstree/azure-devops-template/blob/5ef598a0711cabc6bd6990e18353af058d83a393/operator-ci.yaml#L342-L381) is currently publishing AMD64 images as ARM64 images.

At a minimum, I believe it's possible to improve the current situation while still using the `Docker@2` action to do the builds entirely:
1. Set `DOCKER_BUILDKIT=1` as an environment variable across all your Docker jobs
   ```yaml
   variables:
     DOCKER_BUILDKIT: '1'
   ```
2. Pass the platform based on `ARCH`
   ```yaml
   args: '--platform=linux/arm64'
   ```

By enabling BuildKit, you'll be able to take advantage of the modern Docker builder (note: the classic builder is deprecated as of Docker v23.0, so you really always want this enabled). The important feature here is really for #451 to enable `FROM --platform=${BUILDPLATFORM} golang` to do cross-compiles via Go. Otherwise, the ARM64 build would need to either run on an ARM64 host or via emulation.

Secondly, by specifying the platform in the Docker CLI flags, the resulting image config will be correct. There's apparently no way to see architecture from the image on either Quay or GitHub Packages, but using [crane](https://github.com/google/go-containerregistry/blob/main/cmd/crane/doc/crane.md), you can see:
```shell
crane config ghcr.io/ot-container-kit/redis-operator/redis-operator:v0.14.0-arm64 | jq .architecture
"amd64"

crane config quay.io/opstree/redis-operator:v0.14.0-arm64 | jq .architecture
"amd64"
```

Another possibility would be to use buildx, which you already have setup in the `Makefile`. This [blog post](https://www.frakkingsweet.com/build-multi-architecture-images-in-azure-devops/) looks like a good reference. (You won't need to activate [binfmt](https://github.com/tonistiigi/binfmt) referenced in the first couple lines if you also make the changes in #451 to do a cross-compile. It won't hurt either way, it just makes it available for emulation if needed.)

The advantage to using buildx is that you can build and push the images in a single operation as manifest list, i.e. a single tag that can be used by either ARM64 or AMD64, with each platform automatically choosing the right architecture-specific image.

I hope this is helpful!

**Comment by shubham-cmyk** [comment]
Now we are using multi arch image of Docker.
