### ISSUE TITLE
Bump Operatorhub version to 0.14.0

### ISSUE THREAD

**Issue by sastorsl** [OT-CONTAINER-KIT/redis-operator#454]
**Is your feature request related to a problem? Please describe.**
Would like to see features such as `serviceType` available in the community operator, as mentioned in #317 

**Describe the solution you'd like**
Bump to the latest - `0.14.0` pr writing - `redis-operator` version in https://github.com/k8s-operatorhub/community-operators

**Describe alternatives you've considered**
N/A

**What version of redis-operator are you using?**

redis-operator version: `0.13.0`

**Additional context**
N/A

**Comment by michaelarnauts** [comment]
Is there an easy way to update the operator while waiting for it to enter the community-operators repo?

I've tried installing it via the helm chart, but that could not update the existing version.

```
$ helm upgrade redis-operator ot-helm/redis-operator --install --namespace openshift-operators
Release "redis-operator" does not exist. Installing it now.
Error: rendered manifests contain a resource that already exists. Unable to continue with install: ServiceAccount "redis-operator" in namespace "openshift-operators" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "redis-operator"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "openshift-operators"
```

**Comment by sedadas** [comment]
Hello! Is there any update on this? I can gladly create a PR, but will need some info on how to do it.
All the best!

**Comment by shubham-cmyk** [comment]
https://github.com/k8s-operatorhub/community-operators/pull/2905
