### ISSUE TITLE
Helm example raise no matches for kind in version error

### ISSUE THREAD

**Issue by Zeka13** [OT-CONTAINER-KIT/redis-operator#46]
Thx for awesome operator

This commands
```
kubectl create namespace redis-operator
helm upgrade redis-operator ./helm-charts/redis-operator --install --namespace redis-operator
```
```
# Create redis cluster setup
helm upgrade redis-cluster ./helm-charts/redis-setup -f ./helm-charts/redis-setup/cluster-values.yaml \
  --set setupMode="cluster" --set cluster.size=3 \
  --install --namespace redis-operator
```
Gave me this error, what I am doing wrong?

```no matches for kind "Redis" in version "redis.opstreelabs.in/v1alpha1"```

Thx in advance

**Comment by iamabhishek-dubey** [comment]
We will try to fix this ASAP :D

**Comment by Zeka13** [comment]
@iamabhishek-dubey thanks

There is also some mess with "helm-charts" directory name in docs (some commands says it helm without -charts)

in README
```
helm upgrade redis-cluster ./helm-charts/redis-setup -f ./helm/redis-setup/cluster-values.yaml
```

must be
```
helm upgrade redis-cluster ./helm-charts/redis-setup -f ./helm-charts/redis-setup/cluster-values.yaml
```

All this in total completly blow my mind

BTW there is no artifact for this chart and it must be installed from github sources?

**Comment by iamabhishek-dubey** [comment]
We are building an artifact repo for our helm charts, we are planning to move this operator helm charts their soon

**Comment by Zeka13** [comment]
@iamabhishek-dubey thx for a quick fix, I was also pretty sure you just forgot to change version from alpha to beta there, but it's you as a maintainer confirmed this

**Comment by iamabhishek-dubey** [comment]
Thanks for pointing this out :) but I am not merging this PR right now, I will ship the artifact repo changes as well

**Comment by Zeka13** [comment]
@iamabhishek-dubey this error is back, now with Helm repo
```
helm upgrade redis-cluster ot-helm/redis-setup \
>   --set setupMode="cluster" --set cluster.size=3 \
>   --install --namespace redis-operator
Release "redis-cluster" does not exist. Installing it now.
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: unknown object type "nil" in Redis.metadata.labels.app.kubernetes.io/version
```

**Comment by iamabhishek-dubey** [comment]
@Zeka13 ,

We have fixed this issue 

```
helm upgrade redis-cluster ot-helm/redis-setup \
>   --set setupMode="cluster" --set cluster.size=3 \
>   --install --namespace redis-operator
Release "redis-cluster" does not exist. Installing it now.
Error: unable to build Kubernetes objects from release manifest: error validating "": error validating data: unknown object type "nil" in Redis.metadata.labels.app.kubernetes.io/version
```

Also, we have a slack channel for open-source projects. Would you like to join that channel?

**Comment by Zeka13** [comment]
@iamabhishek-dubey thx for another fix

How can I join slack channel?

Now I am struggling with 
```
exporter:
  enabled: true
```
option

This is my current error

```Error response from daemon: manifest for quay.io/opstree/redis-exporter:1.0 not found: manifest unknown: manifest unknown```
or
```Error response from daemon: manifest for quay.io/opstree/redis-exporter:2.0 not found: manifest unknown: manifest unknown```

**Comment by iamabhishek-dubey** [comment]
I can share the link with you for slack.

https://quay.io/repository/opstree/redis-exporter?tag=latest&tab=tags

I can see the image is available and seems to be working fine for me.

**Comment by Zeka13** [comment]
@iamabhishek-dubey yes, send me the link please, if you need my email it's evgenii@anzu.io 
and I got exporter work like this, thx
```
exporter:
  enabled: true
  image: quay.io/opstree/redis-exporter
  tag: "1.0"
  imagePullPolicy: Always
```
