### ISSUE TITLE
Override services label selector or ignore helm related labels

### ISSUE THREAD

**Issue by applike-ss** [OT-CONTAINER-KIT/redis-operator#461]
I've written a helm chart which heavily relies on bitnamis common helm chart for naming and selectors.

This includes the labels on the redis cluster resource labels which seem to be used on the service resource as well.

The result is that it has a `helm.sh/chart: redis-cluster-<chart-version>` label.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
In an ideal world, i'd like to be able to override the complete set of labels used as selector on the service object on `.spec.kubernetesConfig.service.labels` of the redis cluster resource.

**Describe alternatives you've considered**
Manually defining a template declaration for labels to use which would not include `helm.sh/chart` as a key.

**What version of redis-operator are you using?**
redis-operator version: v0.11.0, however i checked the current CRD and it does not look like i could set labels manually on the service object

**Additional context**

**Comment by iamabhishek-dubey** [comment]
Please open this issue in helm repo https://github.com/OT-CONTAINER-KIT/helm-charts/. Closing it from here
