### ISSUE TITLE
is it support offline install？

### ISSUE THREAD

**Issue by xuziheng1002** [OT-CONTAINER-KIT/redis-operator#467]
We need install redis-operator offline but we can not connect to INTERNET on our server , so I think it will get error when I do helm install.

any way to solve it?

**Comment by shubham-cmyk** [comment]
I didn't get your question can you elaborate

**Comment by xuziheng1002** [comment]
we run RedisReplication on k8s cluster that is offline(without internet env),
the RedisReplication use istio-proxy and inject istio-sidecar in redis pod, when the pod startup, 
it will pull istio-pod from internet(docker.io/istio/proxyv2:1.6.3) ,
Although  I can copy the image to my image-server ,but how do I specify the istio-proxy-image in RedisReplication yaml？
