### ISSUE TITLE
Exposing Redis Service

### ISSUE THREAD

**Issue by kyoxzh888** [OT-CONTAINER-KIT/redis-operator#469]
Is there other way to add externalService? helm upgrade always get error：Error: UPGRADE FAILED: "redis" has no deployed releases.

**Comment by kyoxzh888** [comment]
I found the file of `spec.kubernetesConfig.service` can define the serviceType, but no field to define portNumber,
Is it possible to define port number by `spec.kubernetesConfig.service.annotations` field?

**Comment by iamabhishek-dubey** [comment]
https://github.com/OT-CONTAINER-KIT/helm-charts/blob/main/charts/redis-cluster/values.yaml#L64

You can configure the port using the helm values file.
