### ISSUE TITLE
Request goes to slave instance

### ISSUE THREAD

**Issue by xuziheng1002** [OT-CONTAINER-KIT/redis-operator#472]
We deployed RedisReplication in our k8s.
but load balancing(service in k8s) regardless of master/slave traffic.
when request goes readonly instance(slave) , client will get error:
```
Error in execution; nested exception is io.lettuce.core.RedisReadOnlyException: READONLY You can't write against a read only replica.
```
I checked the values.yaml, and that has not item to set load balancing policy,
how to solve this problem??

**Comment by shubham-cmyk** [comment]
Yes to redirect the request to a particular master you have to either use the sentinel mode or just use the headless service.

**Comment by xuziheng1002** [comment]
> Yes to redirect the request to a particular master you have to either use the sentinel mode or just use the headless service. `fqdn = <pod>.<service>.<namespace>.svc`

thanks for reply, but I still have 2 questions:
1. does the replication cluster failover when master pod was down?
2. Is the first pod(replicationName-0) always role master?

**Comment by xuziheng1002** [comment]
> 
In short,
Is the `fqdn = <pod>.<service>.<namespace>.svc` a reliable service that can be provided to business app?

**Comment by shubham-cmyk** [comment]
1. does the replication cluster failover when master pod was down? 
no the replication cluster with not failover if the master pod is down, to maintain failover you have to implement the redis sentinel. 
2. Is the first pod(replicationName-0) always role master?
by default the 1st pod i.e. replicationName-0 is the master pod but that could change if the master pod is deleted once. To perform operation on master you have to implement sentinel if you don't want to talk to pod directly. So sentinel would automatically perform read on slave and write on master

**Comment by xuziheng1002** [comment]
I just did a failover test on redis-replication, manually deleting the master pod. When the master pod restarted, I found that its IP had changed and the slave synchronization had stopped. Is redis-replication a beta version you are testing? It seems there are still many issues to be resolved. @shubham-cmyk

**Comment by shubham-cmyk** [comment]
Were you using sentinel mode along with it.
