### ISSUE TITLE
ERR Invalid node address specified

### ISSUE THREAD

**Issue by deepak-gc** [OT-CONTAINER-KIT/redis-operator#476]
**What version of redis operator are you using?**

```shell
kubectl logs <_redis-operator_pod_name> -n <namespace>
```

redis-operator version: v0.14.0

**Does this issue reproduce with the latest release?**
yes

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.14", GitCommit:"0f77da5bd4809927e15d1658fb4aa8f13ad890a5", GitTreeState:"clean", BuildDate:"2022-06-15T14:17:29Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:25:06Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/arm64"</summary><br><pre>
$ kubectl version

</pre></details>

**What did you do?**
Created redis cluster using below manifest
``` yaml
apiVersion: v1
kind: Namespace
metadata:
  name: redis-cluster
---
apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: RedisCluster
metadata:
  name: redis-cluster
  namespace: redis-cluster
  annotations:
    version: "1"
spec:
  clusterSize: 3
  clusterVersion: v7
  securityContext:
    runAsUser: 1000
    fsGroup: 1000
  persistenceEnabled: true
  kubernetesConfig:
    image: quay.io/opstree/redis:v6.2.5
    imagePullPolicy: Always
    resources:
      requests:
        cpu: 300m
        memory: 1Gi
      limits:
        cpu: 600m
        memory: 1.5Gi
  redisLeader:
    redisConfig:
      additionalRedisConfig: redis-external-config
  redisFollower:
    redisConfig:
      additionalRedisConfig: redis-external-config
  storage:
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 300Mi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-external-config
  namespace: redis-cluster
data:
  redis-additional.conf: |
    tcp-keepalive 400
    slowlog-max-len 158 
    stream-node-max-bytes 2048
    maxmemory 320mb

```

**What did you expect to see?**

A redis cluster running with 3 master and 1 slave for each

**What did you see instead?**
All redis nodes role is master and I see this error in redis-operator pod logs
```
>>> Performing hash slots allocation on 3 nodes...
Master[0] -> Slots 0 - 5460
Master[1] -> Slots 5461 - 10922
Master[2] -> Slots 10923 - 16383
M: af7d75bbea651053b2e8fa531c03d7b0248e332e redis-cluster-leader-0.redis-cluster-leader-headless.redis-cluster.svc:6379
   slots:[0-5460] (5461 slots) master
M: 7eaa4b836863185ba30dae7caf3613bde03be5eb redis-cluster-leader-1.redis-cluster-leader-headless.redis-cluster.svc:6379
   slots:[5461-10922] (5462 slots) master
M: f1db743fb3439c496b0eefcb7613d4ef34559312 redis-cluster-leader-2.redis-cluster-leader-headless.redis-cluster.svc:6379
   slots:[10923-16383] (5461 slots) master
>>> Nodes configuration updated
>>> Assign a different config epoch to each node
>>> Sending CLUSTER MEET messages to join the cluster
Node redis-cluster-leader-1.redis-cluster-leader-headless.redis-cluster.svc:6379 replied with error:
ERR Invalid node address specified: redis-cluster-leader-0.redis-cluster-leader-headless.redis-cluster.svc:6379
```

**Comment by deepak-gc** [comment]
AlsoI tried in k8s version 1.21.0, 1.23.16 and 1.25 with same results

**Comment by iamabhishek-dubey** [comment]
When using `quay.io/opstree/redis:v6.2.5`, use `clusterVersion: 6` instead of 7. This is documented in the documentation as well.

**Comment by deepak-gc** [comment]
Thank you @iamabhishek-dubey

**Comment by bdurrow** [comment]
Is documentation mentioned in https://github.com/OT-CONTAINER-KIT/redis-operator/issues/476#issuecomment-1491527656 [here](https://ot-container-kit.github.io/redis-operator/guide/redis-cluster-config.html#helm-parameters)?  I  If so there is only a vague clue as to this needs to match the image; there are no sample specs demonstrating this and it seems to indicate that the default image is major version 6 but the clusterVersion defaults to v7. Which could lead someone to believe that those values are compatible.

If the documentation is referring to the CRD Parameters a little further down on the same page there are even fewer clues.  

If the documentation referenced is https://ot-redis-operator.netlify.app/docs/ then I can't find any reference as to how to set clusterVersion.

I'm happy to submit a PR against the documentation but I was hoping to understand what @iamabhishek-dubey was referring to.
