### ISSUE TITLE
redis exporter couldn't connet to redis instance(redis://locahost:6379)

### ISSUE THREAD

**Issue by KevinZhang87** [OT-CONTAINER-KIT/redis-operator#481]
**What version of redis operator are you using?**

redis-operator version:0.14.0
redis-exporter:1.44.0

**Does this issue reproduce with the latest release?**
yes

**What operating system and processor architecture are you using (`kubectl version`)?**

kubernetes v1.23

**What did you do?**

When I create a redis-replication,set secret for password authorization  and turn on redis exporter by sidecar,in the log of redis exporter .however,I find many errors such as " couldn't connet to redis instance(redis://locahost:6379)" in log.I am not sure that redis exporter could work well because of the  redis-replication auth by secret.How can I fix it?

**Comment by sadath-12** [comment]
In my case it works fine when i get the logs through 

```
  k logs redis-replication-0  -c redis-exporter
```

I get something like
``` time="2023-04-06T16:18:29Z" level=info msg="Redis Metrics Exporter v1.44.0    build date: 2022-08-25-05:21:38    sha1: 19f7b036bb46869858eec74d8d3fc2186d641399    Go: go1.19    GOOS: linux    GOARCH: amd64"
time="2023-04-06T16:18:29Z" level=info msg="Providing metrics at :9121/metrics"
```

kubectl version 1.25

could u please provide more details on the manifest u deployed ?

@KevinZhang87

**Comment by genofire** [comment]
we got an equal problemn with "redis-sential"
