### ISSUE TITLE
Latest release docker image tag replacing with master

### ISSUE THREAD

**Issue by apenen** [OT-CONTAINER-KIT/redis-operator#491]
Hi!

Are you replacing tag 0.14.0 with master changes? That's a bad think, isn't it?

![image](https://user-images.githubusercontent.com/9284027/231703879-714dafbc-3bba-47c6-b0ba-8833342cd298.png)

**Comment by shubham-cmyk** [comment]
@apenen I think you are right this need to be fixed.

**Comment by apenen** [comment]
Someone could upload the correct image of tag 0.14.0?

**Comment by shubham-cmyk** [comment]
https://github.com/OT-CONTAINER-KIT/redis-operator/pull/496
