### ISSUE TITLE
I only can create a cluster with size 3 

### ISSUE THREAD

**Issue by popzones** [OT-CONTAINER-KIT/redis-operator#494]
I try to create a cluster with size 5

Command: helm upgrade redis ot-helm/redis-cluster  --set redisCluster.clusterSize=5 --namespace ot-operators

It executed successfully, but it create a cluster with size 3

**Comment by shubham-cmyk** [comment]
You need to change the size of the redis leader and redis follower also. 
Have you changed it ?

**Comment by shubham-cmyk** [comment]
Cluster Scaling would be merged and get into next release.
