### ISSUE TITLE
Redis replication with sentinel on same pods

### ISSUE THREAD

**Issue by astingengo** [OT-CONTAINER-KIT/redis-operator#506]
Is it there a way to deploy only 3 redis pods as replication and have on same pods sentinels installed as well?

**Comment by iamabhishek-dubey** [comment]
Nope, Also we do not encourage that because a container should be bound with a single process to manage its lifecycle. If there are 2 processes running, it will defeat the container philosophy.

**Comment by shubham-cmyk** [comment]
Maybe you can you do it @astingengo but then you have to launch sidecar for it
