### ISSUE TITLE
[BREAKING CHANGE WITH 0.14.0] redis PODs are unable to start after updating redis-operator

### ISSUE THREAD

**Issue by chobostar** [OT-CONTAINER-KIT/redis-operator#507]
This commit breaks compatibility with existing PODs and PVCs:
https://github.com/OT-CONTAINER-KIT/redis-operator/pull/445/files

Thus, after updating from 0.12.0 to 0.14.0, an error occurs:
>create Pod redis-prod-follower-1 in StatefulSet redis-prod-follower failed error: Pod "redis-prod-follower-1" is invalid: spec.containers[0].volumeMounts[0].name: Not found: "data"."

**How to reproduce**
1. Create persistence redis using operator version 0.12.0
2. Update operator to 0.14.0
3. Observe an error above

**Comment by shubham-cmyk** [comment]
This might not happen because the CR might not be updated can you verify that.

**Comment by chobostar** [comment]
> This might happen because the CR might not be updated can you verify that.

Thanks for feedback! Let me clarify how PVC works:

PVC old-name -> PV old-name = containts some data
PVC new-name -> PV new-name == empty

There is **no such thing as rename** PVC.

If POD's volume switches from "old-name" to "new-name" it will loss data.

@shubham-cmyk could you revert https://github.com/OT-CONTAINER-KIT/redis-operator/pull/445 ? It's breaking change because makes incompatible old setups with new operator.

**Comment by shubham-cmyk** [comment]
Thanks, @chobostar. I would revert this PR.

**Comment by chobostar** [comment]
Thanks, @shubham-cmyk 

jfyi, according to the docs:
https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-subdomain-names
>Most resource types require a name that can be used as a DNS subdomain name as defined in [RFC 1123](https://tools.ietf.org/html/rfc1123). This means the name must:
>contain no more than **253 characters**

K8s objects in most cases have no problem if long names.

**Comment by ryan-dyer-sp** [comment]
Any chance we can get a release for this?  Seems a bit much to have this breaking bug in place for 2mo now when a fix was put in place.
