### ISSUE TITLE
Support for Multi K8s Cluster redis cluster

### ISSUE THREAD

**Issue by dipeshtripathi** [OT-CONTAINER-KIT/redis-operator#512]
**Is your feature request related to a problem? Please describe.**
Running a distributed redis cluster across different kubernetes cluster for low latency communication between apps in different regions.

**Describe the solution you'd like**
Something like a multi-cluster distributed master-slave configuration where each cluster has its own master-slave, that are connected to other k8s clusters to for a distributed redis cluster

**Describe alternatives you've considered**
Trying my own installation of multi k8s cluster redis using https://artifacthub.io/packages/helm/bitnami/redis-cluster allow external tag

**What version of redis-operator are you using?**

redis-operator version: 0.13.0

**Additional context**

**Comment by shubham-cmyk** [comment]
This might be not the current requirement from this Redis operator since it would create a single point of failure.
