### ISSUE TITLE
Redis Replication Mode -> Slave to Master switchover not happeneing 

### ISSUE THREAD

**Issue by kannanvr** [OT-CONTAINER-KIT/redis-operator#514]
**What version of redis operator are you using?**
redis-operator version: v0.14.0
```shell
kubectl logs <_redis-operator_pod_name> -n <namespace>
```

 

redis-operator version: v0.14.0

 

**Does this issue reproduce with the latest release?**
  yes

 

**What operating system and processor architecture are you using (`kubectl version`)?**
<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version 
   kubernetes version 1.26.1
   platform : linux/amd64
</pre></details>

 

**What did you do?**
Exploring the redis replication mode with latest version v0.14.0, below are the findings
In replication mode , **when master is unavailable slave is not becoming master** and  database becomes read only. Even if master becomes available after sometime (new master pod comes up) slaves are not recognizing the new master but still points to the old master IP and also if we access the database through service  it still points to the slave which is read only but not pointing to new the master.

 

 

**What did you expect to see?**
1) when master is unavailable , any one of the slave should become master and should be able to perform write and read operation.
2) slaves should be able to recognize the new master.
3) If the old unavailable master comes up , it should come up as a slave to the new master.
4) should be able to perform Write and Read Operations at any point of time.

 

**What did you see instead?**
In replication mode , when master is unavailable slave is not becoming master and  database becomes read only. Even if master becomes available after sometime (new master pod comes up) slaves are not recognizing the new master but still points to the old master IP and also if we access the database through service  it still points to the slave which is read only but not pointing to new the master.

**Comment by shubham-cmyk** [comment]
It won't happen unless you have launched another redis sentinel resource alongside the redis replication mode.
