### ISSUE TITLE
[Feature] : Cannot configure SecurityContext at container level

### ISSUE THREAD

**Issue by ordovicia** [OT-CONTAINER-KIT/redis-operator#516]
**What version of redis operator are you using?**

redis-operator version: v0.14.0

**Does this issue reproduce with the latest release?**

Yes.

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version --output=yaml
clientVersion:
  buildDate: "2023-03-15T13:40:17Z"
  compiler: gc
  gitCommit: 9e644106593f3f4aa98f8a84b23db5fa378900bd
  gitTreeState: clean
  gitVersion: v1.26.3
  goVersion: go1.19.7
  major: "1"
  minor: "26"
  platform: linux/amd64
kustomizeVersion: v4.5.7
serverVersion:
  buildDate: "2023-03-15T13:33:12Z"
  compiler: gc
  gitCommit: 9e644106593f3f4aa98f8a84b23db5fa378900bd
  gitTreeState: clean
  gitVersion: v1.26.3
  goVersion: go1.19.7
  major: "1"
  minor: "26"
  platform: linux/amd64
</pre></details>

**What did you do?**

I need to configure Redis pods' SecurityContext at the container level, in addition to the pod level.
Linux capabilities, for example, can be configured at only container level (`pod.spec.containers.securityContext.capabilities` field).
Container-level SecurityContext configuration would allow us to make Redis pods conformant with [Pod Security Standard's Restricted policy](https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted).

**What did you expect to see?**

Currently, we can configure Redis pods' SecurityContext at the pod level only (`redis.spec.securityContext` field).
I expected that I can configure the container-level SecurityContext too.

**What did you see instead?**

We cannot configure Redis pods' SecurityContext at the container level.

**Comment by shubham-cmyk** [comment]
Fixed : https://github.com/OT-CONTAINER-KIT/redis-operator/pull/518
