### ISSUE TITLE
Redis operator v0.14.0 on Openshift operator hub

### ISSUE THREAD

**Issue by Zvezdoreel** [OT-CONTAINER-KIT/redis-operator#517]
**Is your feature request related to a problem? Please describe.**
The operator hub contains only the 0.13.0 version of the operator

**Describe the solution you'd like**
Upload the latest version of the operator

**What version of redis-operator are you using?**

redis-operator version: 0.13.0

**Additional context**
Is there a plan to update the version of the operator in the  Openshift operator hub?

**Comment by gazdagandras** [comment]
> @iamabhishek-dubey Please update it.

I would appreciate it.

**Comment by shubham-cmyk** [comment]
https://github.com/k8s-operatorhub/community-operators/pull/2905

**Comment by sedadas** [comment]
The operator is still not available because of [#2826](https://github.com/redhat-openshift-ecosystem/community-operators-prod/issues/2826). I have tested it on a non-OpenShift cluster using OperatorHub and the release there worked.

**Comment by shubham-cmyk** [comment]
https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/2967

There was another release of the v0.15.0
