### ISSUE TITLE
Missing RBAC permissions after OLM operator update to v0.14.0

### ISSUE THREAD

**Issue by jabbrwcky** [OT-CONTAINER-KIT/redis-operator#526]
**What version of redis operator are you using?**
redis-operator version: quay.io/opstree/redis-operator:v0.14.0

**Does this issue reproduce with the latest release?**

Yes. The operator was updated by OLM

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.6", GitCommit:"ff2c119726cc1f8926fb0585c74b25921e866a28", GitTreeState:"clean", BuildDate:"2023-01-18T19:22:09Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.13-eks-0a21954", GitCommit:"6305d65c340554ad8b4d7a5f21391c9fa34932cb", GitTreeState:"clean", BuildDate:"2023-04-15T00:33:45Z", GoVersion:"go1.19.8", Compiler:"gc", Platform:"linux/amd64"}

</pre></details>

**What did you do?**

OLM automatically updated the operator from v0.13.0 to v0.14.0

**What did you expect to see?**

Running operator after the update finished.

**What did you see instead?**

The operator failed to start because  the ClusterRole assigned to the ServiceAccount was missing permissions for  `redissentinels` and `redisreplications` and their respective subresources `/finalizers` and `/status` and it is trying to watch those resources.

After manually adding the resources and the respective subresources manually it started up as expected.

**Comment by thurcombe** [comment]
This isn't the only issue with this release. We implemented the missing rbac and then hit upon another issue, the redis pods wouldn't come up because the volumemount specified "data" as the name and the volumes from the existing deployment were "redis" or "redis-standalone" 

For now we've scaled down the operator and manually patched the statefulset. If you think this deserves its own issue, let me know

**Comment by shubham-cmyk** [comment]
@jabbrwcky 
Make sure you have upgraded your crd while you have upgraded from v0.13.0 to v0.14.0, helm doesn't upgrade crd on it's own so  you have to upgrade it independently.

**Comment by jabbrwcky** [comment]
The release was not upgraded via helm but via OLM - the CRDs are there just the permissions on the ClusterRole are missing

**Comment by shubham-cmyk** [comment]
@jabbrwcky 

Thanks I would add the cluster role in this repo also but for now you can take this from https://github.com/OT-CONTAINER-KIT/helm-charts/tree/main/charts/redis-operator/templates

**Comment by michaelarnauts** [comment]
This also occurred on a new install of 0.15.

**Comment by shubham-cmyk** [comment]
@michaelarnauts 
You have to explicitly upgrade the CRD. Even with the helm upgrade the crd are not updated by it's own.

**Comment by huuff** [comment]
@shubham-cmyk

I've had the same issue with a fresh install of 0.14 and 0.15 with OLM. Should I manually install the CRDs?

**Comment by ThomVivet** [comment]
Same issue today with a fresh OLM install of redis-operator.v0.15.1 onto openshift:
```
forbidden: User "system:serviceaccount:redis-operator:redis-operator" cannot create resource "events" in API group "" in the namespace "redis-operator"
forbidden: User "system:serviceaccount:redis-operator:redis-operator" cannot list resource "redisreplications" in API group "redis.redis.opstreelabs.in" at the cluster scope
forbidden: User "system:serviceaccount:redis-operator:redis-operator" cannot list resource "redissentinels" in API group "redis.redis.opstreelabs.in" at the cluster scope
```
It's OK after patching ClusterRole `redis-operator.v0.15.1-xxx` and adding `redisreplications` and `redissentinels` ressources where `redisclusters` was present.
I also added  `events` ressource (where `configmaps` was present)
