### ISSUE TITLE
Release v0.15.0

### ISSUE THREAD

**Issue by genofire** [OT-CONTAINER-KIT/redis-operator#530]
maybe use https://github.com/OT-CONTAINER-KIT/redis-operator/commit/9e15b33fcec54a09b63e04dc7e3ad014c06e7c43

**Comment by shubham-cmyk** [comment]
We have not released v0.15.0 officially now although I have released the Helm Charts now but the operator would be out in a week.

**Comment by genofire** [comment]
whould this be part of this release?:
 - #444 fix of redis-sential exporter

**Comment by shubham-cmyk** [comment]
Yes ! I would add this in this release.

**Comment by mraerino** [comment]
maybe you can bugfix the initcontainer feature before putting it out? https://github.com/OT-CONTAINER-KIT/redis-operator/issues/537

**Comment by shubham-cmyk** [comment]
v0.15.0 is released
