### ISSUE TITLE
master nodes are not coming up properly after failover 

### ISSUE THREAD

**Issue by sv6375261073** [OT-CONTAINER-KIT/redis-operator#534]
**What version of redis operator are you using?**
7.0.5

```shell
kubectl logs <_redis-operator_pod_name> -n <namespace>

"""Running without TLS mode
Starting redis service in cluster mode.....

*** FATAL CONFIG FILE ERROR (Redis 7.0.5) ***
Can't open the log file: No such file or directory
Running without TLS mode
Starting redis service in cluster mode.....

*** FATAL CONFIG FILE ERROR (Redis 7.0.5) ***
Can't open the log file: No such file or directory"""
<img width="704" alt="image" src="https://github.com/OT-CONTAINER-KIT/redis-operator/assets/36235393/203d4afc-4ae6-4f2f-b41f-1d94f8e1aed6">

```

redis-operator version:
0.14.3
**Does this issue reproduce with the latest release?**

Don't know

**What operating system and processor architecture are you using (`kubectl version`)?**
MacOS 13.2.1 Ventura
<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
1.27.1
</pre></details>

**What did you do?**
Master nodes were failing and  trying to recover data using AOF file, So it was restarting again and again because of AOF file format issue. Becuase of this tried to restart all master node then wint in to the bad state as above log issue.

1: Deploy the cluster with the default redis configuration.
2: Do redis-benchmark at high level upto millions of requests.
3: when master starts failing with and start getting refused connection issue.
4: Just restart all master nodes.
**What did you expect to see?**
> Nodes should comeup fresh if not able to recove the data using AOF.

**Comment by sv6375261073** [comment]
Reinstalling also getting the same issue.

**Comment by shubham-cmyk** [comment]
can you check whether you have a default storage class defined
