### ISSUE TITLE
Init countainer tries to mount invalid volume when persistence is enabled

### ISSUE THREAD

**Issue by mraerino** [OT-CONTAINER-KIT/redis-operator#537]
**What version of redis operator are you using?**

redis-operator version: v0.15.0

**Does this issue reproduce with the latest release?**

Yes.

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-04-14T13:14:41Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.6+k3s1", GitCommit:"3b1919b0d55811707bd1168f0abf11cccc656c26", GitTreeState:"clean", BuildDate:"2023-06-26T16:07:10Z", GoVersion:"go1.19.10", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What did you do?**

Install redis-operator v0.15.0 using the Helm Chart.

Create a standalone redis with persistence and an `initContainer`:

```yaml
apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: Redis
metadata:
  name: cache
spec:
  kubernetesConfig:
    image: quay.io/opstree/redis:v7.0.5
    redisSecret:
      name: redis-secret
      key: password
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: default
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
  initContainer:
    enabled: true
    image: busybox:1.36.1
    command: [echo, Hello, World]
```

**What did you expect to see?**

A working init container

**What did you see instead?**

The statefulset complains about an invalid pod template:

```
Events:
  Type     Reason        Age                 From                    Message
  ----     ------        ----                ----                    -------
  Warning  FailedCreate  14s (x15 over 96s)  statefulset-controller  create Pod cache-0 in StatefulSet cache failed error: Pod "cache-0" is invalid: spec.initContainers[0].volumeMounts[0].name: Not found: "init-cache"
```

afaik, the volume name should be `cache` in this case, the `init` prefix doesn't make any sense.

<details><summary>Full spec of the statefulset</summary><br><pre>
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    banzaicloud.com/last-applied: UEsDBBQACAAIAAAAAAAAAAAAAAAAAAAAAAAIAAAAb3JpZ2luYWzsVlFv2zYQ/i/3LMlW48SN3rLYHYo1iSFn7UMRBGfqXBGmSJU8KvEC/feBkuMomZsV21OBvNgieTx+d/fdRz4A1vIzWSeNhgywrt2oSSGCjdQFZLBkZFp7tSSGCCpiLJARsgdArQ0jS6NdGFoqpEtM7dgSKVy5RAaHbD1BdHDVMWpB4VDPJWmWm1igKAnaCBSuSHV+sa4PmESw8Y5NJf+ihI1RG8nJWvl7USTSjDRWz/z+hLmrscMSZmO3dUzVI+xbR+zrW97WwSCgLlAZ3YVl1Iu5NoKXp+8hD88ZYjN3mmxOa7KkBTnIvr6oSp+9QzkcNemKGEPBhNFsjVJkIQtZ35cwD/vgFVxeBrPpdEp4PEnjdfpuHE/WJ2m8Oi4wfj+dTienJ5NJun4P7U0bgatJ9CWvlRToIEsjcKRIsLFhoUIW5adftoQhRLKNFHR5MGVxSVgociGpTFWtkKkL+607fia1O/YEvqLUZHvCk266/x26xTxfflxezy/P57fzy7PfPs1nEEGDytNj3tpob53PZx+Xt2ezWT4w6uBlo5EyAlVpHGcnR9PTf25bnC2XX67yvf8P1lQBoCNhif+gbU7rMN7QFjKo0bk7Y4unhurOiXtraNuB/+U8/zzPby+uZvMBrmdqMbC9/nPxmulNBLLCb2H6u8dtKM2OMaM+0maajJNjiEDJhjQ5t7Bm1RGT7h9TXlUYNOErrNCVEMHIOztaST0qCRWXoiSxSVwJoc3XKJW3dF1acqVRBWRHEUgtWaKakcLtkoTRRd/+NVlpiqeZcQTOC0HODfanEbCsyHh+MnxNMC1hIX+lSCw5422n4Q9tBI1RvqIL4zX3JK/C5wK5hAxGnVT8MPqgtG9d8b+7Iqb72lgmmzVpMpkk45cIH9chgvDR12mvTQtjGbLT9F36yjZr2AijIIPr80UH6RkPOoxa8vlzwRtQWJTmTkMEcShUOh6Ps/ATSN1xZBDjyrvtytxnaXJ0kqRPsQT/8aEG+s98POixvWlvgob7ukCmJVtk+rYdOj9XKKvr3aW4O+TtWvy3a/HHKvB0X2KnQRem6NIKOWHxxUqmq5CPF5wDS989Oe6+HRvbsycd/y77O7ifOlfo3O6NUwplfBH3VQwvm0eyFGH1g1S0C7Dbjux33B4OARuUCleK8v3TcBwN3onjtv07AAD//1BLBwiVDTvYdwMAAHEMAABQSwECFAAUAAgACAAAAAAAlQ072HcDAABxDAAACAAAAAAAAAAAAAAAAAAAAAAAb3JpZ2luYWxQSwUGAAAAAAEAAQA2AAAArQMAAAAA
    redis.opstreelabs.in: "true"
    redis.opstreelabs.instance: cache
  creationTimestamp: "2023-07-01T21:48:15Z"
  generation: 1
  labels:
    app: cache
    redis_setup_type: standalone
    role: standalone
  name: cache
  namespace: default
  ownerReferences:
  - apiVersion: redis.redis.opstreelabs.in/v1beta1
    controller: true
    kind: Redis
    name: cache
    uid: 777ea541-f120-4f61-b5da-8777496441f8
  resourceVersion: "55442263"
  uid: 6fe8dbb9-f497-43a6-bf90-e1f2dd279547
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: authentik-cache
      redis_setup_type: standalone
      role: standalone
  serviceName: cache-headless
  template:
    metadata:
      annotations:
        redis.opstreelabs.in: "true"
        redis.opstreelabs.instance: cache
      creationTimestamp: null
      labels:
        app: cache
        redis_setup_type: standalone
        role: standalone
    spec:
      containers:
      - env:
        - name: PERSISTENCE_ENABLED
          value: "true"
        - name: REDIS_ADDR
          value: redis://localhost:6379
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: redis-secret
        - name: SERVER_MODE
          value: standalone
        - name: SETUP_MODE
          value: standalone
        image: quay.io/opstree/redis:v7.0.5
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - bash
            - /usr/bin/healthcheck.sh
          failureThreshold: 3
          initialDelaySeconds: 1
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: cache
        readinessProbe:
          exec:
            command:
            - bash
            - /usr/bin/healthcheck.sh
          failureThreshold: 3
          initialDelaySeconds: 1
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: cache
      - env:
        - name: PERSISTENCE_ENABLED
          value: "true"
        - name: REDIS_ADDR
          value: redis://localhost:6379
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: redis-secret
        - name: SERVER_MODE
          value: standalone
        - name: SETUP_MODE
          value: standalone
        image: quay.io/opstree/redis-exporter:v1.44.0
        imagePullPolicy: IfNotPresent
        name: redis-exporter
        ports:
        - containerPort: 9121
          name: redis-exporter
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - echo
        - Hello
        - world
        image: busybox:1.36.1
        imagePullPolicy: IfNotPresent
        name: init-cache
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: init-cache
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      annotations:
        redis.opstreelabs.in: "true"
        redis.opstreelabs.instance: cache
      creationTimestamp: null
      labels:
        app: cache
        redis_setup_type: standalone
        role: standalone
      name: cache
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: hcloud-volumes
      volumeMode: Filesystem
    status:
      phase: Pending
status:
  availableReplicas: 0
  collisionCount: 0
  currentRevision: cache-ffd4456d9
  observedGeneration: 1
  replicas: 0
  updateRevision: cache-ffd4456d9
</pre></details>

**Comment by shubham-cmyk** [comment]
@mraerino Thanks for raising this issue This would be fixed in v0.15.0 release.
