### ISSUE TITLE
v0.15.0 Release Notes?

### ISSUE THREAD

**Issue by ammmze** [OT-CONTAINER-KIT/redis-operator#545]
I noticed there is a new release (`0.15.0`) up on [quay.io/opstree/redis-operator](https://quay.io/repository/opstree/redis-operator?tab=tags&tag=v0.15.0), however I am not seeing any release notes to indicate what has changed. Based on the [github actions report](https://github.com/OT-CONTAINER-KIT/redis-operator/runs/14766628945) it looks like there are some issues authenticating with github to publish the new release on github.

**Comment by shubham-cmyk** [comment]
Would be out on monday

**Comment by shubham-cmyk** [comment]
https://github.com/OT-CONTAINER-KIT/redis-operator/releases/tag/v0.15.0
