### ISSUE TITLE
Is the operator ready for production?

### ISSUE THREAD

**Issue by fzyzcjy** [OT-CONTAINER-KIT/redis-operator#547]
Hi thank you for the redis-operator! I wonder whether this one is ready for production?

**Comment by shubham-cmyk** [comment]
Yes It would work in the production, the previous version v0.13.0 is already been deployed in production. 
But I i would recommend you to test the latest feature like cluster Scaling, etc. and you can raise the issue if found I would try to respond them to asap.

**Comment by fzyzcjy** [comment]
@shubham-cmyk Hi thanks for the reply! I want to use Redis with master - slave and 3 sentinels. Is that in production as well?

**Comment by shubham-cmyk** [comment]
It would work good! you must try but the only issue opened right now here regarding it is : https://github.com/OT-CONTAINER-KIT/redis-operator/issues/522

Which means that rolling and upgrading is little bit difficult right now but I would fix it v15.0.1

**Comment by fzyzcjy** [comment]
I see, thank you!

To be honest, I am a bit hesitate, because if operators have even just subtle bugs, it will ruin the whole production environment - I use Redis for data (not only cache), and require HA. Anyway I may try the operator :)

**Comment by shubham-cmyk** [comment]
@fzyzcjy You should try this operator in the dev first.

**Comment by fzyzcjy** [comment]
Sure! I am just worried that dev tests cannot cover each and every corner case. 

> The failure in the operator would not cause any harm to the running environment here.

Well, e.g. if it does not heal Redis during a failure, then it is super big harm (the main worry I have).

**Comment by shubham-cmyk** [comment]
@fzyzcjy  

We try to save the data in PV so the data won't get removed anyway. For extra concern, we never put the ownerReferences on the PVC to prevent the accidental removal of the volumes.  For the worst case you might need to back-up using our scripts or maybe anyway you like.

**Comment by fzyzcjy** [comment]
@shubham-cmyk Definitely - the operator will not cause any data loss, though the main worry is about availability (HA).
