### ISSUE TITLE
How to disable environment variable for pods in same namespace

### ISSUE THREAD

**Issue by waza-ari** [OT-CONTAINER-KIT/redis-operator#548]
After implementing the operator in the cluster and adding a couple of `Redis` resources, I ran into an issue with the operator "automagically" adding environment variables to pods running in the same namespace.

This pod for example is fired up in the same namespace as a standalone redis instance without anything attached using `kubectl -n ns-name run my-shell --rm -i --tty --image ubuntu -- bash` and has a bunch of REDIS related environment variables:

```
# env | grep REDIS
REDIS_PORT_6379_TCP=tcp://10.0.211.70:6379
REDIS_SERVICE_HOST=10.0.211.70
REDIS_ADDITIONAL_PORT_6379_TCP=tcp://10.0.137.192:6379
REDIS_ADDITIONAL_PORT_6379_TCP_ADDR=10.0.137.192
REDIS_ADDITIONAL_SERVICE_PORT=6379
REDIS_SERVICE_PORT=6379
REDIS_ADDITIONAL_PORT=tcp://10.0.137.192:6379
REDIS_ADDITIONAL_SERVICE_PORT_REDIS_CLIENT=6379
REDIS_ADDITIONAL_SERVICE_HOST=10.0.137.192
REDIS_PORT_6379_TCP_PROTO=tcp
REDIS_ADDITIONAL_PORT_6379_TCP_PROTO=tcp
REDIS_PORT_6379_TCP_PORT=6379
REDIS_PORT_6379_TCP_ADDR=10.0.211.70
REDIS_PORT=tcp://10.0.211.70:6379
REDIS_SERVICE_PORT_REDIS_CLIENT=6379
REDIS_ADDITIONAL_PORT_6379_TCP_PORT=6379
```

One of these variables interferes with my application and it is actually overriding what I manually set using a `ConfigMap`. Is there a way to disable this behaviour?

**Comment by shubham-cmyk** [comment]
These variables are automatically added by k8s because it has a service discovery mechanism via env Variable. 
Also it should not be the case that these env Variable are over writing the env variable that you are passing
