### ISSUE TITLE
Custom labels support

### ISSUE THREAD

**Issue by jurim76** [OT-CONTAINER-KIT/redis-operator#550]
Support "podLabels" for CRD, to define custom labels

**Comment by chowmean** [comment]
I assume this means labels to the redis pods? if yes let me take a look at this. @jurim76

**Comment by jurim76** [comment]
Yes, for redis pods. For example, we are using custom pod labels for
different teams.

**Comment by shubham-cmyk** [comment]
@jurim76 
This could be only done on the redid cluster mode. 
Leader and follower pods could have different labels this could be achieved.

but if you talk about each pod in the redis leader sts would have a different label this is not possible by the operator.  However, you can add unique labels on each pod via kubectl

**Comment by jurim76** [comment]
Thank you for clarification
