### ISSUE TITLE
redis images missing?

### ISSUE THREAD

**Issue by pasztorl** [OT-CONTAINER-KIT/redis-operator#557]
Hi,

I see on the main page that redis operator supports 7.0.11 redis image, but on the default repo (from example): https://quay.io/repository/opstree/redis?tab=tags&tag=latest I see up to 7.0.5.

There are other location what are you using to push latest builds?

**Comment by shubham-cmyk** [comment]
Now fixed. 

Image should be : `quay.io/opstree/redis:v7.0.11`
