### ISSUE TITLE
Does this support auth and tls for sentinel as well

### ISSUE THREAD

**Issue by sangeethdba** [OT-CONTAINER-KIT/redis-operator#559]
**Is your feature request related to a problem? Please describe.**

Im looking for answers if this operator support auth and tls for sentinel instnaces.?
requirepass 
tls-port {{ sentinel_port  }}
port 0
tls-replication yes
tls-auth-clients yes
tls-cert-file {{ redis_certs_dir }}/redis_node.crt
tls-key-file {{ redis_certs_dir }}/redis_node.key
tls-ca-cert-file {{ redis_certs_dir }}/redis_rootca.crt
tls-ca-cert-dir {{ redis_certs_dir }}
sentinel auth-pass {{ redis_master_id }} {{ redis_default_password.content }}

I see tls  and password auth config for redis .looking same for sentinel as well

**Describe the solution you'd like**

**Describe alternatives you've considered**

**What version of redis-operator are you using?**

redis-operator version:

**Additional context**

**Comment by sangeethdba** [comment]
@shubham-cmyk

**Comment by shubham-cmyk** [comment]
I just checked out there was no TLS setup on the Sentinel but the AUTH is supported right now, I would add the TLS on the sentinel asap.

**Comment by sangeethdba** [comment]
Thank 
you @shubham-cmyk

**Comment by shubham-cmyk** [comment]
Fixed by : https://github.com/OT-CONTAINER-KIT/redis/pull/35
