### ISSUE TITLE
Operator fails to reconcile new resources

### ISSUE THREAD

**Issue by jessebye** [OT-CONTAINER-KIT/redis-operator#56]
We have observed that the operator silently fails to reconcile new resources after some time. The logs are empty, so there is no indication what is going on. Also, the pod is still healthy. But new `Redis` resources are ignored and do not get reconciled.

**Comment by iamabhishek-dubey** [comment]
Can you give us an example of an instance when this happened?

**Comment by jessebye** [comment]
I'm not sure how to reproduce, as it seems to happen at random, and there are no logs to indicate the failure. We just restart the operator and it starts working again.
