### ISSUE TITLE
Auth failure when following the getting started documentation

### ISSUE THREAD

**Issue by marshtompsxd** [OT-CONTAINER-KIT/redis-operator#561]
redis-operator version:

quay.io/opstree/redis-operator:v0.12.0

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:53:42Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-30T06:34:50Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What did you do?**

Hi Redis operator developer,

thanks for building the nice operator.

I was following the documentation of [getting started](https://ot-container-kit.github.io/redis-operator/guide/setup.html#redis-cluster) to set up a Redis cluster.

However, when I try to connect to the leader node it reports auth failure:
```
> kubectl exec -it redis-cluster-leader-0 -n ot-operators -- redis-cli -a Opstree@1234 cluster nodes
Defaulted container "redis-cluster-leader" out of: redis-cluster-leader, redis-exporter
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
AUTH failed: ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?
78883b9e8409661fd4c1a55b7f94811b34628452 10.244.0.37:6379@16379 master - 0 1689786945586 3 connected 10923-16383
939fad86cc3f4a742889c9012f0f0f4c5db063ea 10.244.0.29:6379@16379 myself,master - 0 1689786945000 1 connected 0-5460
686fa50143e207aaca13de5d48a5c59ff7fb3279 10.244.0.34:6379@16379 slave f387eea784087265e2c46ed55aaca99ef7e1d496 0 1689786945082 2 connected
fd5b24b6273d275b92a532bfab2a4a97612857a9 10.244.0.38:6379@16379 slave 78883b9e8409661fd4c1a55b7f94811b34628452 0 1689786945586 3 connected
f387eea784087265e2c46ed55aaca99ef7e1d496 10.244.0.33:6379@16379 master - 0 1689786945000 2 connected 5461-10922
24c5a88f05799d5e281d0f2c7c74f3324bd0ce5a 10.244.0.30:6379@16379 slave 939fad86cc3f4a742889c9012f0f0f4c5db063ea 0 1689786946088 1 connected
```

I am wondering if there is anything missing in the documentation or if I missed some step. I have manually created a `redis-secret` but it still doesn't work
```
> kubectl get secret redis-cluster-secret -n ot-operators -o yaml
apiVersion: v1
data:
  password: cGFzc3dvcmQ=
kind: Secret
metadata:
  creationTimestamp: "2023-07-19T16:53:50Z"
  name: redis-cluster-secret
  namespace: ot-operators
  resourceVersion: "3037"
  uid: 67880751-cad1-47b2-adc8-06b57990efc2
type: Opaque
```

**Comment by shubham-cmyk** [comment]
`quay.io/opstree/redis-operator:v0.12.0`

I see you are using the v0.12.0 you might think to get on the v0.15.0. 

Checkout this example how to setup the password 
https://github.com/OT-CONTAINER-KIT/redis-operator/tree/master/example/password_protected
you might be missing to add below field in the redis cluster :

```
    redisSecret:
      name: redis-secret
      key: password
```
over here : https://github.com/OT-CONTAINER-KIT/redis-operator/blob/master/example/password_protected/clusterd.yaml#L16C1-L18C20
