### ISSUE TITLE
CRD not found spec in rediscluster resource

### ISSUE THREAD

**Issue by mug3n451** [OT-CONTAINER-KIT/redis-operator#563]
**What version of redis operator are you using?**

```shell
kubectl logs <_redis-operator_pod_name> -n <namespace>
```

redis-operator version:

**Does this issue reproduce with the latest release?** yes

**What operating system and processor architecture are you using (`kubectl version`)?** 
Eks 1.25

**What did you do?**
try to install redis-cluster with operator

helm upgrade redis-cluster ot-helm/redis-cluster   --set redisCluster.clusterSize=3 --install 

but i have thi error:

Release "redis-cluster" does not exist. Installing it now.
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(RedisCluster.spec): unknown field "podSecurityContext" in in.opstreelabs.redis.redis.v1beta1.RedisCluster.spec, ValidationError(RedisCluster.spec.storage): unknown field "nodeConfVolumeClaimTemplate" in in.opstreelabs.redis.redis.v1beta1.RedisCluster.spec.storage

**Comment by shubham-cmyk** [comment]
This seems like the CRD you are using is of the v0.14.0. There have been few breaking change in the v0.15.0. 
So you have to delete the previous CRD and install the operator using the latest helm chart. i.e. v0.15.3

**Comment by mug3n451** [comment]
I have upgrade the CRD with the last helm chart version and now is ok.
Thanks
