### ISSUE TITLE
Regression when using pod security context

### ISSUE THREAD

**Issue by darkrift** [OT-CONTAINER-KIT/redis-operator#566]
This [commit](https://github.com/OT-CONTAINER-KIT/redis-operator/commit/2142b250aa4fa22458504cc6bf2e62ece4f2b251) renamed the field "securityContext" to "podSecurityContext" breaking backward compatibility.

This means that charts built on top of this CRD with 0.14.0 cannot be used with 0.15.0. The following should be done:

1. Revert the name change to the previous name securityContext for the PodSecurityContext and another name for the "real" SecurityContext type (IE. containerSecurityContext)

If you want to change names, you should produce a new version of the CRD object then it doesn't break compatibility along with a webhook to handle conversion

It might end up duplicating effort to produce new CRD version, but that would the less impacting path to support upgrade using more recent versions of the operator while still allowing bigger changes toward a 1.0 version

My day job has many teams using this operator and upgrading 0.15 will require quite the effort since our deployment are managed by argoCD, meaning that we can't just update the operator because if we delete resources after tagging them with reconcile-skip, they are going to be recreated from the code repository code preventing such configuration to be created as they won't match the new CRD.

We can potentially contribute with a PR depending on which approach you would prefer for the fix.

**Comment by darkrift** [comment]
@shubham-cmyk any thoughts on this issue ? 

We're currently looking at this issue because the 0.15.0 release is a serious blocker for us due to the various breaking changes.

**Comment by shubham-cmyk** [comment]
Should we roll out a v0.15.1 could be good idea that could just support the conversion from v0.14.0?

**Comment by darkrift** [comment]
@shubham-cmyk that would be the perfect solution so that 0.14.0 can still be supported and upgraded when we roll out updates of the operator ! 💯

**Comment by shubham-cmyk** [comment]
i would try to complete this by this weekend.

**Comment by darkrift** [comment]
@shubham-cmyk it would also need to support missing the new volume template for the node-conf (effectively supporting every breaking changes from 0.14.0 to 0.15.0)

**Comment by shubham-cmyk** [comment]
@darkrift Got it...

**Comment by shubham-cmyk** [comment]
@darkrift Can you check the PR is almost ready. 
I am thinking about how to add the support for the change in the volume

**Comment by darkrift** [comment]
> @darkrift Can you check the PR is almost ready. 
> 
> I am thinking about how to add the support for the change in the volume

Can this not be made "default values" in the code with kubebuilder:default ?

**Comment by shubham-cmyk** [comment]
@darkrift 

Since the conversion support would be merged soon. 
I was thinking to discuss a few points. 

I am thinking that can you use Blue Green Strategy here. 
Since when you upgraded the to v0.15.1 you could support both the version. 

We need to Run a JOB that just migrates the data from old cluster to new cluster.

**Comment by shubham-cmyk** [comment]
> > @darkrift Can you check the PR is almost ready.
> > I am thinking about how to add the support for the change in the volume
> 
> @shubham-cmyk Can this not be done by specifying "default values" in the code with kubebuilder:default to v1beta1 ? Wouldn't that be forward/backward compatible ?

I don't think when I upgrade to new sts i would be able to use these PVC. We need to perform data from PVC to PVC

**Comment by darkrift** [comment]
> > > @darkrift Can you check the PR is almost ready.
> > > I am thinking about how to add the support for the change in the volume
> > 
> > 
> > @shubham-cmyk Can this not be done by specifying "default values" in the code with kubebuilder:default to v1beta1 ? Wouldn't that be forward/backward compatible ?
> 
> I don't think when I upgrade to new sts i would be able to use these PVC. We need to perform data from PVC to PVC

@shubham-cmyk Why can we not reuse the new PVC ? Is it only a naming problem ?

In this case we can add a “naming pattern” field in the CRD to support both.

I’m currently out camping without much access and no laptop. I’ll be abke to help in 2 days

**Comment by shubham-cmyk** [comment]
Beside the naming problem there is issue. 
In v0.15.0 we created 2 PVC one for handling the `data` and one for handling the redis-cluster node information i.e. `node.conf`.
and in v0.14.0 same PVC contains `data` and `node.conf`. 
So you have to some how handle that also. 

Maybe the best solution could be migrate the `dump.rdb` from old PVC to new PVC

**Comment by darkrift** [comment]
@shubham-cmyk  The problem is that pods cannot be dynamically updated. So unless it's the operator that does this work behind the scene, I don't see an easy and automated way out to migrate from 0.14.0 to 0.15.0.

 I’m not sure the operator is at that level yet though. To make such changes and “migrate” pods from 0.14 to 0.15, one way could be to launch a converter pod that would do that “migration work” of spliting the data from 1 pvc to 2 (by having a new pvc created, tie to that new pod, make the data move over the other pvc and unassociate the pvc to that pod.

Another way is to make 0.15 CRD somehow compatible with 0.14.0.

This can be done with a new boolean flag specifying if we want data and config separated in 2 pvc or combined (default to split), along with the pvc name prefix option to support 0.14.0 hardcoded naming.

What was this pvc split trying to fix/achieve ?
