### ISSUE TITLE
Supporting an upgrade for redisclusters from pre 0.14.0

### ISSUE THREAD

**Issue by jgatt513** [OT-CONTAINER-KIT/redis-operator#569]
### Discussed in https://github.com/OT-CONTAINER-KIT/redis-operator/discussions/568

<div type='discussions-op-text'>

<sup>Originally posted by **jgatt513** August  1, 2023</sup>
Hello Redis team and community,

Are there plans on supporting an upgrade for redisclusters from pre 0.14.0 or is the only solution forward is to blow away all the clusters and let the operator recreate them?</div>

**Comment by shubham-cmyk** [comment]
https://github.com/OT-CONTAINER-KIT/redis-operator/discussions/568
