### ISSUE TITLE
Some Questions and Feature request 👍 

### ISSUE THREAD

**Issue by OpsPita** [OT-CONTAINER-KIT/redis-operator#57]
Well I tested some helm charts and other operators and seems this one works great!
Nice Work guys!

Missing Feature -> Tolerations 
https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/

And is RedisConfig on the Redis CR working?
I cant find a way to apply new configuration to my nodes

Thanks a-lot ! appreciate your work!

**Comment by iamabhishek-dubey** [comment]
RedisConfig is not ready right now, but we are planning to implement it soon. Also Thanks for the taints and tolerations suggestion
