### ISSUE TITLE
Custom Resource Object API

### ISSUE THREAD

**Issue by asayles** [OT-CONTAINER-KIT/redis-operator#570]
404 when visiting this link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#podsecuritycontext-v1-core

**Comment by shubham-cmyk** [comment]
Can you elaborate what do you want to ask ? 
@asayles

**Comment by ppborah** [comment]
@shubham-cmyk, he might be referring to this : https://ot-redis-operator.netlify.app/docs/crd-reference/redis-api/#redisclusterspec
Some of the fields like securityContext have been assigned [PodSecurityContext](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#podsecuritycontext-v1-core) which points to 404.

**Comment by shubham-cmyk** [comment]
Got it ! Thanks @ppborah 

This would be fixed when the v0.15.1 would be out.
