### ISSUE TITLE
How to enable istio using this redis operator?

### ISSUE THREAD

**Issue by jdafda** [OT-CONTAINER-KIT/redis-operator#575]
**What version of redis operator are you using?**

```shell
redis-operator.v0.15.0
```

**What did you do?**
 

I have added istio injection enable using this method : [https://docs.openshift.com/container-platform/4.12/service_mesh/v2x/prepare-to-deploy-applications-ossm.html]( https://docs.openshift.com/container-platform/4.12/service_mesh/v2x/prepare-to-deploy-applications-ossm.html)

**What did you expect to see?**
I am expected to see two pod running , one with redis leader or redis follower and one for envoy proxy

**What did you see instead?**
I see just one pod running.

Is there any documentation about how to enable istio for redis using this operator. also i want to use redis proxy client using filters, any kid of document will be useful here.

Let me know in case more info needed.

**Comment by drivebyer** [comment]
as far as i know, envoy is injected as sidecar to pod, not seprate pod.

**Comment by jdafda** [comment]
Correct and I am able to fix that , now issue is  I applied envoy filter for my redis cluster, gossiping protocol work fine , but still have issue with redis client.  I am following this [https://github.com/zhaohuabing/istio-redis-culster](https://github.com/zhaohuabing/istio-redis-culster)
