### ISSUE TITLE
ACL file not loaded into `redis.conf` when using redis release images

### ISSUE THREAD

**Issue by tbao2011** [OT-CONTAINER-KIT/redis-operator#577]
**What version of redis operator are you using?**
redis-operator version:
v0.15.0

**Does this issue reproduce with the latest release?**
Yes

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"clean", BuildDate:"2023-07-20T02:11:13Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"clean", BuildDate:"2023-07-19T12:14:49Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What did you do?**

The issue is based on the ACL feature in https://github.com/OT-CONTAINER-KIT/redis-operator/pull/486.

1. Deploy redis operator via Helm chart
2. Change the image in the [standalone config](https://github.com/OT-CONTAINER-KIT/redis-operator/blob/67c4f3be6e94f5ee4d21726ad52a9ad053f18610/example/acl_config/standalone.yaml#L10C12-L10C35) from `shubham192001/redis:2.0` to `quay.io/opstree/redis:v7.0.11`, then apply the YAML. Note that I had to update `acl.secret.name` to `acl.secret.secretName` to get it applied.
3. Deploy the secret YAML: https://github.com/OT-CONTAINER-KIT/redis-operator/blob/67c4f3be6e94f5ee4d21726ad52a9ad053f18610/example/acl_config/acl-secret.yaml#L1-L8
7. Wait for the redis pod to become ready. SSH into the container and run `redis-cli acl users`.

**What did you expect to see?**
The two ACL users `opstree` and `buildpiper` (as specified in the `acl-secret` YAML) should be available.

**What did you see instead?**
Only the `default` user is listed.
```
bash-5.1$ redis-cli acl users
1) "default"
```

When checking `/etc/redis/redis.conf`, it missed the line of `aclfile`. Note that it worked when I used the redis image of `shubham192001/redis:2.0` as listed in the sample YAML, but not with the redis release image. Cross-checked the two and found the `entrypoint.sh` in the `shubham` image additionally contains an `acl_setup` function that appends the `aclfile` line to `/etc/redis/redis.conf`:

```sh
acl_setup(){
    if [[ "$ACL_MODE" == "true" ]]; then
        {
            echo aclfile /etc/redis/user.acl
            } >> /etc/redis/redis.conf

    else
        echo "ACL_MODE is not true, skipping ACL file modification"
    fi
}
```
I don't see such lines in `quay.io/opstree/redis:v7.0.11` nor the source repo (https://github.com/OT-CONTAINER-KIT/redis/blob/fad1231d54ca9eea5683027741d757e58047c7fa/entrypoint.sh). Did I miss any other config change? Or should `acl_setup` be checked into the `redis` repo? Thanks!

**Comment by shubham-cmyk** [comment]
Yes @tbao2011 you are right I forgot to merge the ACL addition on the main repo thanks it went un noticed. 
This would be solved by e2e test case where are under process.

**Comment by shubham-cmyk** [comment]
@tbao2011 

Please use the `latest` OR `v7.0.12` now

**Comment by tbao2011** [comment]
Confirmed that `v7.0.12` worked fine with the ACL feature. Thanks for the quick fix!

**Comment by shubham-cmyk** [comment]
@tbao2011 Actually I forgot to merge that branch while releasing the Operator. 
It was nice catch from your side you remind me that mine `shubham192001/redis:2.0` image was working good. 

If you would like you can change the ACL example image from `shubham192001/redis:2.0` to `quay.io/opstree/redis:v7.0.12`
