### ISSUE TITLE
Can't open /data/nodes.conf in order to acquire a lock: I/O error

### ISSUE THREAD

**Issue by lililifan** [OT-CONTAINER-KIT/redis-operator#614]
Defaulted container "redis-cluster-leader" out of: redis-cluster-leader, redis-exporter
Redis is running without password which is not recommended
sed: /data/nodes.conf: I/O error
Running without TLS mode
Starting redis service in cluster mode.....
10:C 08 Sep 2023 11:11:55.493 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
10:C 08 Sep 2023 11:11:55.493 # Redis version=7.0.5, bits=64, commit=00000000, modified=0, pid=10, just started
10:C 08 Sep 2023 11:11:55.493 # Configuration loaded
10:M 08 Sep 2023 11:11:55.494 * monotonic clock: POSIX clock_gettime
10:M 08 Sep 2023 11:12:35.987 # Can't open /data/nodes.conf in order to acquire a lock: I/O error

**Comment by shubham-cmyk** [comment]
Have you passed the appropriate user and group

**Comment by smutel** [comment]
I am the same issue. What user/group I need to use ?

**Comment by shubham-cmyk** [comment]
@smutel 
Use the standard given in the examples; 
https://github.com/OT-CONTAINER-KIT/redis-operator/blob/master/example/v1beta2/redis-cluster.yaml#L10

Make sure to use the 
Operator version : v0.15.1 
with the redis image as per in the examples
