### ISSUE TITLE
Validation hooks are not working

### ISSUE THREAD

**Issue by dntosas** [OT-CONTAINER-KIT/redis-operator#619]
Hey team!

Upgraded recently to v15 and operations stopped working cause validation hooks and conversions are down. I saw some PRs merged with fixes on that, are you also thinking of any patch release soon? 🙏 TIA!

**Comment by shubham-cmyk** [comment]
We didn't merged any validation webhook right now we have conversion webhooks right now but that is useful only if you are using `v1beta1`
