### ISSUE TITLE
Update go version

### ISSUE THREAD

**Issue by shubham-cmyk** [OT-CONTAINER-KIT/redis-operator#636]
**Describe the solution you'd like**

We have been using the go1.17 which is now quiet old we should upgrade the operator to the go1.21.
We should also consider upgrading these library : 

```
k8s.io/api v0.23.0
k8s.io/apimachinery v0.23.0
k8s.io/client-go v0.23.0
sigs.k8s.io/controller-runtime v0.11.0
```

**What version of redis-operator are you using?**

redis-operator version: v0.15.1

**Comment by Azanul** [comment]
May I take this up?

**Comment by shubham-cmyk** [comment]
> May I take this up?

Yes

**Comment by shubham-cmyk** [comment]
@Azanul I think you can take this issue now
