### ISSUE TITLE
[Refactor] - Refactor redis_setup_type string to const

### ISSUE THREAD

**Issue by drivebyer** [OT-CONTAINER-KIT/redis-operator#646]
Currently, the label key `redis_setup_type` is generate by:
https://github.com/OT-CONTAINER-KIT/redis-operator/blob/26f9c0be576c6fbcd263f322ac7bd38478aa8e5e/k8sutils/labels.go#L122-L132

The caller of `getRedisLabels` set `redis_setup_type` by string literal, such as:
https://github.com/OT-CONTAINER-KIT/redis-operator/blob/26f9c0be576c6fbcd263f322ac7bd38478aa8e5e/k8sutils/redis-replication.go#L48.

We could refactor this string literal to const for code clean.

**Comment by titanventura** [comment]
Would like to work on this. Please assign !
