### ISSUE TITLE
[CI] - Migrate golangci-lint to official github action

### ISSUE THREAD

**Issue by drivebyer** [OT-CONTAINER-KIT/redis-operator#648]
Currently, we install and run golangci-lint by shell command:
https://github.com/OT-CONTAINER-KIT/redis-operator/blob/26f9c0be576c6fbcd263f322ac7bd38478aa8e5e/.github/workflows/operator-ci.yaml#L48-L61

We could change it to official action, see https://golangci-lint.run/usage/install/#github-actions

**Comment by titanventura** [comment]
Would like to pick this up !

**Comment by drivebyer** [comment]
> Would like to pick this up !

Ok
