### ISSUE TITLE
upgrade to version 0.5.0 not work on standalone mode

### ISSUE THREAD

**Issue by Danipiario** [OT-CONTAINER-KIT/redis-operator#65]
I have a redis standalone cluster (1 node) installed via operator v 0.4.0
Upgrading to version 0.5.0 give me the error:
`The Redis "redis" is invalid: spec.size: Invalid value: 3: spec.size in body should be greater than or equal to 3`

Also deleting the old operator and installing from scratch the new one give me the same error.
I have a standalone cluster with a single node so I'd expect to be able to set size: 1 on the yaml

**Comment by iamabhishek-dubey** [comment]
The size field doesn't matter in standalone mode, you can remove size or keep the value 3. But in standalone it will create a single redis pod.

**Comment by iamabhishek-dubey** [comment]
Closing this issue, please reopen if the issue persists.
