### ISSUE TITLE
Installation error - unknown field "spec.podSecurityContext"

### ISSUE THREAD

**Issue by amitoj** [OT-CONTAINER-KIT/redis-operator#667]
**What version of redis operator are you using?**

Using latest release

**Does this issue reproduce with the latest release?**
Yes, I have been using this setup for months without any issues, but recently encountered this error.

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: v1.28.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.1

</pre></details>

**What did you do?**
```
helm repo add ot-helm https://ot-container-kit.github.io/helm-charts/
helm repo update
helm upgrade redis-operator ot-helm/redis-operator --install --namespace redis
helm test redis-operator --namespace redis
helm upgrade redis ot-helm/redis -f custom-values.yaml --install --namespace redis
```

**What did you expect to see?**
I expected the commands to execute successfully without any errors, as they have in the past.

**What did you see instead?**
I encountered the following error:

```
W1010 15:44:05.777051 4182932 warnings.go:70] unknown field "spec.podSecurityContext"
Error: conversion webhook for redis.redis.opstreelabs.in/v1beta1, Kind=Redis failed: Post "https://webhook-service.redis-operator.svc:443/convert?timeout=30s": service "webhook-service" not found

```

**Comment by mindthecap** [comment]
I have the same problem. Got the helm chart working with release 0.15.3 (someting breaks with 0.15.7).

**Comment by shubham-cmyk** [comment]
THe apiVersion should be `v1beta2`

**Comment by minhdtb-tanaakk** [comment]
yes, I got the same issue
