### ISSUE TITLE
Front door logo has spelling mistake

### ISSUE THREAD

**Issue by javajon** [OT-CONTAINER-KIT/redis-operator#67]
![image](https://user-images.githubusercontent.com/9454012/117999014-6d54f680-b312-11eb-931a-c34b34d0aa7a.png)

**Comment by iamabhishek-dubey** [comment]
Thanks for pointing this out, we will fix this

**Comment by iamabhishek-dubey** [comment]
This issues has been fixed in https://github.com/OT-CONTAINER-KIT/redis-operator/pull/76
