### ISSUE TITLE
YAML parse error on redis-replication/templates/redis-replication.yaml: error converting YAML to JSON: yaml

### ISSUE THREAD

**Issue by abdul90082** [OT-CONTAINER-KIT/redis-operator#671]
I am encountering an error when utilizing the most recent version of the Redis operator (0.15.1). I am also employing the latest Redis replication and Sentinel versions, which are 0.15.10 and 0.15.11, respectively. 

`Error: YAML parse error on redis-replication/templates/redis-replication.yaml: error converting YAML to JSON: yaml: line 24: did not find expected key`

NAME     	          NAMESPACE   REVISION	     UPDATED              	STATUS  	CHART                	APP VERSION
redis-operator	redis-operator	   1       	2023-10-18 17:25:43.747825484 +0200 CEST	deployed	redis-operator-0.15.9	0.15.1    

These crds installed successfully

redis.redis.redis.opstreelabs.in                                2023-10-18T15:25:39Z
redisclusters.redis.redis.opstreelabs.in                        2023-10-18T15:25:39Z
redisreplications.redis.redis.opstreelabs.in                    2023-10-18T15:25:39Z
redissentinels.redis.redis.opstreelabs.in                       2023-10-18T15:25:39Z

The same configuration works perfectly with the older version 0.15.0. 

{"level":"error","ts":1697662911.2933629,"logger":"controller.redis","msg":"Could not wait for Cache to sync","reconciler group":"redis.redis.opstreelabs.in","reconciler kind":"Redis","error":"failed to wait for redis caches to sync: timed out waiting for cache to be synced","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:208\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:234\nsigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/manager/runnable_group.go:218"}

**Comment by shubham-cmyk** [comment]
@abdul90082 what file you applied ?

**Comment by abdul90082** [comment]
I am using this yaml configuration.
`---
redisReplication:
  resources: 
    requests:
      cpu : 1m
      memory: 1Mi
    limits:
      cpu : 100m
      memory: ${memory}Gi
  ignoreAnnotations:
    - redis.opstreelabs.in/ignore
externalConfig:
  enabled: true
  data: |
    appendonly ${appendonly}
    save "${save}"
    %{ for key, value in extra_config ~}
    ${key} ${value}
    %{ endfor ~}

nodeSelector:
  deploy/dbs: "true"

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - redis-sentinel
        topologyKey: "kubernetes.io/hostname"
storageSpec:
  volumeClaimTemplate:
    spec:
      storageClassName: local-path
      accessModes: ["ReadWriteOnce"]`

**Comment by abdul90082** [comment]
@shubham-cmyk  I've experimented with various values for the ignore annotation, but the error remains consistent. In theory, it should work with an empty string, but that doesn't seem to be the case. I suspect that the issue lies within the redis-replication template file. Do you have any insights on how to resolve this problem? It's causing significant challenges in our production environment.
What I have attempted.
```
ignoreAnnotations: 
    - "redis.opstreelabs.in/ignore" 
```
```
ignoreAnnotations: 
    - "redis.opstreelabs.in"
```
    
 ```
 ignoreAnnotations: 
    - "redis.opstreelabs.in/ignore"
```

```
ignoreAnnotations: 
    - ""
 
```
```
ignoreAnnotations: 
    - "redis.opstreelabs.in/ignore"
    - "redis.opstreelabs.in"
````

If you would like to debug or require additional information, I am more than willing to provide it.

**Comment by shubham-cmyk** [comment]
@abdul90082 

I think it was occurring due to missing deep copy. 
Fixed here : https://github.com/OT-CONTAINER-KIT/redis-operator/pull/672

**Comment by shubham-cmyk** [comment]
This must be due to : 

```
  ignoreAnnotations:
    - redis.opstreelabs.in/ignore
```

ignore annots : 

verify me that we are not facing this issue if you have removed the above block

**Comment by shubham-cmyk** [comment]
I am not sure your CRD are even updated or not please check that

**Comment by shubham-cmyk** [comment]
This should not be possible because our e2e test are passing over here : https://github.com/OT-CONTAINER-KIT/redis-operator/tree/master/tests/e2e/v1beta2/ignore-annots

**Comment by shubham-cmyk** [comment]
can you apply these crd : 

https://github.com/OT-CONTAINER-KIT/redis-operator/tree/master/config/crd/bases

**Comment by phlegx** [comment]
hi @shubham-cmyk first of all: thanks for the explanation. I guess all these problems are finally solved then in version   `v0.15.2`

As I run into these issues too and there is no much we can change to make it work, may I ask when the release is to be expected?

thank you very much
Martin

**Comment by shubham-cmyk** [comment]
We are currently fixing the scaling issue here and writing e2e test case as many possible to get the possible error and fix that. 
I would say it would take a month for stable release. 

Since now we would have a good testing coverage and less chance of failure

**Comment by phlegx** [comment]
Thank you @shubham-cmyk for the fast reply!

One month is quite a long time but of course I fullly understand this has to be properly tested before it can be released. 

It is just now like that, that with the scaling issue the current operator has, we might face data loss since the "master"might not properly detected. Do you have an idea on how to minimize/eradicating the risk up until new operator is released?

The only thing I can currently think of to keeps safe do is scale down to 1.  That would certainly make sure nothing can happen.

**Comment by shubham-cmyk** [comment]
@phlegx 
can you elaborate what risk exactly ? if you are talking about the scaling i would suggest to not use that in the current release. 
this would work but it is still under dev and not tested good. 

Since we have don't have any good  e2e test but now we have worked on it and faced some issue so we are fixing that.
