### ISSUE TITLE
How do I use kubectl to deploy redis-operator

### ISSUE THREAD

**Issue by jiangjian0920** [OT-CONTAINER-KIT/redis-operator#68]
No deployment file for operator was found

**Comment by mxsxs2** [comment]
https://ot-container-kit.github.io/redis-operator/guide/installation.html
Bottom of that page has  section about it.

**Comment by mxsxs2** [comment]
You are right. They are missing.

**Comment by iamabhishek-dubey** [comment]
Thanks for pointing this out, we will fix it ASAP

**Comment by iamabhishek-dubey** [comment]
Documentation is fixed in https://github.com/OT-CONTAINER-KIT/redis-operator/pull/76
