### ISSUE TITLE
ARM Support for Redis-Exporter

### ISSUE THREAD

**Issue by sgillamwright** [OT-CONTAINER-KIT/redis-operator#681]
**Is your feature request related to a problem? Please describe.**
Redis Operator has ARM support, and as of a recent push the redis images themselves have an arm:latest tag. Deploying Redis out with monitoring enabled fails as the redis-exporter image has no ARM support. The exporter not having ARM support is problematic as monitoring is important.

**Describe the solution you'd like**
Would be nice to have an ARM image of the exporter, as suggested by the redis-monitoring example

**Comment by shubham-cmyk** [comment]
`v1.45.0` & `latest` tag of the redis-exporter are multi-arch image
