### ISSUE TITLE
Redis-operator pod is crashing

### ISSUE THREAD

**Issue by raghuiisc** [OT-CONTAINER-KIT/redis-operator#71]
I bought up a kubernetes setup with one master and one node as below

root@rkota-k8s-1:~/redis-operator/helm-charts# kubectl get nodes
NAME          STATUS   ROLES                  AGE    VERSION
rkota-k8s-1   Ready    control-plane,master   2d2h   v1.21.1
rkota-k8s-2   Ready    <none>                 2d1h   v1.21.1

root@rkota-k8s-1:~/redis-operator/helm-charts# kubectl get pods -A
NAMESPACE     NAME                                  READY   STATUS    RESTARTS   AGE
kube-system   coredns-558bd4d5db-lqjcn              1/1     Running   0          2d2h
kube-system   coredns-558bd4d5db-n6pnb              1/1     Running   0          2d2h
kube-system   etcd-rkota-k8s-1                      1/1     Running   0          2d2h
kube-system   kube-apiserver-rkota-k8s-1            1/1     Running   0          2d2h
kube-system   kube-controller-manager-rkota-k8s-1   1/1     Running   0          2d2h
kube-system   kube-proxy-7pzfv                      1/1     Running   0          2d1h
kube-system   kube-proxy-zmjmq                      1/1     Running   0          2d2h
kube-system   kube-scheduler-rkota-k8s-1            1/1     Running   0          2d2h
kube-system   weave-net-kjhbv                       2/2     Running   0          2d1h
kube-system   weave-net-qxnhs                       2/2     Running   0          2d1h

Then i followed the steps mentioned to bring the redis-operator as below, redis-operator pod is crashing.

$ helm repo add ot-helm https://ot-container-kit.github.io/helm-charts/
$ helm upgrade redis-operator ot-helm/redis-operator --install --namespace redis-operator

root@rkota-k8s-1:~/redis-operator/helm-charts# kubectl get pods -A
NAMESPACE        NAME                                  READY   STATUS    RESTARTS   AGE
kube-system      coredns-558bd4d5db-lqjcn              1/1     Running   0          2d2h
kube-system      coredns-558bd4d5db-n6pnb              1/1     Running   0          2d2h
kube-system      etcd-rkota-k8s-1                      1/1     Running   0          2d2h
kube-system      kube-apiserver-rkota-k8s-1            1/1     Running   0          2d2h
kube-system      kube-controller-manager-rkota-k8s-1   1/1     Running   0          2d2h
kube-system      kube-proxy-7pzfv                      1/1     Running   0          2d1h
kube-system      kube-proxy-zmjmq                      1/1     Running   0          2d2h
kube-system      kube-scheduler-rkota-k8s-1            1/1     Running   0          2d2h
kube-system      weave-net-kjhbv                       2/2     Running   0          2d1h
kube-system      weave-net-qxnhs                       2/2     Running   0          2d1h
redis-operator   redis-operator-78c558545b-7lncb       1/1     Running   2          118s
root@rkota-k8s-1:~/redis-operator/helm-charts# kubectl logs redis-operator-78c558545b-7lncb -n redis-operator
2021-05-22T15:07:25.002Z        ERROR   controller-runtime.manager      Failed to get API Group-Resources       {"error": "Get \"https://10.96.0.1:443/api?timeout=32s\": dial tcp 10.96.0.1:443: i/o timeout"}
github.com/go-logr/zapr.(*zapLogger).Error
        /go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132
sigs.k8s.io/controller-runtime/pkg/manager.New
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/manager/manager.go:317
main.main
        /workspace/main.go:68
runtime.main
        /usr/local/go/src/runtime/proc.go:204
2021-05-22T15:07:25.002Z        ERROR   setup   unable to start manager {"error": "Get \"https://10.96.0.1:443/api?timeout=32s\": dial tcp 10.96.0.1:443: i/o timeout"}
github.com/go-logr/zapr.(*zapLogger).Error
        /go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132
main.main
        /workspace/main.go:77
runtime.main
        /usr/local/go/src/runtime/proc.go:204

root@rkota-k8s-1:~/redis-operator/helm-charts# kubectl describe pod redis-operator-78c558545b-7lncb -n redis-operator
Name:         redis-operator-78c558545b-7lncb
Namespace:    redis-operator
Priority:     0
Node:         rkota-k8s-2/10.62.45.32
Start Time:   Sat, 22 May 2021 15:05:27 +0000
Labels:       name=redis-operator
              pod-template-hash=78c558545b
Annotations:  <none>
Status:       Running
IP:           10.240.1.4
IPs:
  IP:           10.240.1.4
Controlled By:  ReplicaSet/redis-operator-78c558545b
Containers:
  redis-operator:
    Container ID:  docker://3f13c8a7b3c96ccf105d7baef27d2e117919ae6c27a2dfce5a658d2811100065
    Image:         quay.io/opstree/redis-operator:v0.5.0
    Image ID:      docker-pullable://quay.io/opstree/redis-operator@sha256:7370767377306e4cec120a9a8dcfafa393543e8ba838d641c879817eb19edcb0
    Port:          <none>
    Host Port:     <none>
    Command:
      /manager
    Args:
      --leader-elect
    State:          Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Sat, 22 May 2021 15:07:56 +0000
      Finished:     Sat, 22 May 2021 15:08:26 +0000
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Sat, 22 May 2021 15:06:54 +0000
      Finished:     Sat, 22 May 2021 15:07:25 +0000
    Ready:          False
    Restart Count:  3
    Limits:
      cpu:     100m
      memory:  100Mi
    Requests:
      cpu:        100m
      memory:     100Mi
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-w5fsn (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  kube-api-access-w5fsn:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Guaranteed
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  3m                   default-scheduler  Successfully assigned redis-operator/redis-operator-78c558545b-7lncb to rkota-k8s-2
  Normal   Pulled     2m56s                kubelet            Successfully pulled image "quay.io/opstree/redis-operator:v0.5.0" in 2.811933742s
  Normal   Pulled     2m21s                kubelet            Successfully pulled image "quay.io/opstree/redis-operator:v0.5.0" in 2.880951827s
  Normal   Pulled     93s                  kubelet            Successfully pulled image "quay.io/opstree/redis-operator:v0.5.0" in 2.779256463s
  Normal   Pulling    35s (x4 over 2m59s)  kubelet            Pulling image "quay.io/opstree/redis-operator:v0.5.0"
  Normal   Created    32s (x4 over 2m56s)  kubelet            Created container redis-operator
  Normal   Pulled     32s                  kubelet            Successfully pulled image "quay.io/opstree/redis-operator:v0.5.0" in 3.043849136s
  Normal   Started    31s (x4 over 2m55s)  kubelet            Started container redis-operator
  Warning  BackOff    0s (x4 over 110s)    kubelet            Back-off restarting failed container

**Comment by iamabhishek-dubey** [comment]
This is not the operator issue, seems like you have some restriction with communication with Kubernetes API Server
```
{"error": "Get "https://10.96.0.1:443/api?timeout=32s\": dial tcp 10.96.0.1:443: i/o timeout"}
```

Check for network policy or try to curl manually the endpoint by creating a debug container

**Comment by raghuiisc** [comment]
Thanks for pointing it out. i have reset-ted the kubernetes cluster and recreated using the below options in the kubectl init which solved the issue.

Forced Kubernetes to use a different network by using the following flags:

kubeadm init --pod-network-cidr=192.168.0.0/16 --apiserver-cert-extra-sans=xxx.xxx.xxx.xxx --apiserver-advertise-address=xxx.xxx.xxx.xxx

Change the xxx.xxx.xxx.xxx with the commmunication IP address of your K8S master.

**Comment by iamabhishek-dubey** [comment]
Closing this issue
