### ISSUE TITLE
Global Sidecar Deployment / Global Redis Exporter Usage

### ISSUE THREAD

**Issue by jakeschurch** [OT-CONTAINER-KIT/redis-operator#721]
Looking to see if future product roadmap for redis operator contains ability to globally set redis exporter for all redis deployments, or likewise, global sidecars to be deployed to all redis deployments. 

Goal here being easing product dev mental overhead by not thinking about enabling monitoring or additional use cases like authentication.

redis-operator version: 0.15.19

**Comment by shubham-cmyk** [comment]
This can only be done by setting up a mutating webhook that could run with the redis operator or as an different deployment. 

If you want a quick fix you can setup a mutating webhook. I am putting this in the next milestone. 

Thanks for the suggestion.

**Comment by jakeschurch** [comment]
thanks so much!
