### ISSUE TITLE
"Creating redis cluster by executing cluster creation commands" log line is redundand and misleading

### ISSUE THREAD

**Issue by egorksv** [OT-CONTAINER-KIT/redis-operator#764]
Source code link:

https://github.com/OT-CONTAINER-KIT/redis-operator/blob/3e6fcb9a5f44052db0767cbe278f83516d278741/controllers/rediscluster_controller.go#L194

Operator issues "Creating redis cluster by executing cluster creation commands" every reconciliation cycle (i.e. every 10 seconds).

This is extremely misleading as it creates perception that cluster is NOT created/reconciled yet and extra actions are still necessary, whereas in reality the cluster has been ready for some time.

It also does not add any value during actual cluster configuration phase as it's not directly linked to any operations

**Comment by drivebyer** [comment]
Yes, we can put the log clause into the
```
if nc := k8sutils.CheckRedisNodeCount
```
