### ISSUE TITLE
There are problems with NodePort

### ISSUE THREAD

**Issue by jiangjian0920** [OT-CONTAINER-KIT/redis-operator#79]
I successfully ran the Redis cluster according to the content in the document,  I could get through Podip :6379, but I could not get through SVCIP :6379

**Comment by lmulder** [comment]
Hello, I resolved the issue by removing label redis=monitor from both redis-master and redis-slave services.

**Comment by iamabhishek-dubey** [comment]
I will check this

**Comment by jiangjian0920** [comment]
I have removed the label, but the question seems to remain, do I need to do anything else

**Comment by jiangjian0920** [comment]
I have removed the label, but the question seems to remain, do I need to do anything else

**Comment by lmulder** [comment]
Sorry I may have not been precise enough, you have to remove this label from pod selector (.spec.selector), removing from .metadata.labels is not enough.

**Comment by jiangjian0920** [comment]
thanks for that。
Is there any way to set the port number for NodePort

**Comment by georgecrawford** [comment]
@iamabhishek-dubey Do you have an ETA for when this fix will be released? I can confirm that removing the pod selector `redis=monitor` from redis-master fixed the issue for us. Thanks!
