### ISSUE TITLE
Error when deleting redis cr resource

### ISSUE THREAD

**Issue by villl** [OT-CONTAINER-KIT/redis-operator#801]
{"level":"error","ts":"2024-03-06T07:51:49Z","msg":"Reconciler error","controller":"redissentinel","controllerGroup":"redis.redis.opstreelabs.in","controllerKind":"RedisSentinel","RedisSentinel":{"name":"redis-sentinel","namespace":"default"},"namespace":"default","name":"redis-sentinel","reconcileID":"dcaea14e-16d6-4985-9f0d-87392a914c75","error":"Operation cannot be fulfilled on redissentinels.redis.redis.opstreelabs.in \"redis-sentinel\": StorageError: invalid object, Code: 4, Key: /cls-81t21053/redis.redis.opstreelabs.in/redissentinels/default/redis-sentinel, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 2804befc-e55f-46d5-9a0b-2321a267b0bb, UID in object meta: ","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/Documents/mycode/go/src/ot-redis-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/Documents/mycode/go/src/ot-redis-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/Documents/mycode/go/src/ot-redis-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227"}

**Comment by drivebyer** [comment]
Could you please provide more details about the issue? For example, the resources applied, the operator's version, and the steps to reproduce it.
