### ISSUE TITLE
Certificates rotation problem, any advice ?

### ISSUE THREAD

**Issue by JeremyLARDENOIS** [OT-CONTAINER-KIT/redis-operator#838]
Hello there,

**Describe your question**
We use redis-operator, we are facing issue and we are asking ourself if there is a way to manage the rotation of certificates. Does redis-operator have such functionnalities ?

**What version of redis-operator are you using?**

redis-operator version: 0.14.0

**Additional context**
We are using it in a kubernetes cluster to create a redis cluster with 3 masters sharded and 3 replicate (1 follower for each shard). We use certmanager and the certificate is generated by cert-manager. Any suggestion, idea and help is welcome !

Thank you for your time

**Comment by drivebyer** [comment]
@JeremyLARDENOIS Thanks for using this operator.

What are certificates used for?

**Comment by JeremyLARDENOIS** [comment]
We use certificates between our redis cluster and our envoy proxies and also for the communication between redis nodes

**Comment by drivebyer** [comment]
@JeremyLARDENOIS  

I'm not entirely certain about this; it might not be the responsibility of the operator. You could consider seeking assistance from tools like cert-manager.

**Comment by JeremyLARDENOIS** [comment]
Thank you for your response and your quick answer, I will search if there is a solution with cert-manager.
