### ISSUE TITLE
Support topologySpreadConstraints

### ISSUE THREAD

**Issue by evrardjp** [OT-CONTAINER-KIT/redis-operator#868]
**Is your feature request related to a problem? Please describe.**

Types have affinity/pdb, but do not have topologyspreadconstraints.
This is useful to split into multiple AZs.

**Describe the solution you'd like**

I guess add support of tsc into multiple places of the code.

**Describe alternatives you've considered**

Forking.

**What version of redis-operator are you using?**

redis-operator version: latest

**Additional context**

I am okay to implement it on my own. However, I would love to have the maintainers voice on:
- Whether you are interested to have that feature in the operator
- What parts of the code might be impacted, and what are the areas of attention [OPTIONAL]. In other words, if you can point me the way (to make my life easier, and avoid reverse engineering) I would love it.
(Right now, I assume I need to update the CRD, its docs, the common types, redis-cluster, redis-types, redissentinel-types, redisreplication-types, redissentinel, statefulset, and the relative tests. Not sure about conversion go files)

**Comment by drivebyer** [comment]
I think we need to write conversion-related because if people use v1beta1 with topologySpreadConstraints, our operator needs to reconcile it to the right status.

**Comment by xiaozhuang-a** [comment]
+1

**Comment by CsongSY** [comment]
+1
