### ISSUE TITLE
Whether this deployment cannot be connected across clusters

### ISSUE THREAD

**Issue by jiangjian0920** [OT-CONTAINER-KIT/redis-operator#88]
When my program connects to a Redis cluster across clusters, it returns a connection PODIP timeout.

**Comment by iamabhishek-dubey** [comment]
Can you please share more details about your issue?

**Comment by jiangjian0920** [comment]
I think because Redis clusters are connected via PODIP, the returned PODIP connection fails when the application connects across clusters. Is there any configuration to allow clusters to relate to each other via nodeip

**Comment by iamabhishek-dubey** [comment]
In the security context, you can enable the privilege mode to run with node IP. But I would suggest expose your Redis service using LoadBalancer and NodePort and then access it using it if your application is running outside of its cluster.

**Comment by iamabhishek-dubey** [comment]
Closing this issue because, please reopen it if needed

**Comment by revathyr13** [comment]
Hello @iamabhishek-dubey 

I am facing a similar issue. I have exposed the redis leader service as Loadbalancer. But still its redirecting to pod IP.

172.3x.xx.xxx :6379>  get key8
-> Redirected to slot [13004] located at 10.x.x.x:6379
Could not connect to Redis at 10.233.80.113:6379: Connection timed out

Is there any way to access this cluster from outside the cluster?
