### ISSUE TITLE
The name and label role of the pod after master-slave switching are incorrect

### ISSUE THREAD

**Issue by xiaozhuang-a** [OT-CONTAINER-KIT/redis-operator#882]
**Describe your question**

**What version of redis-operator are you using?**

redis-operator version: 

**Additional context**

**Comment by drivebyer** [comment]
It needs to be fixed.

**Comment by drivebyer** [comment]
We can use the label key `redis-role` to distinguish between the master and slave, which is implemented by https://github.com/OT-CONTAINER-KIT/redis-operator/pull/925.

**Comment by drivebyer** [comment]
As said to the leader and follower words in the pod name, it's really hard to improve it because we need to use a different name to create a Redis cluster.

**Comment by xiaozhuang-a** [comment]
> It needs to be fixed.

Is there any issue follow-up for label updates in Redis cluster mode? I understand that a separate rotation mechanism is needed to regularly obtain Redis cluster status and update it to CR
