### ISSUE TITLE
duplicated containers spec

### ISSUE THREAD

**Issue by litengfei1982** [OT-CONTAINER-KIT/redis-operator#9]
/pkg/utils/statefulsets.go
FinalContainerDef(cr *redisv1alpha1.Redis, role string) []corev1.Container {
	var containerDefinition []corev1.Container

	containerDefinition = append(containerDefinition, GenerateContainerDef(cr, role))

	if cr.Spec.RedisExporter != true {
		containerDefinition = append(containerDefinition, GenerateContainerDef(cr, role))
if set RedisExporter  to false，containerDefinition will be duplicated and stateful set can not be created

**Comment by iamabhishek-dubey** [comment]
Thanks for the bug report, we will check this

**Comment by iamabhishek-dubey** [comment]
Fixed in https://github.com/OT-CONTAINER-KIT/redis-operator/pull/10
