### ISSUE TITLE
Unable to enable/disable AOF via redisConfig

### ISSUE THREAD

**Issue by alita1991** [OT-CONTAINER-KIT/redis-operator#906]
**What version of redis operator are you using?**

redis-operator version: 0.15.1

**Does this issue reproduce with the latest release?**
Yes

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
Client Version: v1.29.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.26.12+k3s1
WARNING: version difference between client (1.29) and server (1.26) exceeds the supported minor version skew of +/-1
</pre></details>

**What did you do?**

I created a Redis instance in standalone mode and I reconfigured the instance with additional config, to disable AOF persistence, which is required to restore from a backup.

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-additional.conf
data:
  redis-additional.conf: |
    appendonly no
```

**What did you expect to see?**

```
127.0.0.1:6379> CONFIG GET appendonly
1) "appendonly"
2) "no"
```

**What did you see instead?**

```
127.0.0.1:6379> CONFIG GET appendonly
1) "appendonly"
2) "yes"
```

**Additional context**

I'm trying to restore from a backup a Redis instance, where mod = Standalone and another Redis cluster with Sentinel + Replication (3 replicas each).

**Comment by asayles** [comment]
Same issue with 0.15.1

**Comment by drivebyer** [comment]
It's fixed by https://github.com/OT-CONTAINER-KIT/redis/pull/7
