### ISSUE TITLE
Build images again

### ISSUE THREAD

**Issue by lapete** [OT-CONTAINER-KIT/redis-operator#908]
**Is your feature request related to a problem? Please describe.**
I'd like to run the latest updates of the operator but the latest image on quay is v0.15.2 and the helmchart isn't up to date either (pointing to v0.15.1).
Image building is halted since #794 

**Describe the solution you'd like**
Fix the image building process

**Additional context**
If there's another way to run v0.16 with helm, please let me know.

**Comment by drivebyer** [comment]
The quay release process is currently on hold, but I've introduced another workflow that pushes images to ghcr.io.

**Comment by dxygit1** [comment]
Has this issue been resolved?

**Comment by drivebyer** [comment]
Not yet. Please wait for the next release.

**Comment by dxygit1** [comment]
Okay, how long will the next version take? We really need this. 

Thank you for your response.

**Comment by drivebyer** [comment]
> Okay, how long will the next version take? We really need this.

I don't know. You could build your own image from https://github.com/OT-CONTAINER-KIT/redis-operator/blob/master/Dockerfile if you really need it in a hurry.

**Comment by drivebyer** [comment]
Image built in: ghcr.io/ot-container-kit/redis-operator/redis-operator:v0.17.0.
New operator chart: https://github.com/OT-CONTAINER-KIT/helm-charts/releases/tag/redis-operator-0.16.1.
