### ISSUE TITLE
v0.16 released - but no image built and chart not updated?

### ISSUE THREAD

**Issue by KlavsKlavsen** [OT-CONTAINER-KIT/redis-operator#909]
v16 was released in march https://github.com/OT-CONTAINER-KIT/redis-operator/releases/tag/v0.16.0
But no image or helm chart update was released?

Is this intentional, or ?

Can I submit a PR for helm chart update? How do you build new images - does CI in this project do it - or is it a manual process only you can do?

**Comment by drivebyer** [comment]
Helm chart is managed by https://github.com/OT-CONTAINER-KIT/helm-charts

**Comment by drivebyer** [comment]
Image built in: ghcr.io/ot-container-kit/redis-operator/redis-operator:v0.17.0.
New operator chart: https://github.com/OT-CONTAINER-KIT/helm-charts/releases/tag/redis-operator-0.16.1.
