### ISSUE TITLE
Expose at least pod SecurityContext through redis-operator helm chart

### ISSUE THREAD

**Issue by ifalex** [OT-CONTAINER-KIT/redis-operator#972]
**Is your feature request related to a problem? Please describe.**

At this moment hardenings for redis-operator can't be performed due to lack of securityContext field in operator Deployment file

**Describe the solution you'd like**

Enable securityContext in redis-operator deployment object.

**Describe alternatives you've considered**

**What version of redis-operator are you using?**

redis-operator version: 0.16.0

**Additional context**

**Comment by abaicu** [comment]
Also because the securityContext is not exposed, I can not make the operator compliant with the PSA restricted policy.

**Comment by ifalex** [comment]
Yes, it worked. Thanks for the promptitude.
