### ISSUE TITLE
Enable readinessProbe on redis-operator deployment

### ISSUE THREAD

**Issue by ifalex** [OT-CONTAINER-KIT/redis-operator#974]
**Is your feature request related to a problem? Please describe.**

Analyzing helm chart for redis-operator with kube-score, fails on Pod Probes

**Describe the solution you'd like**

Enable configuration for readinesProbe if possible technically.

**Describe alternatives you've considered**

**What version of redis-operator are you using?**

redis-operator version: 0.16.2 (helm chart)

**Additional context**

Failure from kube-score
[CRITICAL] Pod Probes
        · Container is missing a readinessProbe
            A readinessProbe should be used to indicate when the service is
            ready to receive traffic. Without it, the Pod is risking to receive
            traffic before it has booted. It's also used during rollouts, and
            can prevent downtime if a new version of the application is failing.
            More information: https://github.com/zegl/kube-score/blob/master/README_PROBES.md

**Comment by drivebyer** [comment]
Thanks for your feedback.
